### ISSUE TITLE
update BLRI, STIL/ELIS, GATE

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#103]
@jimmyrocks just opening this ticket so you can close when nps.nps-places-boundaries is updated.

Thanks!

**Comment by jimmyrocks** [comment]
Cool.
It's been updated it on Friday here: nps.vzp5vcxr
I need someone to verify that the labels and everything are updated and
working correctly.

**Comment by makella** [comment]
Ok I'll take a look and let you know.

**Comment by jimmyrocks** [comment]
If you're out of the office today, I can look at it with Jake and verify if
it's correct or not.

**Comment by makella** [comment]
up to you guys

**Comment by jakecoolidge** [comment]
i can jump on this now before i head out for a dr's appt.

**Comment by makella** [comment]
ok, thanks!

**Comment by jakecoolidge** [comment]
The BLRI boundary geometry is noticeably different; I'm looking in the Ansley Heights area where the polygon is a bit wider. Looks like that update is live in nps.vzp5vcxr. Checking on the other parks now...

**Comment by jakecoolidge** [comment]
Ellis Island and Statue of Liberty look great!

**Comment by jakecoolidge** [comment]
Finally, updated geometries went live for Gateway as well.

**Comment by makella** [comment]
just want to verify that these are now in nps.nps-places-boundaries.  It looks like they are but @jimmyrocks if you can report here and close the issue when done, that would be great.

**Comment by makella** [comment]
Actually, this doesn't look to be updated in nps.nps-places-boundaries... any ETA on this?

mamata

**Comment by jimmyrocks** [comment]
There were mapbox caching issues, I'll be updating it when the mbstudio
server is done with its daily tasks.

**Comment by makella** [comment]
ok, thanks

**Comment by jimmyrocks** [comment]
It looks like this is ready to run, can I put this into **nps.nps-places-boundaries**?

**Comment by makella** [comment]
yes, that would be great!

**Comment by chadlawlis** [comment]
Note: updated with boundaries from the respective parks.
