### ISSUE TITLE
Governors Island building + trails

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#105]
From Mark @ GATE, 8/11/15:

> The Governors Island Imagery on the website is a little old.  So I had Dave digitize the buildings and trails from the current imagery that we have.  The shapefiles are attached.  Could you have those uploaded to Places for us?

Data on Drive [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9Kbfm40YlFuX0NpYkhGU0JhdWZkcXVzcWZrYlJVci1IMngwTHh3MzF0SUduVGs).

**Comment by jimmyrocks** [comment]
I will work with @jakecoolidge to get these trails in tomorrow

**Comment by jakecoolidge** [comment]
Completed.
