### ISSUE TITLE
Add data for CAHA into Places

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#108]
The data can be found in a few different zip files in Basecamp in the CAHA: Places Mobile project.  Leslie no longer works at the park so the contact will be Jorel Terrell. They have uploaded roads, trails, buildings, parking lots and lakes.

**Comment by jakecoolidge** [comment]
This has been around a while, so I've slated Fri. 8/28 to kickstart the process.

**Comment by jakecoolidge** [comment]
Here is a breakdown of the data available on Basecamp:

Buildings: 
- not seeded; duplicates existing Places data, and in most cases the data in Places is better aligned with imagery

Lakes: 
- Places is not supporting lake polygons at this time. We can convert to centroids and import as points,  however lake names were not included, so I would hold off on importing these.
- I suggest lake polygons be used in the mobile app only.

Parking Lots (points):
- These represent an improvement over existing data (better naming, placement, and comprehensiveness) and have been seeded 8/28.

Places of Interest:
- Polygon features, converted to centroids and seeded as points of interest on 8/28 with the following categories: fishing, information, restroom, showers, boat launch, stable, cemetery, scenic viewpoint, ruin, picnic area.

Ramps:
- These might be boat launches. I should verify with CAHA staff before uploading.

Roads:
- This data does appear to fill in some gaps in Places. Manual conflation will be required to stitch it all together. (In progress.)

Trails:
- @nateirwin seeded these on Apr. 23

**Comment by jakecoolidge** [comment]
Roads seeded 8/31, completing the seeding process (with the exception of the ramps).

**Comment by jakecoolidge** [comment]
Per CAHA staff member, Ramps are access points for Off-Road Vehicles. I've uploaded them as ATV access points/trailheads.
