### ISSUE TITLE
Move label for New Bedford Whaling

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#11]
https://github.com/nationalparkservice/park-tiles/issues/128

**Comment by jimmyrocks** [comment]
I think this is an issue with OpenStreetMap and not park tiles, let's go over it:

http://www.openstreetmap.org/#map=19/41.63511/-70.92296
http://www.nps.gov/npmap/tools/park-tiles/#19/41.63490/-70.92384

**Comment by jimmyrocks** [comment]
Is this still a problem?

**Comment by nateirwin** [comment]
Doesn't look like it to me. I'm going to go ahead and close.
