### ISSUE TITLE
Designation for Buck Island Reef needs updating

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#110]
from @jcant624

Looking through Park Tiles 2.1, I noticed an error with a park label. Buck Island shows as "Buck Island Reef BUIS" instead of "Buck Island Reef NM". Thanks for adding marine boundaries. Looks great.
![capture](https://cloud.githubusercontent.com/assets/6653544/9368543/108c704e-4681-11e5-9fbb-08feb7588527.JPG)

**Comment by chadlawlis** [comment]
This has been taken care of.
