### ISSUE TITLE
Weir Farm boundary

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#113]
From Nigel Shaw @ NERO, 8/21/15:

> The boundary for WEFA is shifted to the east and missing a section.  
> 1. Possibly a projection issue?  In the aattached screenshot the green shaded areas come from the NPS Lands boundary service and are spatially correct.  
> 2. Also note the additional property north of the main park unit.  The green parcel is part of WEFA as well.  (Lands needs to delete the abutting parcel (white) and we're in touch with them about that.)

![image](https://cloud.githubusercontent.com/assets/1238636/9448939/bb006c5e-4a5c-11e5-9cef-8fe6f87fdf8b.png)

**Comment by chadlawlis** [comment]
Updated with latest Land Resources Division boundary

**Comment by jimmyrocks** [comment]
![image](https://cloud.githubusercontent.com/assets/98192/9586165/648bb26c-4fd8-11e5-8862-d0f36acd6a0f.png)
Updated with the boundary from Lands. WSD_Parks looks to be offset and old.

**Comment by chadlawlis** [comment]
Reopening this:

> There is a problem with the Lands Boundary for WEFA.  Greg Waters reports:
> 
> The northern parcel boundary now encapsulates the property that we were going to buy at one time but did not.  My guess is that this is the official legislative boundary on record in the Lands office????  Shall I just be patient and wait for the Lands office to correct?
> 
> We understand this is a Lands Office issue, not an NPMap thing, but if you can "fix" it for Places before it goes public we'll all breath easier.  Our Lands Cartographer is out of the office till later this month, but I'm contacting both him and Jean Olson to see how soon this can be sorted out properly at the source.
> 
> See the appended screenshot for clarification.

![image](https://cloud.githubusercontent.com/assets/1238636/9823925/ab065286-5886-11e5-8d89-0f12e9a2eeea.png)

We are awaiting an updated boundary for the park, to replace the one from Land Resources Division.

**Comment by chadlawlis** [comment]
And closing again... All set for now, but we will need to update this once the next Lands iteration is released.

**Comment by chadlawlis** [comment]
Anddd we're back open:

> See the temporary fix to the WEFA boundary file attached to the message from the working-while-vacationing NER Lands Cartographer Mark Duffy, attached.  Please use this for the WEFA boundary in Places until WASO Lands can update their official records.  Mark says Jean is on a fire detail, so the official fix for WEFA won't happen real soon.

Interim boundary [here](https://drive.google.com/drive/u/0/folders/0B0AXEdn7N9KbNVhscV96aGJ2TWM), to override when next iteration of Lands is released.

**Comment by chadlawlis** [comment]
New boundary has been added to CartoDB.

**Comment by chadlawlis** [comment]
Verified new boundary is live in Park Tiles.

**Comment by chadlawlis** [comment]
The updated Lands boundary is now available.

Reopening this - updating in CartoDB to pull from Lands, will confirm when live.

**Comment by chadlawlis** [comment]
Note: the latest Lands boundary is identical to the "interim" boundary sent along by the park here https://github.com/nationalparkservice/places-data/issues/113#issuecomment-139650241, so do not expect to see a different geometry.

Should be all set, closing out.

**Comment by nateirwin** [comment]
Just to verify: Since the boundaries are the same, we are now pulling this from Lands, right?

**Comment by chadlawlis** [comment]
Correct - now pulling from Lands, per the park's request. 

Jim is re-running the tiles today, so this will be pulling from Lands from here on out.
