### ISSUE TITLE
Oxon Cove Park is labeled George Washington Memorial Parkway and GWMP itself is unlabeled 

### ISSUE THREAD

**Issue by johnpauls** [nationalparkservice/places-data#119]
Yet another DC area issue.  Currently Oxon Cove Park ( nps.gov/oxhi ) is labeled as George Washington Memorial Parkway (GWMP) and  the parkway itself has no label. 

![image](https://cloud.githubusercontent.com/assets/5996979/9520446/6bf6caf0-4c95-11e5-9a4f-b90440b9ec8b.png)

The parkway in on the Virginia side of the river, and the land on the Maryland side is a bunch of smaller units managed by National Capital Parks East (NACE). The situation is kind of confusing, as decades ago when the parkway was planned it was going to be on both sides of the river, and some land for it was purchased in MD. It was then decided to just have the parkway in VA and no in MD. However as far as I can tell GWMP still owns the land in MD in  some sense and this is probably reflected in the lands data. However, the land in Maryland is now managed by NACE and is a bunch of different units.

The actual parkway is the land along the Potomac in VA, and currently has no label at all.

**Comment by mtaylorlong** [comment]
@cwlawlis802: Is this worth revisiting? Do we have this correct in our parks table? Seems to still be labeling this way in PT3.

**Comment by chadlawlis** [comment]
The NCR boundary replacement https://github.com/nationalparkservice/places-data/issues/347 will take care of this - we have a new boundary for OXHI, which will be labeled appropriately once implemented, and a more accurate boundary for GWMP.

Note that GWMP will not be labeled at all extents/zoom levels given it is a relatively larger area. As you have mentioned @mtaylorlong these larger areas will really only show labels at lower (zoomed out) zoom levels.
