### ISSUE TITLE
Mis-categorized points of interest in MORA

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#120]
The view of Mount Rainier NP in Park Tiles 2.1 has a surplus of question mark symbols. Many of these are actually natural features, like Sluiskin Falls, that are not marked as exhibits/waysides/information on the Harpers Ferry map. A tune up with JOSM could assign tags to these features that are compliant with our evolving schema and better describe them.

![screen shot 2015-08-27 at 8 27 15 am](https://cloud.githubusercontent.com/assets/11392872/9523082/8d7a14ca-4c95-11e5-9889-2174de67c4d0.png)

**Comment by jakecoolidge** [comment]
This has been fixed for MORA but there are several other parks that need this edit as well. I'm going to run a report to identify them.

**Comment by nateirwin** [comment]
I think DEVA may need some love too. I'm still a little confused as to why this happened? Is it something we'll be able to bulk detect and fix?

**Comment by jakecoolidge** [comment]
I'm not sure what happened either. Here's the count from cartodb of parks where I believe this is happening. You can see LAKE scores pretty high, and DEVA has some as well. MORA's 29 are the ones I just fixed.

These are natural features that were tagged as info exhibits, perhaps as a default when we hadn't yet started tagging things like waterfalls in Places. I don't think it will be an issue going forward; hopefully this is it. 

I'm going to create a separate issue (just one) to track this work.

unit_code,count
lake,64
cany,52
sagu,35
olym,31
arch,29
mora,29
deva,21
meve,20
samo,18
libi,17
pore,15
goga,13
thro,12
havo,12
colm,12
knri,11
sequ,10
deto,9
ciro,8
labe,8
redw,6
lamr,6
orpi,6
glca,6
blca,6
bibe,5
laro,5
rola,5
crla,4
gumo,4
depo,4
grba,4
mana,3
cach,3
hale,3
bica,3
hafo,2
puhe,2
pohu,2
lach,2
dino,2
crmo,2
hove,2
kala,2
orca,1
joda,1
shen,1
rocr,1
beol,1
peco,1
moca,1
rabr,1
cave,1
miss,1
azru,1
klgo,1
lavo,1
sapu,1
grsa,1
moja,1
kaho,1
