### ISSUE TITLE
Load CHIS data

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#122]
The park's GIS Specialist digitized the entire park in OSM. He has given us permission to extract data created under the park's username, Channel_Islands_NPS.

Cc/ @jakecoolidge, @jimmyrocks

**Comment by jakecoolidge** [comment]
Completed, with the exception of buildings. The building geometries are the same for the two datasets, but the buildings in Places have unique identifier fields associated with them (building IDs and FMSS IDs) that we should maintain.
