### ISSUE TITLE
Update boundary for SHEN

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#125]
From Daniel Hurlbert, 8/28

> I was beginning to review Places data for our park and realize that the park boundary layer being used by Places is not correct.  Large areas of land are missing.  Please replace with the attached as the official park boundary.

Boundary [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbUGpEMzVzY1Yxek0).

**Comment by jimmyrocks** [comment]
Can someone figure out how to assemble these lines into a polygon?

**Comment by chadlawlis** [comment]
Sure thing, will do

**Comment by chadlawlis** [comment]
Thought this would be a quick fix in QGIS, turns out it isn't. Emailed Dan for the polygon.

**Comment by chadlawlis** [comment]
Dan sent along the polygon version, available [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbS3AzTnlJTXRoUUk).

@jimmyrocks throwing this back to you for upload to Places.

**Comment by jimmyrocks** [comment]
![image](https://cloud.githubusercontent.com/assets/98192/9590415/aa9e972e-4ff1-11e5-84dc-837681904bb6.png)

updating to the "shen" boundary

**Comment by jakecoolidge** [comment]
Verified new boundary is live in Park Tiles.
