### ISSUE TITLE
CACO roads, trails, and points of interest

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#127]
"CACOroads_places.shp includes NPS roads, parking lot access and connecting town and state- maintained roads that will make sense to a viewer.
CACO_pointsofinterest.shp  has a variety of points of interest that cover visitor use, historic features, visitor services and has attributes to indicate parking lots.
CACO_designatedtrails.shp contains the trails maintained for visitors -- these are listed on the CACO webpage and most have brochures.
CACO_bikepaths.shp are similar -- the officially maintained bike paths."

Data can be found [here.](https://drive.google.com/a/doi.gov/folderview?id=0B8kRL6psDWmZcmNGejlLQmZ2LVE&usp=sharing)

**Comment by jakecoolidge** [comment]
completed

**Comment by nateirwin** [comment]
Nice!
