### ISSUE TITLE
Add unit code to Governors Island data

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#128]
`{"unit_code":"gois"}` - currently missing from data inside park boundary.

**Comment by jimmyrocks** [comment]
The boundary we have for the park is a lot smaller than the area that is
mapped on the island.
It does correctly get its unit code inside the park boundary, but most of
the island is not within that boundary.
Maybe we need to follow up with NPNH on this issue?

**Comment by chadlawlis** [comment]
Hm, shouldn't this point have a unit code? Appears to be inside the rendered boundary:

![gois](https://cloud.githubusercontent.com/assets/1238636/9558728/61600d88-4da6-11e5-8da7-410fccdabd54.jpg)

**Comment by nateirwin** [comment]
Possibly because it was loaded in via JOSM? We need to manually add unit_code in if we're using JOSM.

**Comment by jimmyrocks** [comment]
These were added by an intern at gateway. I'm not sure how it happened,
maybe the points were added before we updated the boundaries, or the intern
deleted the unit_code manually.

In any case, I can run a spatial join on all of the data tomorrow and we
can see if there are any other outliers like this and update them.

**Comment by jimmyrocks** [comment]
This will be fixed by this issue:
https://github.com/nationalparkservice/places-data/issues/131
