### ISSUE TITLE
Update boundary for JEFF

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#129]
From Sue Ford at JEFF, 8/31:

> I was working in the Places Editor one day last week and the next day I went back in do more work and the park boundary had been added by someone else and it's incorrect. It's not too far off it just slid south a bit, but I can't correct it. I don't want to add anything else until we can get the boundary issue straightened out. Can you help? If you need anymore info from me just let me know.

The boundary is currently pulling from `WSD_Parks`.

**Comment by jimmyrocks** [comment]
![image](https://cloud.githubusercontent.com/assets/98192/9583180/11655a40-4fc7-11e5-9aec-350a3012c69e.png)
It looks better in the Lands Dataset, so I'll switch it to use that source.

`UPDATE parks SET poly_source = 'Land Resources Division' WHERE unit_code = 'jeff'`

**Comment by chadlawlis** [comment]
This fix has been verified as live in Editor + Park Tiles.
