### ISSUE TITLE
Label MABI in Vermont earlier and make sure acronym in MABI (not MOBI)

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#13]
https://github.com/nationalparkservice/park-tiles/issues/123

**Comment by jimmyrocks** [comment]
Both moved to Zoom 7:
https://github.com/nationalparkservice/park-tiles-internal/blob/397e85846b77de5b6d22443ed1a220c8a50de970/park_tiles_data_process/nps_data_compilation/scripts/cleanup/label_point_calc_tasks.sql#L318-322

**Comment by makella** [comment]
I'm not seeing this change at z7 in the 3/12/15 update:

http://www.nps.gov/npmap/tools/park-tiles/#7/43.445/-71.131

**Comment by makella** [comment]
this is fixed.
