### ISSUE TITLE
Clean up unit_code capitalization

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#130]
We need to make sure all unit codes are lowercase. Currently, downloading service-wide datasets from the [Places landing page](http://insidemaps.nps.gov/places/) include a variety of both upper and lowercase unit codes.

@jimmyrocks is this something you can run in the database across all parks (`LOWER(unit_code)`)? If not I can start formulating a list of the parks that need attention.

**Comment by jimmyrocks** [comment]
I was going to wait until Friday, but this issue was easy to fix while updating the internal schemas
