### ISSUE TITLE
Preset name changes

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#132]
I recommend the following (from the `name` column in our [preset spreadsheet](https://docs.google.com/spreadsheets/d/1XFqkmIYMEp73q9flgNto9QJim6N5hbacgkUAgdf0rhE/edit#gid=0)):
- "Horseback Riding" :arrow_right: "Horseback Riding Trail"
- "All-terrain Trail" :arrow_right: "All-Terrain Vehicle Trail"

If anyone comes across others, feel free to add to the list here.

**Comment by jakecoolidge** [comment]
If we track changes to the preset spreadsheet as issues here in Github, it can serve to notify us that we may need to update the cartocss in our maps. This is an example of some cartocss I currently have in one of my styles:

[FCategory='Horseback Riding']{marker-file: url(img/symbols/horseback-riding-white-16.svg);}

So if we change "Horseback Riding" to "Horseback Riding Trail", my cartocss needs to be updated to:

[FCategory='Horseback Riding Trail']{marker-file: url(img/symbols/horseback-riding-white-16.svg);}

I'm open to suggestions for what the proper workflow could look like. The source and the style will each get updated, and they will, for a short time, be out of sync. But eventually both will be live on Mapbox and rendering the way we need them to.

**Comment by chadlawlis** [comment]
Adding:
- "Litter Receptacle" :arrow_right: "Waste Basket"

**Comment by chadlawlis** [comment]
Adding:
- "Four Wheel Drive Road" :arrow_right: "Four-Wheel Drive Road" (given we also have "Four-Wheel Drive Trail")

Update: just a note here that we are removing this preset from Editor, though we will continue to support the underlying tag for GIS imports.

**Comment by chadlawlis** [comment]
@jakecoolidge re: https://github.com/nationalparkservice/places-data/issues/132#issuecomment-136845429 let's continue to compile feature name change requests here, as we discussed, given the cartoCSS does not build from the preset spreadsheet. Once you and @jimmyrocks are at a good point to make these changes we can implement, which should be straightforward given all changes will be noted here.

**Comment by chadlawlis** [comment]
Adding:
- "Service Road" :arrow_right: "Access Road" (context: https://github.com/nationalparkservice/places-data/issues/136)

**Comment by jimmyrocks** [comment]
What is the reason for changing "Litter Receptacle" :arrow_right: "Waste Basket"? HFC uses Litter Receptacle for their icons, do we have a source for the new name?

**Comment by chadlawlis** [comment]
I was going from OSM's [`{"amenity":"waste_basket"}`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_basket). But if HFC uses "Litter Receptacle" that's fine by me.

**Comment by jimmyrocks** [comment]
**renamed**:  miscellaneous/entrance/entrance%2fexit.json :arrow_right: building/entrance/entrance_%2f_exit.json
**renamed**:  miscellaneous/cemetery/cemetery.json :arrow_right: miscellaneous/cemetery/cemetery_%2f_graveyard.json
**renamed**:  road/four_wheel_drive/four_wheel_drive_road.json :arrow_right: road/four_wheel_drive/four-wheel_drive_road.json

**changed class**:  building/building/cabin.json :arrow_right: building/cabin/cabin.json
**changed class**:  building/primitive/hut.json :arrow_right: building/shelter/hut.json
**changed class**:  building/primitive/shelter.json :arrow_right: building/shelter/shelter.json
**changed class**:  miscellaneous/battlefield/battlefield.json :arrow_right: historic/battlefield/battlefield.json
**changed class**:  miscellaneous/cannon/cannon.json :arrow_right: historic/cannon/cannon.json
**changed class**:  miscellaneous/monument/monument.json :arrow_right: historic/monument/monument.json
**changed class**:  miscellaneous/ruin/historic_ruins.json :arrow_right: historic/ruin/historic_ruins.json
**changed class**:  miscellaneous/ship/historic_ship.json :arrow_right: historic/ship/historic_ship.json
**changed class**:  miscellaneous/site/historic_site.json :arrow_right: historic/site/historic_site.json
**changed class**:  miscellaneous/wreck/wreck.json :arrow_right: historic/wreck/wreck.json
**changed class**:  miscellaneous/fort/fortification.json :arrow_right: miscellaneous/structure/fortification.json
**changed class**:  miscellaneous/manmade/tower.json :arrow_right: miscellaneous/structure/tower.json
**changed class**:  natural_feature/reef_(bar)/reef_(bar).json :arrow_right: natural_feature/reef/reef_(bar).json
**changed class**:  trail/non-motorized/pedestrian_street.json :arrow_right: road/minor/pedestrian_street.json
**changed class**:  trail/water/motorized_trail.json :arrow_right: trail/motorized/motorized_trail.json
**changed class**:  trail/non-motorized/non-motorized_watercraft_trail.json :arrow_right: trail/water/non-motorized_watercraft_trail.json

**new preset**:  miscellaneous/view/overlook.json
**new preset**:  building/shelter/gazebo.json
**new preset**:  building/shelter/pavilion.json
**new preset**:  historic/marker/battlefield_marker.json
**new preset**:  historic/marker/historic_marker.json
**new preset**:  historic/monument/memorial.json
**new preset**:  land_recreation/camping/horse_camp.json
**new preset**:  land_recreation/playground/playground.json
**new preset**:  locality/region/populated_place.json
**new preset**:  natural_feature/arch/natural_bridge.json

**removed**: locality/boundary/park.json

**Comment by jimmyrocks** [comment]
**renamed**: road/service/service_road.json :arrow_right: road/service/access_road.json
**renamed**: trail/non-motorized/horseback_riding.json :arrow_right: trail/non-motorized/horseback_riding_trail.json

**Comment by chadlawlis** [comment]
What about "All-terrain trail" :arrow_right: "All-Terrain Vehicle Trail"?

**Comment by chadlawlis** [comment]
This has been added - "All-terrain trail" just had not been removed. Removed now.

**Comment by chadlawlis** [comment]
Everything else looks fine to me - let's plan on closing this out after the Places concall this afternoon.

**Comment by chadlawlis** [comment]
All set here.
