### ISSUE TITLE
Mis-categorized points of interest

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#133]
The following are, in most cases, natural features (waterfalls, ect.) that are tagged as info exhibits/waysides in Places (see [this issue](https://github.com/nationalparkservice/places-data/issues/120)):

unit_code,count
~~lake,64~~
~~cany,52~~
~~sagu,35~~
~~olym,31~~
~~arch,29~~
~~deva,21~~
~~meve,20~~
~~samo,18~~
~~libi,17~~
~~pore,15~~
~~goga,13~~
~~thro,12~~
~~havo,12~~
~~colm,12~~
knri,11 these appear to be actual info waysides and were not updated
~~sequ,10~~
deto,9 information panels, not updated
~~ciro,8~~
~~labe,8~~

**Comment by jakecoolidge** [comment]
completed parks shown as strikeouts; this should eliminate the excess info symbols appearing in Park Tiles

**Comment by nateirwin** [comment]
:+1:

**Comment by jimmyrocks** [comment]
👍👍
