### ISSUE TITLE
Removing "Hospital Building", "Hotel Building", "Four-Wheel Drive Road" presets

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#134]
@asouthwould we would like to propose the removal of these two point presets. "Hotel Building" is effectively a duplicate of "Lodging" and "Hospital Building" is a duplicate of "Hospital". Are there any specific use cases you had in mind that we should know about, or other concerns associated with removing these?

Copying @jimmyrocks for his visibility.

**Comment by chadlawlis** [comment]
Adding "Four-Wheel Drive Road" to this list of what we'd like to remove. 

@asouthwould, I remember that both the road and trail GIS standards include a four-wheel drive vehicle classification, as follows (from our work during the mapathon):
- Road: `RDCLASS=4WD`
- Trail: `TRLUSES=Four-Wheel Drive Vehicle > 50" in Tread Width`

In Editor, we have both "Four-Wheel Drive Road" (which `RDCLASS=4WD` maps to) and "Four-Wheel Drive Trail" (which `TRLUSES=Four-Wheel Drive Vehicle > 50" in Tread Width` maps to). We would like to remove "Four-Wheel Drive Road" from the Editor, so that "Four-Wheel Drive Trail" is the only preset that comes up when "four wheel..." is searched, but we would also like to remove the tag altogether if it's possible to map both GIS classifications to "Four-Wheel Drive Trail".

For now, we are removing the road from editor and will await your feedback as to hanging on to the preset in general or removing it.

Thanks!

**Comment by asouthwould** [comment]
I support removing Hotel Building and using Lodging.
I support removing Hospital Building and using Hospital.
I agree that these two changes will simplify choices.

I do NOT support the merging of Four-Wheel Drive Road and Four-Wheel Drive Trail. 

I know this may seem confusing, but 4WD access is permissible within both the Roads and Trails spatial data standards because this is a valid classification for either of these entities. To physically observe one of these 4WD paths, you may not be able to discern between the two. It is more of a political decision by the park to call something a "Road" or a "Trail" and those two terms should not be interchanged. With that, if the park directs me to put a feature into their Roads dataset and classify it as a 4WD road, I feel very uncomfortable with that being reclassified and publicly displayed as a trail. Or vice versa. Thanks!

**Comment by chadlawlis** [comment]
Sounds good, thanks Angie. We are going to remove the "Four-Wheel Drive Road" preset from Places Editor for now, to avoid confusion for people tracing from satellite imagery, but we will continue to support it for GIS imports. If it turns out parks would like the option for both we can always add it back in.

**Comment by asouthwould** [comment]
That sounds good to us... as long as 4WD "Trails" coming in from GIS are rendered more like the other trail features and 4WD "Roads" are rendered more like the other road features. I think that's going to be the most important factor from the park perspectives; they will want distinction between the look of these two feature types on a map. Thanks!

**Comment by nateirwin** [comment]
Ugh, now I'm kind of having second thoughts about this. What are you thinking, @cwlawlis802?

**Comment by chadlawlis** [comment]
@nateirwin well, the underlying tag for the road classification will still be supported, so it should continue to be accessible cartographically. Users just won't be able to add this as a preset directly through Editor. 

What are you thinking?

**Comment by nateirwin** [comment]
Guess I'm just thinking that maybe we should continue to support both "Four-Wheel Drive Road" and "Four-Wheel Drive Trail". I was focused on making the presets in Places Editor more intuitive, but I think @asouthwould brings up a really good point about parks wanting to add this use case to both roads and trails.

**Comment by chadlawlis** [comment]
Okay, we can add it back in... We won't include it in the default road preset list, but it will be searchable.

**Comment by jimmyrocks** [comment]
We can also leave it in there so it's not even searchable, but will still
show up if someone manually enters the tags.

**Comment by chadlawlis** [comment]
Just to tie up any loose ends here, we are continuing to support "Four-Wheel Drive Road" in Editor as search-only.

"Hospital Building" and "Hotel Building" have been removed.

**Comment by jimmyrocks** [comment]
- "Four-Wheel Drive Road" is actually set to unsearchable in iD. It can
  only be added through import or JOSM.
- "Hospital Building" has been deleted
- "Hotel Building" has been merged with "Lodging"

**Comment by chadlawlis** [comment]
`inEditor` is currently set to `TRUE`, is that not the field dictating searchability in Editor?

**Comment by jimmyrocks** [comment]
That is the field dictating searchability in Editor.

**Comment by chadlawlis** [comment]
Set to `FALSE` now, we're good!
