### ISSUE TITLE
Add boundary for Fort Monroe National Monument

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#135]
It isn't currently in our boundaries dataset, but it is definitely a legit unit: http://www.nps.gov/fomr/index.htm.

**Comment by chadlawlis** [comment]
Added to https://github.com/nationalparkservice/places-data/wiki/Tracking-Boundary-Updates. This boundary does not appear to be in the latest Land Resources Division dataset.

**Comment by jimmyrocks** [comment]
There are two labeling issues with the new boundaries dataset, so I'm going to be rerunning it. If someone can get me this boundary, I can add it in before the next run.

**Comment by chadlawlis** [comment]
@jimmyrocks where is this new boundary living? Would be great to get it up on Drive [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbcU9RMDNrVTN4UDg).

**Comment by chadlawlis** [comment]
This has been implemented. @jimmyrocks to post boundary to Drive.

**Comment by chadlawlis** [comment]
On Drive [here](https://drive.google.com/drive/u/0/folders/0B0AXEdn7N9KbVURHS19hUmxPV0E)
