### ISSUE TITLE
Update boundary for HAMP

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#138]
From the park.

https://drive.google.com/a/doi.gov/folderview?id=0B9Ygi7kxEFrBeVdWTkN6aUF3ZWs&usp=sharing

**Comment by nateirwin** [comment]
Follow up with william_curtis@nps.gov when the boundary has been updated.

**Comment by jimmyrocks** [comment]
This was updated from IRMA/Lands 16 days ago: https://github.com/nationalparkservice/places-data/issues/42

**Comment by jakecoolidge** [comment]
Verified, this is now drawing correctly in Park Tiles.

**Comment by chadlawlis** [comment]
Great, tracking updated in https://github.com/nationalparkservice/places-data/wiki/Tracking-Boundary-Updates as well.
