### ISSUE TITLE
HALE boundary

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#140]
We might still be missing a piece of HALE in our boundary dataset.

Originally tracked with [this issue.](https://github.com/nationalparkservice/places-data/issues/90)

**Comment by jimmyrocks** [comment]
Thanks for opening this as a separate issue.

**Comment by ryanjhodge** [comment]
This just reminded me... I brought this issue up with Scott Kichman (GIS Specialist for Pacific Islands Network) and he's going to weigh in via Email to Nate.

> I will send Nate what I know has been approved by Haleakala folks

**Comment by nateirwin** [comment]
From Scott:

"Hello all, This is the boundary that has been approved by both Lands Division and the Steering Committee folks for PACN

It is projected 

Projected Coordinate System:    NAD_1983_UTM_Zone_4N
Projection: Transverse_Mercator
false_easting:  500000.00000000
false_northing: 0.00000000
central_meridian:   -159.00000000
scale_factor:   0.99960000
latitude_of_origin: 0.00000000
Linear Unit:    Meter

Geographic Coordinate System:   GCS_North_American_1983
Datum:  D_North_American_1983
Prime Meridian:     Greenwich
Angular Unit:   Degree

If you have any questions or issues, just give a holla!"

**Comment by nateirwin** [comment]
And a link to the dataset: https://drive.google.com/open?id=0B9Ygi7kxEFrBQmVRX2lzT3kxRFU

**Comment by chadlawlis** [comment]
Updated in CartoDB, will confirm when live once boundaries have been re-run.

**Comment by chadlawlis** [comment]
This is now live.
