### ISSUE TITLE
GEWA data

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#149]
"This data is a subset of what came from the NR Condition Assessments for (this park).  Some pretty old, but best available."

Data stored [here.](https://drive.google.com/a/doi.gov/folderview?id=0B8kRL6psDWmZRy0tcmNrMnhJdEU&usp=sharing)

**Comment by cwlawlis802** [comment]
Can't open `.mdb` provided, so unable to determine the themes available.

**Comment by cwlawlis802** [comment]
Reached out to Nigel to send this along in another format.

**Comment by chadlawlis** [comment]
This is in `.mdb` format - I forwarded along to Paul who is converting it to `.gdb`.

**Comment by chadlawlis** [comment]
Data is [here](https://drive.google.com/drive/u/1/folders/0B8kRL6psDWmZRy0tcmNrMnhJdEU) in `.gdb` format. 

Includes points of interest, buildings, roads, trails (among a variety of other data).

**Comment by chadlawlis** [comment]
Seeded:
- Points of interest (limited: fire hydrants, water fountains, water wells)
  - GDB layers: `gewa_fire_hydrant`, `utility_points`
- Roads
  - GDB layer: `GEWA_Roads` (heavily altered geometries), `circulation_poly` (no geometries, only for road surface types and a couple of names)
- Fences
  - GDB layer: `small_scale_feature_line`
- Building footprints
  - GDB layer:  `buildings_and_structures_poly`

Trails (`WMCO_Trails`) overlapped existing, not seeded.

**Comment by cwlawlis802** [comment]
Before screenshot with x-ray basemap here: https://api.tiles.mapbox.com/v4/nps.080c11a9/-76.92380189895628,38.191901685819545,16/980x1156@2x.png?access_token=pk.eyJ1IjoibnBzIiwiYSI6IkdfeS1OY1UifQ.K8Qn5ojTw4RV1GwBlsci-Q

Take after using this link: http://insidemaps.nps.gov/mapshot/?basemap=x-ray-view&exportRetina=true&height=1166&width=1280#16/38.1919/-76.9238

**Comment by cwlawlis802** [comment]
After screenshot with x-ray: https://api.tiles.mapbox.com/v4/nps.080c11a9/-76.9238,38.1919,16/980x1166@2x.png?access_token=pk.eyJ1IjoibnBzIiwiYSI6IkdfeS1OY1UifQ.K8Qn5ojTw4RV1GwBlsci-Q
