### ISSUE TITLE
Label Cumberland Gap one zoom level sooner

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#15]
https://github.com/nationalparkservice/park-tiles/issues/110

**Comment by jimmyrocks** [comment]
Can't really be done (conflicting labels).. see more here:
https://github.com/nationalparkservice/park-tiles-internal/commit/c916bfc254fcc15fd06d740295b019c43c2e4ead#diff-1d1501ca5cd56b2cba609d05085e8db5
