### ISSUE TITLE
THST data

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#150]
"This data is a subset of what came from the NR Condition Assessments for (this park).  Some pretty old, but best available."

Data stored [here.](https://drive.google.com/a/doi.gov/folderview?id=0B8kRL6psDWmZaVBPR2xNV0sxX28&usp=sharing)

**Comment by chadlawlis** [comment]
Points of interest, roads, and trails (among a variety of other data, not for use in Places).

**Comment by jakecoolidge** [comment]
Roads seeded. Trails data is outside the park boundary, and point data are for spot elevations.
