### ISSUE TITLE
HOME data

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#151]
Data stored [here.](https://drive.google.com/a/doi.gov/folderview?id=0B8kRL6psDWmZdm5rd3VxUkd3TFk&usp=sharing)

**Comment by chadlawlis** [comment]
Buildings, parking lots, points of interest, roads, and trails.

Also boundaries and hydrology.

**Comment by jakecoolidge** [comment]
Seeded buildings, parking lots, points of interest, roads and trails.
