### ISSUE TITLE
MISS POI data

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#153]
Points of interest at this point; other themes are in development.

Data stored [here.](https://drive.google.com/open?id=0B8kRL6psDWmZUEZXN1dFRGNLWlk)

**Comment by chadlawlis** [comment]
Seeded, including `{"leisure":"park"}` for `type=Park`, which is in the queue for addition to Editor as a preset here https://github.com/nationalparkservice/places-data/issues/208.

All existing duplicates were removed, replaced with the points from the seed.
