### ISSUE TITLE
SLBE trails and parking lots

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#156]
"Other comments:

"You already have a points of interest layer we can edit in Places. But - you should (easily) update Trailheads in that Places of Interest layer to match names in the attached trail file (currently your layer has no names, just numbers for all trailhead "names")."

Buildings and roads pending at this time.

Data stored [here.](https://drive.google.com/open?id=0B8kRL6psDWmZaE1IQmQtaUtGZmc)

**Comment by nateirwin** [comment]
I'm happy to help update the trailhead names once the trails are loaded.

**Comment by jakecoolidge** [comment]
Great! I'll notify you once it's up and running.

**Comment by jakecoolidge** [comment]
seeded trails and parking lot points; also updated trailheads with names to match adjacent trails.
