### ISSUE TITLE
BOHA data

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#158]
Asked contributor to resend link to Google Drive item; permissions are blocking access.

**Comment by chadlawlis** [comment]
I now have access, and Andrew is providing access for you as well Jake.

Data [here](https://drive.google.com/drive/u/1/folders/0B8kRL6psDWmZWUJEdVNZWkRHSmc).

**Comment by chadlawlis** [comment]
Points of interest, roads, trails, and parking lots (among other data).

**Comment by jakecoolidge** [comment]
Of the layers provided, the following have been uploaded to Places:
- LIGHTHOUSES_PT
- Docks
- FORTS
- BOHA_paths
- EOTROADS_ARC
- cemetary_pt_BOHA
- graves_BOHA
- Historic_Structures
- Parking_Lot_BOHA
- Ranger_Stations
- Tent_camping
- Toilet
- VisitorsCenters
- Vistas
- Yurt_camping

Duplicates of the above layers were not uploaded. 

The following layers are either well outside park boundaries or outside the scope of Places and were not uploaded:
- Seaports
- seawalls_arc
- pierlin_arc
- biketrails_arc
- ASMIS_subsites
- ASMIS_sites
- majmhdr1
- MBTAParkingLots_BOHA
- ParknRideLots_BOHA
- bhi_park_area
