### ISSUE TITLE
Look into labeling Alibates Flint Quarries National Monument sooner

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#16]
https://github.com/nationalparkservice/park-tiles/issues/109

**Comment by jimmyrocks** [comment]
Somewhere in between data and cartography problem

**Comment by nateirwin** [comment]
I should/will follow up with Kat Kirby and Ginny Reams when completed.

**Comment by chadlawlis** [comment]
Not sure if there is anything new here to discuss but it appears to be labeling at Z9 still. Looks fine to me, not sure if it's still a problem for state pages? @nateirwin

**Comment by nateirwin** [comment]
Sounds to me like we can close this one out. It was good feedback, but not sure there's anything we can do about it.
