### ISSUE TITLE
Adding label-only records for FRST

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#160]
Originally opened as [a Places Editor issue.](https://github.com/nationalparkservice/places-editor/issues/84) Opening here because it affects not just Places Editor but all maps, including Park Tiles. FRST is comprised of three sites spanning the length of Delaware; see page 2 of [their brochure.](http://www.nps.gov/frst/loader.cfm?csModule=security/getfile&pageID=539714) Currently only the northernmost site is represented on our maps. [Park Tiles example](http://www.nps.gov/npmap/tools/park-tiles/#12/39.8006/-75.5295)

**Comment by chadlawlis** [comment]
This has finally been addressed here https://github.com/nationalparkservice/places-data/issues/416.

The link to FRST's brochure http://www.nps.gov/frst/loader.cfm?csModule=security/getfile&pageID=539714 indicates "The specified document no longer exists" and I can't seem to find a brochure map via HFC http://www.nps.gov/hfc/cfm/carto.cfm.

I can export this from the parks table and determine logical label-only points from that.

**Comment by chadlawlis** [comment]
Currently, the largest of the four areas of FRST is labeled in PT3: http://insidemaps.nps.gov/park-tiles-3/#14/39.8282/-75.5663

The next area south is here: http://insidemaps.nps.gov/park-tiles-3/#17/39.73809/-75.54075#17/39.73809/-75.54075. Adding a label-only record to the places_boundaries parks table via the following:

``` sql
INSERT INTO parks (
  unit_id,
  unit_name_short,
  unit_name_long,
  unit_desig_abbr,
  unit_desig_full,
  unit_code,
  simp_type,
  geom_point,
  data_source)
VALUES (
  (SELECT max(unit_id) + 1 FROM parks),
  (SELECT unit_name_short FROM parks WHERE unit_id = '155'),
  (SELECT unit_name_long FROM parks WHERE unit_id = '155'),
  (SELECT unit_desig_abbr FROM parks WHERE unit_id = '155'),
  (SELECT unit_desig_full FROM parks WHERE unit_id = '155'),
  (SELECT unit_code FROM parks WHERE unit_id = '155'),
  (SELECT simp_type FROM parks WHERE unit_id = '155'),
  (SELECT ST_GeomFromText('POINT(-75.540598 39.738420)', 4326)),
  'Label-only');
```

The next area south after that is here: http://insidemaps.nps.gov/park-tiles-3/#17/39.66016/-75.56348

``` sql
INSERT INTO parks (
  unit_id,
  unit_name_short,
  unit_name_long,
  unit_desig_abbr,
  unit_desig_full,
  unit_code,
  simp_type,
  geom_point,
  data_source)
VALUES (
  (SELECT max(unit_id) + 1 FROM parks),
  (SELECT unit_name_short FROM parks WHERE unit_id = '155'),
  (SELECT unit_name_long FROM parks WHERE unit_id = '155'),
  (SELECT unit_desig_abbr FROM parks WHERE unit_id = '155'),
  (SELECT unit_desig_full FROM parks WHERE unit_id = '155'),
  (SELECT unit_code FROM parks WHERE unit_id = '155'),
  (SELECT simp_type FROM parks WHERE unit_id = '155'),
  (SELECT ST_GeomFromText('POINT(-75.563340 39.660231)', 4326)),
  'Label-only');
```

And the next area south after that, being the final area, is here http://insidemaps.nps.gov/park-tiles-3/#17/39.15620/-75.52341

``` sql
INSERT INTO parks (
  unit_id,
  unit_name_short,
  unit_name_long,
  unit_desig_abbr,
  unit_desig_full,
  unit_code,
  simp_type,
  geom_point,
  data_source)
VALUES (
  (SELECT max(unit_id) + 1 FROM parks),
  (SELECT unit_name_short FROM parks WHERE unit_id = '155'),
  (SELECT unit_name_long FROM parks WHERE unit_id = '155'),
  (SELECT unit_desig_abbr FROM parks WHERE unit_id = '155'),
  (SELECT unit_desig_full FROM parks WHERE unit_id = '155'),
  (SELECT unit_code FROM parks WHERE unit_id = '155'),
  (SELECT simp_type FROM parks WHERE unit_id = '155'),
  (SELECT ST_GeomFromText('POINT(-75.524082 39.156161)', 4326)),
  'Label-only');
```

Then, set the SRID to 3857 for all FRST records:

``` sql
UPDATE parks
SET geom_point = ST_Transform(ST_SetSRID(geom_point, 4326), 3857)
WHERE unit_code = 'frst';
```

**Comment by chadlawlis** [comment]
These are showing up correctly in QGIS - handing over to @mtaylorlong to populate carto fields.

**Comment by mtaylorlong** [comment]
Done! Main label appears at z9 and the secondary labels appear at z12.
