### ISSUE TITLE
Add preset for docks/piers

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#161]
We have a mobile project where we'd like to render the docks/piers at a ferry terminal (among others) as polygons. The OSM tag for this type of structure is ["man_made":"pier"](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpier).

**Comment by chadlawlis** [comment]
Good timing - this is already in the queue from last week's Places call, to be called "Boat Dock" with the same tag as you mentioned: https://docs.google.com/document/d/1G-Jx5OcYdkYMKNVuhhsg-WyFqqeGrRRBIU5dhjG7_-U/edit (Water Recreation > Boat > Boat Dock)

**Comment by jimmyrocks** [comment]
The distinction that Jake would like is it should also be an area

**Comment by chadlawlis** [comment]
Fine by me

**Comment by nateirwin** [comment]
I'm good with this too. Perhaps we should treat fortifications this way, as well? We've had a few requests from parks and others that want to map fortifications as areas - not just points.

**Comment by chadlawlis** [comment]
Changing the tag to `{"man_made":"pier","mooring":"yes"}` per http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpier.

Will add "Boat Dock" as both a point and an area.

**Comment by chadlawlis** [comment]
Adding Fortification as area as well: https://github.com/nationalparkservice/places-data/issues/50#issuecomment-145980616

**Comment by chadlawlis** [comment]
Added to spreadsheet, now live in Editor for both "Boat Dock" (as point and area) and "Fortification" (as both point and area).

**Comment by nateirwin** [comment]
Looks like fortification is a subclass under building? Think maybe it should be out its own class?

**Comment by jimmyrocks** [comment]
We decided to put Fortification under Building so that it would show up as a building if there was no other style associated with it.

**Comment by nateirwin** [comment]
I guess this could be ok, but a lot of fortifications are just earthen berns and aren't anything close to a building. To me, it makes more sense for them to have their own classification... and in the future I could see us differentiating between the different types of fortifications.

**Comment by jimmyrocks** [comment]
We were discussing a larger classification for all areas, so enclosed structures can be one, decks/piers/patios/fountains (open structures) can be another, and natural features could be the last. We'll probably need some input from @jakecoolidge and @mtaylorlong on these ideas.

**Comment by nateirwin** [comment]
Ok, but fortifications don't seem to fit into any of those classifications? And that still doesn't address the issue that most fortifications are not buildings, yet they're grouped under the building classification.

**Comment by jimmyrocks** [comment]
Yeah, we originally only made the buildings classification, because we were not supporting any other areas. I'm sure @jakecoolidge and @mtaylorlong have more cartographic and on-the-ground experience than I do, so hopefully they'll have better classifications.
