### ISSUE TITLE
GOSP data from IMR

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#165]
Points of Interest, Parking Lots, Roads, and Trails. (Buildings will be available later via the national feature service.) Data stored [here.](https://drive.google.com/a/doi.gov/folderview?id=0BweNz2Mvs1oINFNXcmxnby1NbWM&usp=sharing)

**Comment by jakecoolidge** [comment]
Eric to resend with next batch of data.

**Comment by chadlawlis** [comment]
New data received 10/26, [here](https://drive.google.com/drive/u/1/folders/0B6O6-Wj7RWnYd2J6WHRVdTdkZm8).

**Comment by jakecoolidge** [comment]
Seeding will be handled by sync tool.
