### ISSUE TITLE
MAWA Boundary

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#167]
per Andrew at RICH, current boundary is incorrect. Park boundary stored on Drive [here.](https://drive.google.com/open?id=0B8kRL6psDWmZdzhsRDNIUDUwUTg)

**Comment by chadlawlis** [comment]
Updated in CartoDB, will confirm and close when live.

**Comment by chadlawlis** [comment]
Confirmed as updated.
