### ISSUE TITLE
Seed data for NCR parks

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#170]
This is a data seed from the National Capital Region: [Link](https://drive.google.com/open?id=0B9Ygi7kxEFrBWWY3bWVYSlFnV00). It includes data for all of their parks. Some detail:

> There are two feature classes that are trails-related: trails and paths.  The trails are more conventional trails and the paths are primarily in the National Mall and Memorial Parks (NAMA).  This distinction exists in our database because NAMA treats their pathways in FMSS differently than most parks.  However, you probably don't care about the distinction for Places.  The points of interest is a pretty extensive dataset, but corresponds primarily to points of interest typically found on the brochure maps.  The roads centerlines is the least developed on these datasets and doesn't include the entirety of the C&O Canal NHP.

**Comment by chadlawlis** [comment]
Park units included in this seed, by feature type:

| unit_code | unit_name | POI | Trails | Roads |
| --- | --- | --- | --- | --- |
| ANAC | Anacostia Park | X | X |  |
| ANTI | Antietam National Battlefield | X | X | X |
| APPA | Appalachian National Scenic Trail |  | X |  |
| ARHO | Arlington House National Historic Site | X |  |  |
| BAWA | Baltimore-Washington Parkway |  |  | X |
| CATO | Catoctin Mountain Park | X | X | X |
| CHOH | Chesapeake & Ohio Canal National Historical Park | X | X | X |
| CLBA | Clara Barton National Historic Site | X |  |  |
| CLMO | Claude Moore Farm | X |  |  |
| COGA | Constitution Gardens | X |  |  |
| FODU | Fort Dupont Park | X | X |  |
| FOFO | Fort Foote | X | X | X |
| FOWA | Fort Washington Park | X | X | X |
| FRDE | Franklin Delano Roosevelt Memorial | X |  |  |
| FRDO | Frederick Douglass National Historic Site | X |  |  |
| GEMM | George Mason Memorial | X |  |  |
| GLEC | Glen Echo Park | X |  |  |
| GREE | Greenbelt Park | X | X |  |
| GRFA | Great Falls Park | X | X |  |
| GWMP | George Washington Memorial Parkway | X | X | X |
| HAFE | Harpers Ferry National Historical Park | X | X | X |
| HAHA | Harmony Hall |  | X | X |
| KEAQ | Kenilworth Park and Aquatic Gardens | X | X |  |
| KOWA | Korean War Veterans Memorial | X |  |  |
| LIME | Lincoln Memorial | X |  |  |
| LYBA | Lyndon Baines Johnson Memorial Grove on the Potomac | X |  |  |
| MANA | Manassas National Battlefield Park | X | X | X |
| MONO | Monocacy National Battlefield | X | X | X |
| NACE | National Capital Parks - East | X | X | X |
| NAMA | National Mall and Memorial Parks | X | X |  |
| NCRO | East Potomac Park | X |  |  |
| OXHI | Oxon Cove Park & Oxon Hill Farm | X | X | X |
| PAAV | Pennsylvania Avenue National Historic Site |  | X |  |
| PISC | Piscataway Park | X | X | X |
| PRWI | Prince William Forest Park | X | X | X |
| ROCR | Rock Creek Park | X | X |  |
| SUIT | Suitland Parkway |  |  | X |
| THIS | Theodore Roosevelt Island | X | X |  |
| THJE | Thomas Jefferson Memorial | X |  |  |
| VVME | Vietnam Veterans Memorial | X |  |  |
| WAMO | Washington Monument | X |  |  |
| WHHO | Lafayette Square | X | X |  |
| WOTR | Wolf Trap Park for the Performing Arts | X | X | X |
| WWII | World War II Memorial | X |  |  |

**Comment by jakecoolidge** [comment]
completed

**Comment by nateirwin** [comment]
:boom:
