### ISSUE TITLE
SACR data

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#171]
From ACAD's GIS Specialist:

> I've worked with our media specialist in Interpretation and we would like you to replace the seeded data in Places for SACR with the data in the following zipped file.  
> Some things to note:
> 
> 1) I don't have a line layer for the roads at SACR, only the polygons that are in ParkingLots
> 2) I've included a better boundary layer for SACR.
> 3) the trails are all pedestrian only.

Here's a [link](https://drive.google.com/open?id=0B9Ygi7kxEFrBcHVpMlZPbEVHN2c).

**Comment by chadlawlis** [comment]
Created a separate issue for the boundary https://github.com/nationalparkservice/places-data/issues/173 and copied the boundary data [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbRzJSSFRFNHduaGM) as well.

**Comment by jakecoolidge** [comment]
completed
