### ISSUE TITLE
Whitman Mission should be labeled sooner

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#174]
A visitor to the NPS.gov Washington state page let us know that Whitman Mission National Historic Site is missing from the map. They do have a website: http://www.nps.gov/whmi/.

**Comment by chadlawlis** [comment]
To clarify, this boundary is in Places (pulling from WSD_Parks) and it is in Park Tiles as well, including on the state page. It is just not labeling at the landing zoom of the state page map:

![whmi_state_page](https://cloud.githubusercontent.com/assets/1238636/10465688/6a97328e-71ad-11e5-9f98-0ae6130d40fc.jpg)

**Comment by chadlawlis** [comment]
Copying @jakecoolidge + @mtaylorlong for a fix on the carto side.

**Comment by jimmyrocks** [comment]
This is something I can fix in the meantime, just let me know what zoom it
should show up at, and I'll change the code around. It looks like it may
conflict with Nez Perce, but we can look at it.

**Comment by mtaylorlong** [comment]
Whitman Mission's label appears at z7 now. There's room for it at z6, but I think it's okay to wait for one more click. :smiley_cat:
