### ISSUE TITLE
ACAD data

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#175]
From the park's GIS Specialist:

> I've worked with our media specialist in Interpretation and we would like you to replace the seeded data in Places for ACAD with the data in the following zipped geodatabase. Some things to note:  
> 
> 1) the non-motorized trails layer has two extra attributes LEN_MILE and ALT_NAME. We would like to be able to have the information in those fields available for use in the pop-up boxes in Places
> 2) the roads layer has one extra attribute ONEWAY (text field, either Y or N). I think this ends up as a tag in Places.
> 3) the geodatabase contains a feature class for ACAD's boundary, which is only slightly different from what you have up there now.
> 4) many of these layers will have data that seems to fall outside the fee-ownership boundary on the Schoodic Peninsula. These facilities are on an NPS-held conservation easement and we have an agreement to manage them. I'm not sure if you have a way of showing less-than-fee ownership, so I did not include this in the boundary layer. Contact me if you want to discuss this.

[Link to data](https://drive.google.com/open?id=0B9Ygi7kxEFrBcG1lV2xub255MGs)

**Comment by chadlawlis** [comment]
Points of interest, roads, trails, buildings, parking.

Also a boundary.

**Comment by jakecoolidge** [comment]
completed
