### ISSUE TITLE
Missing parks?

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#176]
This list came from @bmclane-NPS:
- Manhattan Project National Historical Park (all 3 units)
- Harriet Tubman Underground Railroad National Monument
- Hanouliuli National Monument

**Comment by ryanjhodge** [comment]
Tule Springs Fossil Beds National Monument is on Park Tiles (TUSK).  It's directly North of Las Vegas.

![capture](https://cloud.githubusercontent.com/assets/4172213/10501014/02995e9c-7292-11e5-9a85-9543966779d6.PNG)

**Comment by nateirwin** [comment]
Great. I'll take it out of the list!

**Comment by chadlawlis** [comment]
Honouliuli (HONO) is in Park Tiles as well, but not available through Park Tiles search (it is available in the Editor dropdown list, however).

TUSK is also not available through Park Tiles search. It is available in the Editor dropdown list.

We do not have a boundary for Harriet Tubman Underground Railroad National Monument (HATU), which needs to be added into CartoDB along with the Park Tiles and Editor search/dropdown functions.

@nateirwin which parks (3 units?) constitute Manhattan Project National Historical Park?

**Comment by chadlawlis** [comment]
Created separate issue for HATU here: https://github.com/nationalparkservice/places-data/issues/178

**Comment by jimmyrocks** [comment]
The dropdown list only includes parks that have a geometry, because you
can't zoom to a park that doesn't have a geometry. So I'd guess that HONO
does not have a geometry in CartoDB.

**Comment by nateirwin** [comment]
I think we have this figured out. Chad is upgrading the Park Tiles viewer to NPMap.js 3, which now pulls in from CartoDB. That should resolve the issue for all the parks but HATU and Manhattan Project. We just created individual issues for these (they don't exist in our database yet), so I'm going to close this one.
