### ISSUE TITLE
Missing MAPR boundary

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#179]
A new park. May be a tough one.

**Comment by chadlawlis** [comment]
From talk-us-nps OSM mailing list:

> the new site will cover three locations: Hanford, Washington; Oak Ridge,
> Tennessee; and Los Alamos, New Mexico.

Park is to be announced today, still no boundary from IRMA.

**Comment by chadlawlis** [comment]
Share this with Clifford Snow clifford@snowandsnow.us when available.

**Comment by chadlawlis** [comment]
From Roger @ Lands, this is set for inclusion in next Lands release:

> There is a Federal Register notice coming out this month.  I'll include the MAPR boundary in the next IRMA update after this announcement.

**Comment by chadlawlis** [comment]
Unfortunately this was not actually included in the latest Lands release [20160107](https://irma.nps.gov/App/Reference/DownloadDigitalFile?code=533885&file=nps_boundary.zip). 

I reached out to Roger @ Lands again today to see if he has anything he could pass along.

**Comment by chadlawlis** [comment]
``` sql
insert into parks (unit_id, unit_name_short, unit_name_long, unit_desig_abbr, unit_desig_full, unit_code, unit_state, unit_url) values ((select max(unit_id) + 1 from parks), 'Manhattan Project', 'Manhattan Project', 'NHP', 'National Historical Park', 'mapr', 'nm,wa,tn', 'http://www.nps.gov/mapr/index.htm');
insert into parks_poly (unit_id, unit_code) values ((select unit_id from parks where unit_code = 'mapr'), 'mapr');
insert into parks_line (unit_id, unit_code) values ((select unit_id from parks where unit_code = 'mapr'), 'mapr');
```

**Comment by cwlawlis802** [comment]
From Daniel, webmaster @ MAPR, 2/11/16:

> I am the webmaster for all seven websites for the Manhattan Sites Unit.
> You have consent to use the Park Tile 3 map for the following sites:
> CACL
> FEHA
> AFBG
> THRB
> GEGR
> HAGR
> SAPA

So, I will combine these units to create a master boundary for MAPR.

**Comment by cwlawlis802** [comment]
Done via:


```sql
-- set geom_poly from custom imported table mapr
UPDATE parks_poly
SET geom_poly = (SELECT ST_Union(wkb_geometry) FROM mapr)
WHERE unit_code = 'mapr';

-- update unit_area from geometry, data_source to mapr
UPDATE parks
SET unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_code = 'mapr'),
data_source = 'mapr'
WHERE unit_code = 'mapr';
```

**Comment by cwlawlis802** [comment]
*Note*: 5 of the 7 units that were merged to create this boundary pull from Lands (CACL, FEHA, THRB, HAGR, SAPA) while AFBG and GEGR  pull from a custom `npnh` source. I am setting the source for the standalone MAPR unit to `mapr` in `parks`.

@jakecoolidge the source for AFBG appears to align better with imagery:
![afbg](https://cloud.githubusercontent.com/assets/1238636/12990534/20c72eaa-d0c8-11e5-849f-ead1fe924c4c.jpg)
while the GEGR source appears to be expanded a little bit beyond what Lands provides:
![gegr](https://cloud.githubusercontent.com/assets/1238636/12990570/50e229d2-d0c8-11e5-884b-8b8b221cba4e.jpg)

Do these look right for these units? Closing, but chime in if you can confirm that these are good or require a transition to Lands.

**Comment by chadlawlis** [comment]
An official boundary is now available with the latest Lands release 20160331. Updating to this will be handled via #697.

**Comment by cwlawlis802** [comment]
Okay, scratch this https://github.com/nationalparkservice/places-data/issues/179#issuecomment-183051602. Daniel is the Webmaster at MASI - Manhattan Sites - not MAPR, Manhattan Project National Historical Park. I will move this custom aggregate boundary over to MASI, once the record is created via #701, then set the MAPR boundary to the latest release from Lands per #697.

**Comment by chadlawlis** [comment]
The tiles were regenerated since #697 was completed but I can't seem to find the MAPR boundary in PT3. Some of the site areas in TN should be showing up around here, starting at Z14: http://insidemaps.nps.gov/park-tiles-3/#16/35.9843/-84.2572.

Reopening this - Jim to run boundaries this afternoon, so I'll check back in after that.

**Comment by chadlawlis** [comment]
These are now live.
