### ISSUE TITLE
Remove RRBH from dataset

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#181]
Apparently Ronald Reagan Boyhood National Historic Site is a **proposed** National Historic Site, but is not yet officially part of the National Park Service. It does not have an official NPS website, and it has been in the "pending" status since 2002.

The Office of Communications has asked that we take it out of our maps for now.

**Comment by chadlawlis** [comment]
Is there a logical way to do this in the script @jimmyrocks? Otherwise I can remove it from CartoDB, but I'm assuming there is a preferable way to preserve the information should this transition to "official" down the road.

**Comment by jimmyrocks** [comment]
It looks like the polygon is also in IRMA, so deleting it won't get rid of
it, it'll just get rid of the WSD Parks version out in cartodb.
The IRMA/CartoDB merging script needs to get updated to remove it, so I can
do that. I'll let you know when it's done, and we can rerun the boundaries
tonight.

**Comment by jimmyrocks** [comment]
This is updated in code, the park still needs to be removed from CartoDB. The scripts will need to be run from the beginning again since this park exists in both IRMA and CartoDB, and the new scripts will remove it.

**Comment by chadlawlis** [comment]
This appears to be all set - `unit_code = 'rrbh'` returns no records in either CartoDB parks or places_boundaries parks.
