### ISSUE TITLE
expose "access" tag in nps.nps-places-data

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#183]

**Comment by jimmyrocks** [comment]
The access tags should be the same that are in [OSM](http://wiki.openstreetmap.org/wiki/Key:access).

Is there any aggregation you would like me to do, (everyone = no other than access=yes) or would you like me to expose all the tags as they come in?

**Comment by jakecoolidge** [comment]
I say we try raw data for the immediate roll-out and see how it goes.

**Comment by jimmyrocks** [comment]
👍

**Comment by chadlawlis** [comment]
So, the consensus is to only support `{"access":"yes"}` and `{"access":"no"}`, correct? Not `{"access":"private"}`, `{"access":"permissive"}`, etc?

**Comment by jimmyrocks** [comment]
I was going to just conflate access=yes to "yes" and all other access=\* to "no", but we can expose the raw tags, and a similar thing can be done in the CSS

**Comment by chadlawlis** [comment]
Okay. If our plan is only to support "yes" else "no" values, we might as well conflate. Unless there is a benefit to the user to see the raw tag?

**Comment by jakecoolidge** [comment]
I just added "private" tags to Places...so, I should change them to "no"?

**Comment by chadlawlis** [comment]
Well, that gets to my question... What would we like to support? In practice, it seems like we'll really only be using "yes" and "no". But if there is a logical use case for "private", "permissive", etc then we need to sort that out.

@jakecoolidge, is there a specific reason you used "private" vs. "no"?

**Comment by jimmyrocks** [comment]
I don't think we need to limit the values to just yes or no for any reason
other than making it easier for the users. There may be a use for more
specific tags in the future, although I can't think of any. Either way, we
should be about to say if access = anything, then access = no unless
access=yes, then access remains = yes

**Comment by chadlawlis** [comment]
I guess I'm just thinking in terms of the tracing guide and how we want provide guidance on this. We have an open issue here https://github.com/nationalparkservice/places-data/issues/82 which we need to address. I'm fine with supporting all the values, but moral of the story in terms of guidance is that anything other than "yes" will be aggregated into "no" for our use, for now (and therefore rendered differently in Park Tiles, as a feature not accessible to the public).

Does that make sense/sound good?

**Comment by jakecoolidge** [comment]
@cwlawlis802, I couldn't remember what we had agreed upon. "Private" is a bit more specific. I was aware of the osm wiki regarding access, and @jimmyrocks and i were looking at it again this morning. There, they recommend more specificity, so that guided my decision. I only applied the tag to three test features in Places, so changing them isn't a big deal.

**Comment by jimmyrocks** [comment]
I think it's good enough for the guide to say just "yes" or "no" and to make a note that access=anything else will show up as no access. If the other tags make more sense to cartography, then there's no reason they can't use them to create a more accurate map. But as far as suggesting things to users, I think yes and no are good enough. Really, there isn't much of reason to suggest using access=yes, since that is the default, but it can't hurt to add it either.

**Comment by chadlawlis** [comment]
Sounds good to me. For guidance, we'll stick to "yes" (the default, not requiring user input) or "no" (including all other values than "yes"). We'll maintain the raw tags for possible use cases down the road.

So, @jakecoolidge, if "private" makes the most sense in your situation let's keep it. But, for now, that will be lumped into "no" in Park Tiles (not publicly accessible) until a specific use case emerges.

**Comment by jakecoolidge** [comment]
Sounds good to me. I'll let @jimmyrocks close this up when the changes have been applied.

**Comment by jimmyrocks** [comment]
These are now available in the points, lines, and polygons layers
