### ISSUE TITLE
GRPO data

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#185]
Trails for GRPO (in MWR).

> I am attaching a zip file with trails layers for APIS, GRPO, and ISRO.
> These are not going to change, at least spatially. I think they are in pretty good shape.
> I am still working on the other parks in the network, all apparently in some state of revision.
> Will send the best we have for those soon, by the end of the month anyway.
> I am also attaching a word doc with some updated notes.

Data (`.gdb`) and word document `GLKN_ParkTrails.docx` [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbRDdKeHlmZC05cWM)

**Comment by jakecoolidge** [comment]
completed. will send notification when all parks in this submission are seeded.
