### ISSUE TITLE
ISRO data

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#186]
Trails for IRSO (in MWR).

> I am attaching a zip file with trails layers for APIS, GRPO, and ISRO.
> These are not going to change, at least spatially. I think they are in pretty good shape.
> I am still working on the other parks in the network, all apparently in some state of revision.
> Will send the best we have for those soon, by the end of the month anyway.
> I am also attaching a word doc with some updated notes.

Data and word document `GLKN_ParkTrails.docx` [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbdDNIMWc0SDJWdjQ)

**Comment by jakecoolidge** [comment]
Completed. @cwlawlis802, can you provide me with the contact info for the submitter? (Will close once submitter has been notified.)

**Comment by jakecoolidge** [comment]
submitter contacted
