### ISSUE TITLE
Error in SAIR boundary 

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#2]
https://github.com/nationalparkservice/park-tiles/issues/135

**Comment by jimmyrocks** [comment]
I can't figure out how to extract the boundary from here:
http://www.nps.gov/maps/full.html?mapId=233db5bb-3651-4ef7-8d34-42be468fc453#17/42.46810/-71.00740
http://insidemapservices.nps.gov/arcgis/rest/services/NPSUnits/MapServer

**Comment by jimmyrocks** [comment]
Updated, looks like it was an error in WSD_Parks

**Comment by chadlawlis** [comment]
Looks like an issue with the SAIR boundary has re-emerged. When I pull the boundary down from the `places_boundaries_v2` database it shows up correctly locally, and identical to the current boundary from Lands:

![sair](https://cloud.githubusercontent.com/assets/1238636/16501346/432124e4-3ec6-11e6-9080-aac56ab90c05.png)

However, it shows up as follows in Park Tiles (https://www.nps.gov/npmap/tools/park-tiles/view/#18/42.46834/-71.00736):

![sair_pt](https://cloud.githubusercontent.com/assets/1238636/16501381/6344550c-3ec6-11e6-8d8d-41a44c946c61.png)

And the boundary looks the same as Park Tiles in the [Mapbox source](http://10.147.153.191:3000/source?id=tmsource:///home/npmap/places-data/boundaries/database/nps-places-boundaries-v2.tm2source#), so there has definitely been an error here.

I am going to update the geometry in our database to pull from Lands, given they are identical geometries (`data_source` currently set to `npmap`) and hope this resolves after regenerating the boundaries.

This may fix this issue https://github.com/nationalparkservice/places-data/issues/646 as well.

**Comment by chadlawlis** [comment]
Done via:

``` sql
BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM lands_20160331 WHERE unit_code = 'sair'),
    data_source = 'Land Resources Division'
WHERE
    unit_id = 352;
UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 352)
WHERE
    unit_id = 352;
UPDATE 
    parks_point
SET
    geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_id = 352)
WHERE
    unit_id = 352;
COMMIT;
```

Will confirm once boundaries are regenerated.

**Comment by chadlawlis** [comment]
This is now live.

I am assuming #646 will fix once this boundary has been synced to CartoDB.
