### ISSUE TITLE
Add preset "Fire Hydrant"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#205]
Tag `{"emergency":"fire_hyrant"}` from http://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant.

I recently uploaded a number to GEWA https://github.com/nationalparkservice/places-data/issues/149.

**Comment by chadlawlis** [comment]
Added "Fire Hydrant" as `{"emergency":"fire_hyrant"}`. Service > Support > Fire Hydrant.

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
This is now live.
