### ISSUE TITLE
CEBE data

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#206]
From Dan @ SHEN.

Data [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbT191cVdxYUNFVUE).

Includes buildings, trails, and some points of interest. 

Also includes a park boundary, which I will create a new issue for.

**Comment by chadlawlis** [comment]
Boundary issue here https://github.com/nationalparkservice/places-data/issues/207

**Comment by jakecoolidge** [comment]
completed.
