### ISSUE TITLE
Add preset "Park"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#208]
Tag `{"leisure":"park"}` from  http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpark.

I am uploading a number to MISS https://github.com/nationalparkservice/places-data/issues/153.

**Comment by jimmyrocks** [comment]
This was proposed previously, and we were afraid that it would be
confusing. I'm ok using it, but can we come up with a better name for it?

**Comment by chadlawlis** [comment]
Good memory, I remember this coming up before as well. I can think about what else to call it.

**Comment by chadlawlis** [comment]
After further discussion, we are going with "Park" after all.

Added as `{"leisure":"park"}`. Land Recreation > Park > Park.

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
This is now live.
