### ISSUE TITLE
FLFO data from IMR

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#216]
From Darcee, 10/26.

> Please replace all the data you currently have in Places with this data.

Points of interest, roads, trails, and parking. Buildings available later via FMSS. Data [here](https://drive.google.com/drive/u/1/folders/0B6O6-Wj7RWnYd2J6WHRVdTdkZm8).

**Comment by jakecoolidge** [comment]
Seeding will be handled by sync tool.
