### ISSUE TITLE
Accuracy problem with BAND boundary

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#22]
"I was working on BAND and noticed that Park Tiles boundary is a little off (~260 meters) from the lands data, that is, a bit south of where it should be."

**Comment by jimmyrocks** [comment]
Looks like BAND is came from WSD_Parks, I'll verify that the IRMA dataset is better and make the switch.

**Comment by jimmyrocks** [comment]
IRMA's boundary looks a lot better, I'll make the switch:
http://bl.ocks.org/d/b5c05ba8326dfd3649d0 (IRMA)
http://bl.ocks.org/d/e84a80bcd5f7f364b618 (What we had from WSD_Parks)

**Comment by nateirwin** [comment]
Fixed.

**Comment by heidiogle** [comment]
Looks great guys, thanks!
