### ISSUE TITLE
FRLA Boundary Update

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#228]
Frederick Law Olmstead NHS needs a boundary refresh. Our current boundary is just a square floating across the street from the actual site. Currently in Places, the VC POI is correctly placed. We need a better boundary.
![frla](https://cloud.githubusercontent.com/assets/4741443/10805163/622b025c-7d91-11e5-8f99-f9a0d10bf583.png)
I'll email the contact who brought this to our attention to see if he has a better parcel boundary for this site.

**Comment by chadlawlis** [comment]
We have an issue open for this here: https://github.com/nationalparkservice/places-data/issues/197.

**Comment by mtaylorlong** [comment]
Ah. Sorry 'bout that.
