### ISSUE TITLE
Alcatraz Island should get labeled sooner

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#23]
![park_tiles___national_park_service](https://cloud.githubusercontent.com/assets/10443/6701907/ab84a728-cce8-11e4-9056-338c7b5dffea.jpg)

**Comment by jimmyrocks** [comment]
The zoom level is currently set to 14

This was originally set to Zoom level 11:
https://github.com/nationalparkservice/mapbox-studio-projects/commit/c645c2bd6b0ddb39e08f2ab100cddcfe5b7e3986

But we moved it to Zoom level 14:
https://github.com/nationalparkservice/mapbox-studio-projects/commit/397e85846b77de5b6d22443ed1a220c8a50de970

To Close this issue:
https://github.com/nationalparkservice/places-data/issues/17

In Reference to @makella's comment here:
https://github.com/nationalparkservice/park-tiles/issues/99

**Comment by mtaylorlong** [comment]
I've got in and checked these settings. They should be all set now. Alcatraz should show up starting at z11.
