### ISSUE TITLE
JOFI Label is Outside of Boundary

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#230]
John F Kennedy NHS shows it's label outside of its actual boundary. This may be so the label doesn't fill the entire boundary, but it still looks a little funny. Worth revisiting after the new boundaries are in place.

![jofi](https://cloud.githubusercontent.com/assets/4741443/10805342/85593018-7d92-11e5-81d2-9441fb9b0f6c.png)

**Comment by mtaylorlong** [comment]
Still haven't resolved this one yet. Last time I looked, the issue was that I wasn't sure whether the polygon or the point was more correct.

@cwlawlis802: Can I add this to you list of things to check up on? If the boundary is correct, then we just need to move the point so that it falls within the boundary. Let me know if/when you've made the final call and I'll take a look at the min_zoom settings as well to see if there's any possible room for improvement.

**Comment by chadlawlis** [comment]
Yup, the boundary appears correct: http://www.nps.gov/hfc/carto/PDF/JOFImap1.pdf.

The `geom_point` has been updated from JOFI's `geom_poly`:

``` sql
update parks set geom_point = (select ST_Centroid(geom_poly) from parks_poly where unit_code = 'jofi') where unit_code = 'jofi'
```

So, this should be all set - the label should appear directly over the boundary now.

**Comment by mtaylorlong** [comment]
Great! I'm closing this one out.
