### ISSUE TITLE
Add runways to nps_places_polygons

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#231]
I need to render areas tagged 'aeroway':'runway' in our NPNH basemap.

**Comment by mtaylorlong** [comment]
@jakecoolidge: Has this issue been resolved?

**Comment by jakecoolidge** [comment]
It doesn't appear to have been resolved. I'm rendering it in the NPNH basemap with a custom data source, so I haven't been pushing on it. And now that I think of it, since it's not supported as a Places preset, I don't see this happening for a while. I'd be okay with closing this for the time being.

**Comment by nateirwin** [comment]
Are you all ok with keeping this one open? I'd really like to add this as a preset. There are more airports in parks than you might think!

**Comment by jakecoolidge** [comment]
Maybe the issue should be, "create a preset for runway polygons"? And we'll add it once we lift the freeze on new presets.

**Comment by jakecoolidge** [comment]
Oops. You basically said that already, @nateirwin.
