### ISSUE TITLE
YELL data seed for Places

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#235]
The YELL GIS office provided all the places-relevant shapefiles they had to @mtaylorlong on the Places Mobile kick-off visit. [The data is on our shared drive](https://drive.google.com/a/doi.gov/folderview?id=0BwlLCv2MkbqkMDJVS0k2bXdUcGs&usp=sharing).

**Comment by mtaylorlong** [comment]
All initial data was seeded on 11/27/2015.

**Comment by chadlawlis** [comment]
Adding note here to remember to track this in our Places seeding spreadsheets.

**Comment by mtaylorlong** [comment]
I got it in Data Seed Tracking. I think I still need to add it to some other spreadsheed. Maybe the data sources one?

**Comment by chadlawlis** [comment]
[Places Data Sources](https://docs.google.com/spreadsheets/d/1dXwwszQbF1hBOJZ2BCH37LAGY-VgpO8vOBN2XzQc6EQ/edit#gid=0) and [Tracking Places Data Call Responses](https://docs.google.com/spreadsheets/d/1kgpmfuQg8mgEtcqd7MBGuO5fJoeQmUbFuqvuD7XzxSE/edit#gid=0).

Looks like you'll just need to update the dates for the latter. Thanks!
