### ISSUE TITLE
Add "oneway" attribute to rendered Places data for Roads and Trails

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#238]
@nateirwin brought up a good point that we should add special line symbology for oneway roads in Park Tiles. To do this, we'll need to turn the "oneway" tag into an available attribute in our tiles. Where roads are tagged in Places Editor as oneway=yes, we can mark "yes" in the oneway field; otherwise, all other roads and trails would be marked "no".

@jimmyrocks: If you can sort out the data end, I'll make sure I can symbolize it in Park Tiles.

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/mapbox-studio-projects/commit/eb0590185d1d7286a6ecbf60d64ac178611b01e4

**Comment by mtaylorlong** [comment]
Thanks!

**Comment by mtaylorlong** [comment]
@jimmyrocks: I'm still not seeing the one_way field in the nps_places_road_and_trails vector tiles. Here's an example:

One-way road in Shenandoah: http://10.147.153.193/api/0.6/way/50631/full.html

Here's what it looks like in MB Studio:
![screen shot 2015-11-12 at 7 49 08 am](https://cloud.githubusercontent.com/assets/4741443/11121343/853444ca-8912-11e5-971d-6187e00c73be.png)

As you can see, there's no one_way field in the data. Any idea why?

**Comment by jimmyrocks** [comment]
Sorry, it was a typo on my end… https://github.com/nationalparkservice/mapbox-studio-projects/commit/1e196c7f05c66834e126bb56aba5afd802274c6f
