### ISSUE TITLE
Boundaries table - Separate poly & line geometries, rename to "Parks"

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#239]
In our call today, we decided to simplify the boundaries table by separating the geometries for polygons and lines into their own tables. By simplifying the main table, we should be able to access it and edit it easier (currently, opening this table tends to crash PGAdmin). For each of these separate tables, we will include fields for unit_code and unit_id (unit_id will be the primary key used to join to the main table).

**Boundaries > Parks:**
Since the main boundaries table won't actually store boundary geometries anymore, we'll re-name it to "Parks". Here's how I see the tables being named:
- **Parks** - (includes all attributes and point geometries)
- **Parks_Poly** - (includes unit_id, unit_code, and geom_poly)
- **Parks_Line** - (includes unit_id, unit_code, and geom_line)

@jimmyrocks: Let me know when this is complete so I can test out editing the main table. Hopefully, this makes it easier for me to access and edit the table.

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-data/commit/db52162aaff8e9f7fd24ccd1bc60389419921f8d
