### ISSUE TITLE
Trail Name inaccurate in CARE

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#24]
Hi guys, the trail just south of the Fremont River should be called Fremont River Trail, not Freemont.  Thanks!

**Comment by nateirwin** [comment]
Humm, this looks ok to me?

![park_tiles___national_park_service](https://cloud.githubusercontent.com/assets/10443/6807297/3fd4262c-d213-11e4-9f06-404defdae7ef.jpg)

**Comment by heidiogle** [comment]
The trail name Fremont should only have one "e."

Heidi Ogle
GIS Specialist
Colorado State University Research Associate
National Park Service, Intermountain Region
Geographic Resources Division
12795 W. Alameda Pkwy.
Lakewood, CO 80228
303-987-6707 (office)
530-412-3308 (mobile)

**Comment by makella** [comment]
@heidiogle 
Thanks so much for pointing this out!
I've corrected the spelling in our source data.  You should see the updates take place here in the next 10-15 mins. Feel free to re-check and if you still see the issue, please re-open this.

**Comment by makella** [comment]
@heidiogle I just checked, things seem to be in order now:

http://www.nps.gov/npmap/tools/park-tiles/#16/38.2782/-111.2474

**Comment by heidiogle** [comment]
Looks great!  Thanks Mamata!

Heidi Ogle
GIS Specialist
Colorado State University Research Associate
National Park Service, Intermountain Region
Geographic Resources Division
12795 W. Alameda Pkwy.
Lakewood, CO 80228
303-987-6707 (office)
530-412-3308 (mobile)

**Comment by makella** [comment]
No problem! That's what we like to hear :)
