### ISSUE TITLE
Add/Update Boundaries for GOGA Parks

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#240]
This could be nothing (y'all know the history of these boundaries better than me), but it seems to me that there is supposed to be a boundary for Marin Headlands (part of GOGA) that isn't there. I see a bunch of Places data and a VC, but no boundary in Park Tiles. Perhaps this boundary was lost in an update?

![screen shot 2015-11-05 at 9 59 36 am](https://cloud.githubusercontent.com/assets/4741443/10975402/fc8cdd30-83a3-11e5-85b9-8cf2303daeff.png)

@jimmyrocks, @cwlawlis802: If this get's updated in our current boundaries table, let's make sure it gets into the new table as well.

**Comment by mtaylorlong** [comment]
@jimmyrocks just pointed me to an email chain in which GOGA sent us some new geometries for their parks. It sounds like we just haven't gotten around to updating these.

I'll look at these shapefiles and see if I can make sense of it. GOGA may be a perfect test case for how we can deal with subunits in our boundaries table and in Park Tiles.

**Comment by cwlawlis802** [comment]
@mtaylorlong can you forward that email to me? I updated the Fort Point boundary recently but have not come across any new geometries for other GOGA subunits. This would be good for me to discuss with the park as well.

**Comment by jimmyrocks** [comment]
Since there is no boundary at all for GOGA, I will put a temporary one in for the meantime

**Comment by chadlawlis** [comment]
I am in touch with the GIS Specialist @ GOGA about this and will confirm changes here.

**Comment by jimmyrocks** [comment]
Glad to see this is getting worked out!

**Comment by chadlawlis** [comment]
Plenty to address here...

Muir Woods, as currently rendered in Park Tiles:

![park tiles 3 insidemaps 2015-12-03 16-18-58](https://cloud.githubusercontent.com/assets/1238636/11577937/88f35416-99de-11e5-819c-e93be0cdc86d.jpg)

Quick overlay, custom GOGA boundary overlaying current boundaries in Places:

![qgis 2 10 1-pisa 2015-12-03 16-53-24](https://cloud.githubusercontent.com/assets/1238636/11577953/9a42ddb8-99de-11e5-8471-6876a538525b.jpg)

There are a number of units not included in GOGA's boundary, including JOMU (among many others). More investigation to follow, including discussion with the park.

**Comment by chadlawlis** [comment]
### Geometry issues

I have moved the MUWO to another issue, here https://github.com/nationalparkservice/places-data/issues/299. I will replace the MUWO `WSD_Parks` geometry with the latest from Lands.

Judging by our current data, GOGA includes the following subunits:
- PRSF (source: `WSD_Parks`)
- FOPO (source: `FOPO`)
- SAFR (source: `WSD_Parks`)
- MUWO (source: `Land Resources Division`)
- ALCA (no geometry)

However, the PRSF geometry is not rendered in Park Tiles - it only includes the larger GOGA boundary here. PRSF and FOPO are also not aligned:

![qgis 2 10 1-pisa 2015-12-07 12-57-17](https://cloud.githubusercontent.com/assets/1238636/11638078/20d9a7b6-9ce2-11e5-80b4-d215072890ec.jpg)

![park tiles 3 insidemaps 2015-12-07 12-52-35](https://cloud.githubusercontent.com/assets/1238636/11638004/d0ec5762-9ce1-11e5-8d57-672f32ade044.jpg)

The SAFR geometry does not align with the larger GOGA boundary... 

![qgis 2 10 1-pisa 2015-12-07 12-59-19](https://cloud.githubusercontent.com/assets/1238636/11638158/9892a58c-9ce2-11e5-9136-2e97696e1401.jpg)

...but it is technically rendered in Park Tiles, though in a different style than usual:

![park tiles 3 insidemaps 2015-12-07 13-01-27](https://cloud.githubusercontent.com/assets/1238636/11638195/c3fc830a-9ce2-11e5-9ec1-3fc3eea14ba4.jpg)

Finally, ALCA is included in the GOGA boundary, but does not have its own unit geometry. We could pull this out of the larger GOGA, if necessary.

So, to-do:
- [x] Resolve PRSF geometry with both larger GOGA and nearby FOPO
- [x] Resolve SAFR geometry
- [x] Create standalone ALCA geometry https://github.com/nationalparkservice/places-data/issues/378

**Comment by chadlawlis** [comment]
### Labeling issues

In terms of true GOGA subunits, PRSF and ALCA are missing labels in Park Tiles at all zoom levels. Original ALCA issue here https://github.com/nationalparkservice/places-data/issues/17.

In terms of not true GOGA subunits, the Marin Headlands could use a label, though there is no geometry for this (as it is not an NPS unit). Angel Island, the island due north of ALCA, could also use a label:

![park tiles 3 insidemaps 2015-12-07 13-09-15](https://cloud.githubusercontent.com/assets/1238636/11638331/c2bc4af6-9ce3-11e5-887a-fb4959228ed7.jpg)

This is technically a state park, though it is included in GOGA's "offshore and managed" boundary.

I am waiting to hear back from the GOGA GIS Specialist, who should have some insight/preference as how to handle Marin Headlands and Angel Island.

So, to-do:
- [x] Add ALCA label https://github.com/nationalparkservice/places-data/issues/378
- [x] Add PRSF label
- [x] Add Marin Headlands label
- ~~[ ] Add Angel Island label~~

**Comment by mtaylorlong** [comment]
Most of these issues have been resolved with our new boundaries update, but I'm pushing this to the next release just to make sure we cross everything off the list.

**Comment by chadlawlis** [comment]
See #559 for Marin Headlands label.

**Comment by chadlawlis** [comment]
See #560 for full list of remaining localities to add.

**Comment by chadlawlis** [comment]
Alrighty, so we are all set here. Below is an overview image of changes:

![goga_overview](https://cloud.githubusercontent.com/assets/1238636/13163950/9312cd88-d66e-11e5-9f48-2cef9fc5a142.png)

The new boundary lines up very nicely with what is shown on the HFC maps http://www.nps.gov/hfc/cfm/carto-detail.cfm?Alpha=GOGA, which is convenient and should make the transition natural.

As you can see, a large area to the north was removed from GOGA affiliation and will be added to the PORE boundary, because it is managed by PORE. A large area around MUWO was removed, because this is a state park. The land area of Angel Island was removed, because this is a state park. The offshore boundary around it remains, as this is suitable to show as part of GOGA. A large area to the south was added - this is San Francisco Public Utilities Commission (SFPUC) watershed land / NPS easement managed by the park, so it is fitting to include. And a large area to the south was removed, because this is an NPS easement that should not be rendered as part of the official GOGA boundary.

PRSF was also added as its own unit (with its own geometry), while ALCA was separated out as its own unit (with its own geometry). The MUWO boundary is identical to Lands, so no change there. FOPO is only slightly different, but it fits in seamlessly with the surrounding GOGA offshore boundary and the new PRSF boundary so this is improved. Finally, the SAFR boundary is new - coming directly from the park itself.

We should be all set here - once the localities are added in GOGA will be looking highly detailed on PT3 :+1:

**Comment by chadlawlis** [comment]
Okay, this has been updated once more - this time to re-introduce the PORE managed, GOGA legislative area to the north. This is what the "final" boundary looks like, after working with the park last week during the mobile visit:

![goga_final](https://cloud.githubusercontent.com/assets/1238636/15082515/57669b44-1385-11e6-801f-6682fea457fd.png)
_blue fill represents the GOGA boundary_

The `unit_area` and `geom_point` have been updated in the database to reflect the change as well. See #561 for more context on the PORE managed, GOGA legislative area.

Data available [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbMW9HeFJnN280V2M).

**Comment by chadlawlis** [comment]
Reopening - will close once confirm this is live and accurate in Park Tiles.

**Comment by chadlawlis** [comment]
GOGA's min_zoom_poly has also been bumped up to Z9 (previously Z10).

**Comment by chadlawlis** [comment]
The new area is rendering but still at Z10 not 9. Re-running boundaries and will confirm/close once live.

**Comment by chadlawlis** [comment]
GOGA is now live at Z9. Closing.
