### ISSUE TITLE
Render Superclass "Locality" as Points

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#241]
I just discovered in our NPS_Preset_Classes spreadsheet that we have presets for Locality. (Cultural Landscape, Historic District, Junction, Locale, Populated Place). I'm interested in encouraging parks to adopt these presets because we could use these features to replace our current OSM locality labels inside parks. The OSM labels bug me because they displace labels in important areas and I'd like to move them around for cartographic purposes that would be inappropriate for OSM.

I was thinking about these and trying to decide how we should encourage folks to use them. Using these presets for points seems the simplest for the sake of Park Tiles. I'd love to support tagging polygons this way, but labeling inside polygons is still a bit fishy in vector tiles (GL may solve this though). 

So, @jimmyrocks: I wanted to make sure that localities are currently being rendered into our places tiles. If they are, I'm going to experiment with using them in YELL.

**Comment by jimmyrocks** [comment]
I most recently refreshed all the tiles in CartoDB and MapBox with the latest preset classes on Tuesday of this week.

https://github.com/nationalparkservice/places-data/issues/237

**Comment by mtaylorlong** [comment]
Cool. So anything with this preset should already be in the tiles, right?

**Comment by jimmyrocks** [comment]
yes

**Comment by mtaylorlong** [comment]
Does this preset work on all geometry types?

**Comment by jimmyrocks** [comment]
I believe that localities are only points

**Comment by mtaylorlong** [comment]
Gotcha. Good to know. Thanks!
