### ISSUE TITLE
Add preset for carriage roads

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#242]
Admittedly, these are only found in Acadia. Per Acadia's GIS Specialist:

> Is there any way to make the carriage roads (currently classed as horseback riding trails (though they are multi-use/no motorized use)) have a different symbol than the hiking trails (pedestrian only)? They are extremely different types of recreational resources and experiences and it will confuse visitors to see them classed the same on a map.

Even if we can't begin symbolizing carriage roads differently in Park Tiles in the near term, this seems like an important category of recreational pathway that we will want to capture in Places moving forward.

My first idea is to add a new preset within the Trail superclass and the Non-Motorized class with the Name/Type "Carriage Road". The underlying tags are less clear to me. We could maintain&mdash;
"highway":"path"
"foot":"yes"
"bicycle":"yes"
"horse":"yes"
and perhaps add&mdash;
"sport":"equestrian"

_or_ we could adopt
"highway":"bridleway"
as the definition for this highway type [on the OSM wiki](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dbridleway) seems well-aligned to these carriage roads. Thoughts?

**Comment by jakecoolidge** [comment]
Further clarification from the ACAD GIS Specialist:

> In terms of numbers, the primary use of the carriage roads are bicyclists, then pedestrians (walkers, runners, snowshoe/XC skiing), and really only a few horse/carriage users, comparatively.  I think I put them in as horse trails to try to separate them from the hiking trails.  The new bike paths near the Schoodic Woods campground are similar in terms of design, but do NOT allow horses;  however, so far we have been depicting them, on in house maps, with the same symbol as the MDI carriage roads, because that is how they "feel" to visitors.
> 
> And, actually, MABI has a couple carriage roads also.

**Comment by chadlawlis** [comment]
I'm okay with adding this as a preset with underlying tag `{"highway":"bridleway"}` while maintaining the ability to edit the approved uses i.e. foot, bicycle, horse - as it's done in OSM:

![openstreetmap 2015-11-09 10-54-31](https://cloud.githubusercontent.com/assets/1238636/11041656/5bd4cc42-86d0-11e5-9c5c-010ddaf19f17.jpg)

**Comment by jimmyrocks** [comment]
+1 for Bridleway

**Comment by jakecoolidge** [comment]
+1 here as well!

**Comment by chadlawlis** [comment]
Cool, I can add it to the spreadsheet.

@jakecoolidge want it added as "Carriage Road" or "Bridleway"?

**Comment by chadlawlis** [comment]
Added as line as "Carriage Road" `{"highway":"bridleway"}`.

Will regenerate presets and confirm when live.

**Comment by chadlawlis** [comment]
@jimmyrocks to regenerate presets due to limitations with current update script.

**Comment by chadlawlis** [comment]
@jimmyrocks would you mind regenerating the presets this week for this to go live?

**Comment by chadlawlis** [comment]
Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by jimmyrocks** [comment]
"Carriage Road" `{"highway":"bridleway"}`. Doesn't appear to exist in the NPS_Preset_Classes list, is this an error, or was it removed for a reason?

**Comment by chadlawlis** [comment]
This is now live.
