### ISSUE TITLE
Bad label: "Klondike Gold Rush - Seattle Unit National Historical Park"

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#244]
Should be "Klondike Gold Rush National Historical Park - Seattle Unit"

**Comment by mtaylorlong** [comment]
I'll need to double check the parks table to fix how we're handling this. The label also isn't showing up at zoom levels where there's plenty of space, so I'll need to do some min_zoom tweaking.

**Comment by mtaylorlong** [comment]
Fixed this. It should read correctly on the next boundaries update.
