### ISSUE TITLE
Trails not rendering to CartoDB tables

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#248]
We have some trails tagged "highway":"path" in Saint-Gaudens NHS that were created in Places Editor in October and do not appear in nps.trails or nps.places_lines. This came up when park staff attempted to download the trails from insidemaps, but the number of trails geometries listed is currently zero.

**Comment by jimmyrocks** [comment]
These specific trails were causing problems when being imported to CartoDB. I will re-render them and see if it produces the same error.

**Comment by jimmyrocks** [comment]
These appear to be fixed: http://www.nps.gov/maps/full.html?mapId=daafb8e5-280a-4914-b3f5-7d160a453f9a&url=aHR0cHM6Ly9ucHMuY2FydG9kYi5jb20vYXBpL3YyL3NxbD9xPVNFTEVDVCUyMColMjBGUk9NJTIwcGxhY2VzX2xpbmVzJTIwV0hFUkUlMjB1cGRhdGVkX2F0JTIwPj0lMjAnMjAxNS0xMS0xMSAxODo0ODoyNyclMjBBTkQlMjB1cGRhdGVkX2F0JTIwPD0lMjAnMjAxNS0xMS0xMSAxODo0OTozOCc7JmFwaV9rZXk9NWU5ZjY1MTIxYWFjZDE4ZDkyYThmNzliZTY1ZjQwNGU3YWJhOGNmNiZmb3JtYXQ9Z2VvanNvbg==
