### ISSUE TITLE
GLCA roads to (and from) nowhere

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#25]
![capture](https://cloud.githubusercontent.com/assets/11545684/6721114/468eda9e-cd8f-11e4-929a-9a4c830c2fe9.JPG)
There are four roads to and from nowhere in GLCA, pictured above.  Below will show you where they are at in the park.
![capture1](https://cloud.githubusercontent.com/assets/11545684/6721160/aeb887dc-cd8f-11e4-9334-9041ccd48bb7.JPG)

**Comment by nateirwin** [comment]
That's interesting. The roads look fine on OpenStreetMap, but they are rendering disconnected in Park Tiles. I'm going to loop @makella in on this one. She may have an idea as two what's going on.

A few links to help:

http://www.nps.gov/npmap/tools/park-tiles/#18/37.08892/-111.40748
http://www.openstreetmap.org/edit#map=18/37.08892/-111.40748

**Comment by jimmyrocks** [comment]
They don't render in the locator overlay either, and the problem looks to
be at a layer boundary. It looks like something MapBox is doing.

**Comment by makella** [comment]
I'll look into it a little more.  You can see that it is happening in their Streets dataset as well so at least that helps narrow it down:
https://www.mapbox.com/editor/?id=nps.li242o03#saved

**Comment by makella** [comment]
I have a support ticket with Mapbox about this.  I think it might be similar to what happened in GRSM with Tom but waiting to hear back.

**Comment by makella** [comment]
I haven't forgot about this! I'm still working with support... it looks like something is happening on the data update side of things.  I'll report back when I know more! 

@heidiogle thanks so much for pointing this out... we can't have our eyes everywhere on the map so it is really helpful when we find these things and can report bugs/issues that we're seeing to the people providing us the technology to build these online maps!

**Comment by makella** [comment]
related to:
https://github.com/nationalparkservice/park-tiles/issues/144

**Comment by mtaylorlong** [comment]
Since this relates to OSM roads, I think it's no longer relevant. I'm closing this issue.
