### ISSUE TITLE
Delete existing data in locked parks

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#251]
_Note: regional park unit lists were taken from [this site](http://inside.nps.gov/index.cfm?handler=parkunitlist&sort=7), so take it with a grain of salt. Not all of the parks originally had Places data in them._
### AKR
- [x] Alagnak
- [x] Aleutian World War II
- [x] Aniakchak
- [x] Bering Land Bridge
- [x] Cape Krusenstern
- [x] Denali
- [x] Gates Of The Arctic
- [x] Glacier Bay
- [x] Inupiat Heritage Center
- [x] Katmai
- [x] Kenai Fjords
- [x] Klondike Gold Rush
- [x] Kobuk Valley
- [x] Lake Clark
- [x] Noatak
- [x] Sitka
- [x] Wrangell - St Elias
- [x] Yukon - Charley Rivers
#### Exceptions

~~\- [ ] Western Arctic National Parklands~~ (collection of 4 park units)
### IMR
- [x] Alibates Flint Quarries   alfl
- [x] Amistad   amis
- [x] Arches    arch
- [x] Aztec Ruins   azru
- [x] Bandelier band
- [x] Bent's Old Fort   beol
- [x] Big Bend  bibe
- [x] Bighorn Canyon    bica
- [x] Big Thicket   bith
- [x] Black Canyon Of The Gunnison  blca
- [x] Bryce Canyon  brca
- [x] Canyon De Chelly  cach
- [x] Casa Grande Ruins cagr 
- [x] Canyonlands   cany
- [x] Capitol Reef  care
- [x] Carlsbad Caverns  cave
- [x] Capulin Volcano   cavo
- [x] Cedar Breaks  cebr
- [x] Chamizal  cham
- [x] Chaco Culture chcu
- [x] Chickasaw chic
- [x] Chiricahua    chir
- [x] Colorado  colm
- [x] Coronado  coro
- [x] Curecanti cure
- [x] Devils Tower  deto
- [x] Dinosaur  dino
- [x] El Malpais    elma
- [x] El Morro  elmo
- [x] Florissant Fossil Beds    flfo
- [x] Fort Bowie    fobo
- [x] Fossil Butte  fobu
- [x] Fort Davis    foda
- [x] Fort Laramie  fola
- [x] Fort Union    foun
- [x] Gila Cliff Dwellings  gicl
- [x] Glen Canyon   glca
- [x] Golden Spike  gosp
- [x] Grand Canyon  grca
- [x] Grant-Kohrs Ranch grko
- [x] Great Sand Dunes  grsa
- [x] Guadalupe Mountains   gumo
- [x] Hovenweep hove
- [x] Hubbell Trading Post  hutr
- [x] John D Rockefeller Jr jodr
- [x] Lake Meredith lamr
- [x] Little Bighorn Battlefield    libi
- [x] Lyndon B Johnson  lyjo
- [x] Mesa Verde    meve
- [x] Montezuma Castle  moca 
- [x] Natural Bridges   nabr
- [x] Navajo    nava
- [x] Oklahoma City okci (_note: missing park boundary; issue [here](https://github.com/nationalparkservice/places-data/issues/243)_)
- [x] Organ Pipe Cactus orpi
- [x] Palo Alto Battlefield paal
- [X] Padre Island  pais
- [x] Pecos peco
- [x] Petrified Forest  pefo
- [x] Petroglyph  petr
- [x] Hohokam Pima  pima
- [x] Pipe Spring pisp
- [x] Rainbow Bridge  rabr
- [x] Rio Grande  rigr
- [x] Rocky Mountain  romo
- [x] San Antonio Missions  saan
- [x] Saguaro sagu
- [x] Sand Creek Massacre sand
- [x] Salinas Pueblo Missions sapu
- [x] Sunset Crater Volcano sucr
- [x] Timpanogos Cave tica
- [x] Tonto tont
- [x] Tumacácori  tuma
- [x] Tuzigoot  tuzi
- [x] Washita Battlefield waba
- [x] Walnut Canyon waca
- [x] White Sands whsa
- [x] Wupatki wupa
- [x] Yucca House yuho
- [x] Zion  zion
#### Exceptions

**`.osm` file already uploaded from IMR:**
- [x] Glacier glac

**National trails:**
~~\- [ ] California cali~~
~~\- [ ] El Camino Real de Tierra Adentro elca~~
~~\- [ ] El Camino Real de los Tejas elte elte~~
~~\- [ ] Mormon Pioneer mopi~~
~~\- [ ] Oregon  oreg~~
~~\- [ ] Pony Express poex~~
~~\- [ ] Santa Fe safe~~
~~\- [ ] Trail Of Tears trte~~

**Autonomous parks:**
~~\- [ ] Grand Teton grte~~
~~\- [ ] Yellowstone yell~~

**Comment by jakecoolidge** [comment]
I struck out YELL and GRTE as "exempted" parks. GLAC is struck out since it houses current IMR data. Let me know if I should delete this park as well, or if there's any other parks that should be exempted.

**Comment by chadlawlis** [comment]
Other exceptions listed in original comment.

All set here.
