### ISSUE TITLE
Add Ice Age National Scenic Trail (IATR) to Parks Database

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#254]
Dee Finnegan, the GIS Specialist for Ice Age National Scenic Trail (IATR) pointed out that we don't list IATR in our Places Editor drop-down. I'm guessing this is because it's a scenic trail and we couldn't properly accommodate it before. With our new Parks database, I think we can include it.

I've asked Dee for the official trail geometry. If there's no official polygon boundary, we can make one with a buffer (like we did for APPA). I'll post back here when we get the boundary.

@jimmyrocks: How does the lands database handle this geometry? Do they store a line?

**Comment by nateirwin** [comment]
Well, this is a tricky one. We've intentionally avoided adding National Trails to our parks database, and Park Tiles, up to this point because they aren't "official" NPS units. Most of the lands that are part of national trails aren't NPS property, etc.

I do, however, think we can support it in Places Editor. Perhaps we should start tracking National Trails, National Historic Areas, etc. in a separate table?

**Comment by mtaylorlong** [comment]
Well, I think there's a way for us to store the geometries without ever presenting them inappropriately on a map. IATR has a website and a map, so we'll need to figure out how to show this in Park Tiles.

**Comment by mtaylorlong** [comment]
As for the separate table, I think we could still keep them all in one place. Since we know the designation (National Trails, National Historic Areas, etc.) we can exclude those cases from rendering where applicable.

**Comment by nateirwin** [comment]
Agreed. If we just add it into CartoDB, however, a lot of apps that are pulling from there will start displaying it. So we'll just need to be careful about how we implement this.

**Comment by mtaylorlong** [comment]
I emailed Dee to let her know that this is a bit more complicated than I thought. I asked if she had any advice about how the trail can be shown at large scales without leading folks into private property.

**Comment by chadlawlis** [comment]
This has been added to our database via #784 and the geometry added via #788.

It is currently set to not render in Park Tiles, only to be used for the "Parks Near Me" NPS.gov project. We'll want to check with the park to confirm the accuracy of the geometry if/when we decide to render it.
