### ISSUE TITLE
Support "Golf Course" preset as point

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#255]
Probably not a common use for most parks, but I have the area of a golf course for DEWA. It would be nice to render this area differently in Park Tiles, especially if we're going with the area of interest approach that might bring more features like this into play.

@jimmyrocks what do you think?

**Comment by nateirwin** [comment]
I've actually been surprised by how many golf courses I've seen in parks. I think it's more common than you might think. I don't see any reason not to add it?

**Comment by chadlawlis** [comment]
GOGA as example: http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=16.72/-122.46758/37.79151.

**Comment by chadlawlis** [comment]
Added as `{"leisure":"golf_course"}` as area.

Land Recreation > Golf > Golf Course

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
@jimmyrocks we were under the impression this had been added back in December - can we get this preset into Editor? We need it for the GOGA app, among others.

**Comment by chadlawlis** [comment]
This is now live.

**Comment by chadlawlis** [comment]
Like Athletic Field https://github.com/nationalparkservice/places-data/issues/297#issuecomment-197425005 the area for this is functional, but the point does not seem to show up in Editor.

Reopening. @jimmyrocks could be the bug you mentioned with presets using the same class and superclass for points and polygons?

**Comment by chadlawlis** [comment]
All set here - the presets were regenerated and this is now live as both a point and area.

The symbol for the point is not showing up correctly in Editor, however, which will be addressed via https://github.com/nationalparkservice/places-editor/issues/111.
