### ISSUE TITLE
GLCA shifted 125 meters west

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#26]
Hey guys, It appears that the GLCA boundary is shifted about 125 meters west of where it should be.  These two images show that shift between GLCA/CARE and GLCA/CANY.  Let me know if you have any questions.  Thanks!
![capture1](https://cloud.githubusercontent.com/assets/11545684/6838457/3fb90bf0-d31f-11e4-9392-633255168291.JPG)
![capture](https://cloud.githubusercontent.com/assets/11545684/6838459/43943452-d31f-11e4-8bf9-016753895d56.JPG)

**Comment by makella** [comment]
@heidiogle do you happen to have a better, more accurate boundary that we can use? It would be good for us to have that to replace this one!

Thanks,
mamata

**Comment by heidiogle** [comment]
Hey Mamata, here's the link to the Lands dataset in IRMA.

https://irma.nps.gov/App/Reference/Profile/2220234

Hope that helps!

**Comment by jimmyrocks** [comment]
This is part of a much bigger problem with the WSD_Parks import. It seems like many of those parks were projected incorrectly. I think it would make sense to go through each park in WSD_Parks and compare it with IRMA and choose from there.

**Comment by nateirwin** [comment]
For now, can't we just switch the source for GLCA and rerun the boundaries?

**Comment by jimmyrocks** [comment]
We can do that for now for this entry, but the problem will keep coming up with different parks

**Comment by nateirwin** [comment]
I think that is ok for now. We'll have Chad take a look at this in a more methodical way, but addressing this issue will allow us to get back to @heidiogle.

**Comment by makella** [comment]
@heidiogle this is fixed!

http://www.nps.gov/npmap/tools/park-tiles/#12/37.6553/-110.8018

**Comment by heidiogle** [comment]
Looks great!  Thanks Mamata!
