### ISSUE TITLE
Add Southeast Region National Historic Trails to Parks Database

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#260]
Maricela Avalos from the Southeast Region contacted us about National Historic Trials. She has noticed that we don't support these in the same way we support other park units (they aren't an option in our drop-down). I let her know we're aware of the issue and working on it with other trails as well. I also asked if she could send us authoritative data for the trails that we can use to test our solution.

Here are the trails she's asking about:
- Selma to Montgomery
- Overmountain Victory

Here's here email:

> Hello, My name is Maricela Avalos, currently working with the GIS Team at the Southeast Regional Office. We have started adding data to Places via the Places Editor and I noticed that there is no data for some of our National Historic Trails, such as Selma to Montgomery or Overmountain Victory. 
> They do not show up in the drop down list as NPS units. Are there plans in the future to include data from these sites? I'm holding off on making any edits to these sites until further notice.

I've let her know where tracking the issue here.

**Comment by jimmyrocks** [comment]
We've had an issue with a lot of trails in the past that "trails" are actually a vague area in which the trail may or may not be. This is because there are important sites along the trail, but much of the trail is on private land and the NPS doesn't want to call attention to these areas.

**Comment by mtaylorlong** [comment]
Right - we just need a solution that balances these concerns. I don't think we should show any kind of green boundary like we do for other units, but I do think that we should add our own nps version of the trail over OSM and make sure it looks okay by masking out clashing osm labels and geometries.

These trails have their own websites and their own maps, so we need a Park Tiles solution. Even if it's not perfect, it's better than not acknowledging them at all.

**Comment by jimmyrocks** [comment]
This might be a great use for the line and max_zoom_poly features we have
in our parks table now.

**Comment by mtaylorlong** [comment]
I've been thinking about this issue a bit...

It bothers me that we don't have a record of these historic trails in our parks table at all, simply because of these park tiles issues. I'd love to get these into our parks table as a line, make a dummy boundary for them if one truly does not exist, then only show the simplified line at small zoom levels, but NOT show the boundary at larger zoom levels. If we store a boundary, then we can still accommodate editing in Places, we just won't show any kind of boundary or line when you're zoomed in past 8 or so. This way we have a record of it as a valid park, and we can store places data for it (if it exists), but we avoid the issue of sending people into private property.

This is similar to the discussion we had about the OKCI. The main issue is if someone hits our parks table to download the boundary, how do we let them know that it's not a representation of NPS property?

**Comment by chadlawlis** [comment]
See also https://github.com/nationalparkservice/places-data/issues/411 for SEMO and https://github.com/nationalparkservice/places-data/issues/409 for OVVI.

Tracking all National Trail related issues via https://github.com/nationalparkservice/places-data/issues?q=is%3Aissue+is%3Aopen+label%3Anational-trail.

**Comment by chadlawlis** [comment]
Records for both Selma to Montgomery and Overmountain Victory National Historic Trails have been added to our database, and geometries added via #788.

They are currently set to not render in Park Tiles, only to be used for the "Parks Near Me" NPS.gov project. We'll want to check with the region to confirm the accuracy of the geometries if/when we decide to render them.
