### ISSUE TITLE
Group Campground icon truncates at #17 in PT 3.0

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-data#263]
http://insidemaps.nps.gov/park-tiles-3/#17/35.60284/-83.77428 note the truncated icon:

![image](https://cloud.githubusercontent.com/assets/5861784/11381712/9667a85a-92cb-11e5-8fc9-e3e7e62d1799.png)

**Comment by chadlawlis** [comment]
Hm, this is displaying at Z16 for me, not 17.

cc @mtaylorlong

**Comment by tpcolson** [comment]
In Chome, in the only true and ultimate OS, Win 64....in IE 10 it happens at 16, but not 17.

**Comment by mtaylorlong** [comment]
Thanks @tpcolson for the heads up. I'll look into this and see if I can figure out what's going on.

**Comment by mtaylorlong** [comment]
We've decided to remove POI's entirely from Park Tiles, and instead offer a more customizable POI vector overlay solution. See issues #381 and #380.
