### ISSUE TITLE
Visitor center rendering is inconsistent

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-data#265]
Note that at 11 (http://insidemaps.nps.gov/park-tiles-3/#10/35.6177/-83.4796 ) 3 VC's are shown. Zoon into http://insidemaps.nps.gov/park-tiles-3/#11/35.5649/-83.5153, and 3 different VC's are shown....this is inconsistent with http://www.nps.gov/npmap/tools/park-tiles/#10/35.4937/-83.3876 and http://www.nps.gov/npmap/tools/park-tiles/#11/35.5643/-83.4370

**Comment by mtaylorlong** [comment]
We've decided to remove POI's entirely from Park Tiles, and instead offer a more customizable POI vector overlay solution. See issues #381 and #380.
