### ISSUE TITLE
Add attributes to Roads and Trails vector tiles

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#268]
We need a bit more control over styling roads and trials. Here's our wishlist for new attributes to bring into the Mapbox vector tiles we render from Places:
- `oneway`: yes or no (already in use)
- `surface`: paved, unpaved, dirt, cobblestone, boardwalk, etc.
- `access`: yes, no, public, private, nps-only, seasonal

We should further discuss the recommended values to use for these. Can anyone else think of other attributes we would need for all roads and trails? cc: @jimmyrocks, @cwlawlis802, @jakecoolidge, @nateirwin.

**Comment by mtaylorlong** [comment]
Thought of one more attribute that may come into play heavily in the mobile apps:
- `accessible`: yes or no

You could also distinguish more than 'yes' or 'no' with values like 'wheelchair' to be more specific that a trail is wheelchair accessible. In some parks' custom mobile maps, we could use this attribute to distinguish between different kinds of accessibility.

**Comment by jimmyrocks** [comment]
We may want to discuss accessibility.

Wheelchair the handicap accessible tag used in OpenStreetMap. There were concerns with using it as an official tag though because accessibility is a legal issue, and we can't have anyone just tag things as accessible. We had discussed an NPS specific tag that only certain users could use to denote ADA compliance, but we pushed the issue off because of its complexity. If we do want to start looking into it again, we should reach out to Tom Colson.

**Comment by jimmyrocks** [comment]
surface should be available in the next release of the tiles
access is a reserved word, so the field is called "access_tag"

**Comment by mtaylorlong** [comment]
cool. About `access_tag`: is there something else comparable in osm we could use? It kind of bugs me to have it named differently than the others. :/

**Comment by jimmyrocks** [comment]
"access" is the tag that OSM uses, and is the column name in the pgsnapshot file. I'm not sure why mbstudio classic doesn't support its use, I can look more into it though.

**Comment by jimmyrocks** [comment]
Nevermind, it's not working because it's already there

**Comment by jimmyrocks** [comment]
Following with @jakecoolidge and @mtaylorlong that these fields are currently working for you?

**Comment by mtaylorlong** [comment]
@jimmyrocks: I haven't made any changes to PT3 to take advantage of these yet. But I'm guessing they'll be fine. I'll let you know when I actually start working with them.

**Comment by jimmyrocks** [comment]
Cool, no rush… I'll just leave this open for the time being

**Comment by mtaylorlong** [comment]
This one's all good!
