### ISSUE TITLE
Label Cumberland Gap one zoom level sooner

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#27]
Try to label Cumberland Gap on the Tennessee/Kentucky border one zoom level sooner.

This feedback came in from the Superintendent of Abraham Lincoln Birthplace National Historical Park.

**Comment by jimmyrocks** [comment]
The label is set to go on at zoom 6, but it conflicts with the label from Big South Fork National River & Recreation Area. Big South Fork is a larger park by area, so that is why it has priority over Cumberland Gap.

**Comment by nateirwin** [comment]
Understood, but can we move one (or both) of the labels to try to get the both labeled at the same time?

**Comment by nateirwin** [comment]
This is especially important on the state pages: http://www.nps.gov/state/ky/index.htm. A visitor should be able to go there and visually identify which parks exist in a state without having to zoom/pan the map. I understand that this isn't possible in all cases (at least not at this point), but Cumberland Gap is way east of Big South Fork, so it should be able to label them both.

If our labeling rules give Big South Fork priority over Cumberland Gap, we need to change this hierarchy in our data source, as they have equal prominence in reality.

**Comment by nateirwin** [comment]
I should/will respond to Bill Justice, Kat Kirby, and Judy Jaffie when this issue is taken care of.

**Comment by nateirwin** [comment]
Going back and looking through email, this issue was actually reported by multiple people going all the way back to December of 2014. Any chance we can take a look at it sooner rather than later?

Cc/ @jakecoolidge and @mtaylorlong

**Comment by jakecoolidge** [comment]
I'll get started this afternoon. It will be a cosmetic fix, something like we did in Michigan for Sleeping Bear Dunes, but I'm thinking our new boundaries table will have the data we need to better support Cumberland Gap moving forward.

**Comment by mtaylorlong** [comment]
Yeah. This will be easy in our new boundaries table set up. I think we can
pull this off if Park Tiles 2.1 since the point should be present in
earlier tiles, but it may be a little tricky since the labeling point might
not be available in the tiles at the previous zoom level.

**Comment by nateirwin** [comment]
Fixed. Thanks, @jakecoolidge!

![kentucky__u_s__national_park_service_](https://cloud.githubusercontent.com/assets/10443/9890427/1425de10-5bbd-11e5-9e64-26f9bbfa1460.jpg)

**Comment by jakecoolidge** [comment]
Yeah! Fyi, Park Tiles 2.1 (incl. Slate and Imagery) updated as well. The xml for Park Tiles 2.1 is now 749KB, underscoring how key that new boundaries table will be once implemented.
