### ISSUE TITLE
Add presets "Cinema" and "Library"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#274]
[`{"amenity":"cinema"}`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcinema) and [`{"amenity":"library"}`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlibrary).

One of each was added to HOFR: https://github.com/nationalparkservice/places-data/issues/270.

**Comment by chadlawlis** [comment]
Added "Cinema" as `{"amenity":"cinema"}`. Service > Entertainment > Cinema.

Added "Library" as `{"amenity":"library"}`. Service > Library > Library.

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
Both are now live.
