### ISSUE TITLE
Add preset "Farm"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#275]
[`{"place":"farm"}`](http://wiki.openstreetmap.org/wiki/Tag:place%3Dfarm) as a point of interest.

See also https://help.openstreetmap.org/questions/504/how-should-a-farm-be-tagged.

**Comment by chadlawlis** [comment]
Added to MAVA https://github.com/nationalparkservice/places-data/issues/273.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
This has not been added to the preset sheet yet, so did not go live with the latest preset regeneration.

**Comment by chadlawlis** [comment]
Adding to GOGA #612.

**Comment by chadlawlis** [comment]
This has been added to the spreadsheet, will go live once presets are regenerated.

**Comment by chadlawlis** [comment]
This is now live.
