### ISSUE TITLE
replace existing trails in NCR with new geometries (PT3 feedback)

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#278]
Based on some settings Cynthia uses in ArcGIS, some of her trail geometries didn't import properly into Places. She's provided corrected geometries in the geodatabase stored [here.](https://drive.google.com/open?id=0B8kRL6psDWmZVEJGS1J0d2JXMEkta3Rqb081UndGSHZpYm5z)

She also notes: 

> NAMA doesn't really have traditional trails; they have multi-use paths. I keep these separate in the 
> "Paths" feature class that I sent and I'm re-sending with updates.

Current data are marked as Pedestrian Paths ("highway":"footway"). @cwlawlis802 and @jimmyrocks, is this the correct tagging for these types of features? If so, it might be sufficient to maintain that tagging and develop a path symbol that differentiates them from trails.

**Comment by chadlawlis** [comment]
I think using "Pedestrian Path" makes sense, though I guess it depends on the definition of "multi-use". Technically a pedestrian path is intended primarily for pedestrian traffic, though they can be open to other modes of transportation like bicycles. Cartographically, this should render differently from a traditional trail `{"highway":"path"}` so this sounds like an appropriate use for it.

**Comment by jakecoolidge** [comment]
Paths and trails in the core DC area uploaded to Places today. Cynthia and I agree the NCR trails/paths most in need of revision are found adjacent to NAMA. Will prioritize the remainder of the updates when Cynthia returns from travel.

**Comment by mtaylorlong** [comment]
@jakecoolidge: If you think this issue won't be resolved soon, we can move it to the next release milestone (Park Tiles 3.0.2).

**Comment by jakecoolidge** [comment]
@mtaylorlong: sounds good. What's in there currently shouldn't hold up the 3.0.1 release.

**Comment by jakecoolidge** [comment]
With some digging, I believe I've pinpointed those areas that did incur edits between Oct. 8 and Nov. 30, uploaded any stragglers, and determined data is current in Places. Will close this issue and email Cynthia shortly.
