### ISSUE TITLE
replace existing POIs in NCR with new data (PT3 feedback)

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#280]
Data found [here.](https://drive.google.com/open?id=0B8kRL6psDWmZVEJGS1J0d2JXMEkta3Rqb081UndGSHZpYm5z) This data should replace all POIs seeded in October.

**Comment by jakecoolidge** [comment]
Tags were assigned to POIs based on the attribute POI_Type. Tags are summarized below. Where POI_Type matched a Places Preset, the tags were taken directly from the Places Preset Classes spreadsheet and are not repeated below. POIs with a miscellaneous POI_Type, "Recreation" were assigned a variety of tags; these are listed in a second table.

| POI_Type | Count | tags used |
| --- | --- | --- |
| Amphitheater | 9 |  |
| Auto Tour Stop | 5 | tourism:information; information:exhibit |
| Boat Launch | 34 |  |
| Bus Stop | 9 |  |
| Campground | 24 |  |
| Campsite | 42 |  |
| Cannon | 6 |  |
| Canoe/Small Boat Access | 6 |  |
| Cemetery | 6 |  |
| Drinking Water | 33 |  |
| Entrance Station | 7 |  |
| Exhibit | 18 |  |
| Ferry | 1 | amenity:ferry_terminal |
| Fishing | 4 |  |
| Food Service | 25 |  |
| Fort | 3 |  |
| Gate | 37 |  |
| Headquarters | 1 |  |
| Historic House Site | 8 |  |
| Information | 3 |  |
| Lighthouse | 2 |  |
| Lock | 83 |  |
| Marina | 8 |  |
| Milemarker | 185 |  |
| Monument, Memorial, or Statue | 120 |  |
| Museum | 37 |  |
| Overlook or Viewpoint | 17 |  |
| Park Headquarters | 10 |  |
| Parking | 244 |  |
| Picnic Area | 86 |  |
| Ranger Station | 4 |  |
| Recreation | 8 | _see below_ |
| Recreation Center | 1 | leisure:sports_centre |
| Recreation Field | 7 | landuse:recreation_ground |
| Recreation Field: Baseball/Softball | 16 | leisure:pitch; sport:baseball |
| Recreation Field: Equitation Field | 1 | leisure:pitch; sport:equestrian |
| Recreation Field: Multi-Use Athletic Field | 2 | landuse:recreation_ground |
| Recreation Field: Polo | 1 | leisure:pitch; sport:equestrian |
| Recreation Field: Soccer/Football | 9 | leisure:pitch; sport:soccer |
| Recreation Field: Volleyball | 5 | leisure:pitch; sport:volleyball |
| Recreation: Basketball | 6 | leisure:pitch; sport:basketball |
| Recreation: Fitness Station | 2 | leisure:fitness_station |
| Recreation: Golf Course | 4 |  |
| Recreation: Ice Skating | 3 |  |
| Recreation: Playground | 8 |  |
| Recreation: Roller Skating | 1 | leisure:sports_centre; sport:roller_skating |
| Recreation: Swimming | 1 |  |
| Recreation: Tennis | 7 | leisure:pitch; sport:tennis |
| Rental Venue | 2 | amenity:shelter; building:pavilion |
| Restroom | 180 |  |
| Store | 15 |  |
| Trailhead | 14 |  |
| Visitor Center | 26 |  |
| Visitor Protection | 7 | amenity:police |

#### POI_Type="Recreation"

| name | tags used |
| --- | --- |
| Anacostia Community Bathhouse | amenity:public_bath |
| Camp Strauss | leisure:park |
| Carderock Area | leisure:park |
| Hard Bargain Farm | amenity:education_centre; building:yes |
| National Colonial Farm | tourism:museum |
| Oxon Hill Farm | tourism:information; information:exhibit |
| Smithsonian Carousel | tourism:attraction |
| Tidal Basin Paddle Boats | leisure:slipway |

**Comment by jakecoolidge** [comment]
POIs for the core DC area uploaded today. Will prioritize outlying areas once Cynthia returns from travel.

**Comment by mtaylorlong** [comment]
@jakecoolidge: I'm assuming this one isn't quite finished, so I'm pushing it to the next release.

**Comment by jakecoolidge** [comment]
@mtaylorlong: that works. I never heard back from Cynthia but I might go ahead and finish this anyway next week.

**Comment by jakecoolidge** [comment]
With some digging, I believe I've pinpointed those areas that did incur edits between Oct. 8 and Nov. 30, uploaded any stragglers, and determined data is current in Places. Will close this issue and email Cynthia shortly.
