### ISSUE TITLE
Resolve OBED/OBRI Discrepancy

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#283]
Maricela Avalos has been working on Places data in the Southwest Region and noticed a unit code discrepancy for Obed Wild & Scenic River. The unit is listed twice in our drop-down menu because we have it listed under two different unit codes: OBED and OBRI. According to Maricela, **the official unit code is OBRI**.

Here's what we need to do to resolve the issue:
- [X] ~~Remove OBED record from our Parks database.~~ Change OBED unit code to OBRI in `parks`, `parks_poly`, and `parks_line` and change `data_source` to "Land Resources Division" in `parks`.
- [X] Check to see if our OBRI record has the right geometry and the right attributes for display in PT3.
- [x] Change all OBED tags in Places to OBRI (we can do this in JOSM)
- [x] Check to make sure the incorrect OBED tag isn't coming from another database. If it is, we'll want to make sure it doesn't keep showing up when we update.

@cwlawlis802: Do you mind deleting the record in the Parks Table?

Here's Maricela's original email:

> Hello NPMap Team, I started to look at the data in Places Editor for Obed Wild & Scenic River and came across a couple of discrepancies. When attempting to select the park in the "Zoom to a Park..." drop down menu, it comes up twice in the list. I've also noticed that the data comes with either "OBED" or "OBRI" as the unit code. 
> Additionally, while looking at the park in Park Tiles 3 Beta, OBRI shows up as a point. I got an error when attempting to search for the park ("There was an error getting the bounds for that park"). I'm not sure how to go about editing data for this park, although I'd like to update the existing data to contain the official "OBRI" unit code. 
> Has anyone on the team noticed these issues? Any information will be appreciated.
> Thank you, Maricela

**Comment by mtaylorlong** [comment]
One more item on the to-do list:
- [x] Update CartoDB table so the duplicate records aren't pulled into the drop-down list in editor. Maricela mentioned getting a geometry error, so we'll need to make sure that the record we're using has a valid geometry.

**Comment by nateirwin** [comment]
Looks to me like OBED is the official unit code: http://www.nps.gov/obed/. Not that NPS.gov is always right, but it usually is.

**Comment by mtaylorlong** [comment]
Ah. Interesting twist. Well, we'll have to get that sorted out before we proceed. I'll ask Maricela to double check.

**Comment by chadlawlis** [comment]
From the park's GIS specialist, Chad Harrold:

> The alpha code for the park is OBRI. For all official documents we use OBRI.

It's listed as OBED throughout NPS.gov, though, as @nateirwin mentions. Is there a logical way for us to decide between the two, or do we simply assume the park preference?

**Comment by nateirwin** [comment]
Well, this is the "official" list: http://inside.nps.gov/index.cfm?handler=parkunitlist. It says OBED is the correct unit code. I say "official" because I've found errors in this list before, and it seems like it isn't updated all that often.

**Comment by chadlawlis** [comment]
Right, but if the park is using something different do we default to their preference or what is considered "authoritative" via the NPS.gov pages? This seems similar to how we handle boundaries - defaulting to authoritative (Lands) unless otherwise specified by the park.

**Comment by chadlawlis** [comment]
So, this unit is currently listed with unit_code OBED in our places_boundaries table, pulling from `WSD_Parks`.

It is available as both OBED and OBRI from our former CartoDB "Parks" boundary table, with identical geometries. OBRI is pulling from Lands, while OBED is pulling from `WSD_Parks` - the latter of which was transferred to the new table, the former which was not. The former (Lands) is missing most other attribute data (visitors, state, phone, full_designation, climate, blurb, and address), most/all of which has been antiquated with our new table. 

It is available through Lands as only unit_code OBRI, which again has an identical geometry to what we have on file as OBED via `WSD_Parks`.

So, if we decide to go with OBRI instead of OBED we can simply update this directly in the places_boundaries table along with the source - to pull from Lands instead of `WSD_Parks`.

I can then move on to change all map feature unit codes from OBED to OBRI in Places via JOSM.

For this:

>  Check to make sure the incorrect OBED tag isn't coming from another database. If it is, we'll want to make sure it doesn't keep showing up when we update.

I am assuming you are referring to another boundary database, i.e. Lands, @mtaylorlong? If so, Lands is using OBRI so that should be fine.

**Comment by nateirwin** [comment]
All this is making me think we should create a table to track alternate unit codes. The reason I say this is we need a way to match both obed and obri to the correct data, no matter which of those codes is passed in. That would make it less important for us to "get it right" in our database.

**Comment by chadlawlis** [comment]
Sounds good, so we will go with OBRI.

The plan is to create a lookup table with fields "unit_code" and "alt_unit_code", with each alternate unit code having its own record.

With this in place, we will default to the park's preferred unit code, even if this strays from the "official" unit code as displayed on NPS.gov (http://inside.nps.gov/index.cfm?handler=parkunitlist). We will add this to our Disclaimer page, which I will open another issue for.

Current alternates include:
- OBRI (OBED)
- LAME (LAKE)
- SEQU and KICA (SEKI)
- ...

**Comment by chadlawlis** [comment]
Okay, we should be all set here.

I updated checklists to reflect work completed. OBED is now OBRI, and the two issues opened above will help track this and cover us down the road. Closing.
