### ISSUE TITLE
Populate alternate unit code table

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#284]
See https://github.com/nationalparkservice/places-data/issues/283#issuecomment-161716154.

@jimmyrocks sounds like you have solid grasp of how you want this to look, so assigning to you.

**Comment by chadlawlis** [comment]
| unit_code | alt_unit_code | issue |
| --- | --- | --- |
| thje | jefm | https://github.com/nationalparkservice/places-data/issues/319 |
| frsp | fred | https://github.com/nationalparkservice/places-data/issues/318 |
| obri | obed | https://github.com/nationalparkservice/places-data/issues/283 |
| wamo | wash |  |
| cong | cosw |  |

**Comment by chadlawlis** [comment]
Table has been created in `places_boundaries` https://github.com/nationalparkservice/places-data/blob/gh-pages/boundaries/database/views/alternate_unit_codes.sql.

Repurposing this to populate table.

**Comment by chadlawlis** [comment]
Table is live in CartoDB here: https://nationalparkservice.cartodb.com/u/nps/tables/alternate_unit_codes.

**Comment by cwlawlis802** [comment]
Note to revisit FRSP vs. FRED: https://github.com/nationalparkservice/places-data/issues/324.

**Comment by chadlawlis** [comment]
Added `unit_code = 'wamo'` (currently used in our table, also on NPS.gov http://www.nps.gov/wamo/index.htm), `alt_unit_code = 'wash'` (listed on http://inside.nps.gov/index.cfm?handler=parkunitlist) for "Washington Monument".

**Comment by chadlawlis** [comment]
Added `unit_code = 'cong'` (currently used in our table, also on NPS.gov http://www.nps.gov/cong/index.htm), `alt_unit_code = 'cosw'` (listed on http://inside.nps.gov/index.cfm?handler=parkunitlist) for "Congaree National Park".

**Comment by chadlawlis** [comment]
This is live and has been populated with all alternate unit codes that I have come across in reviewing the NPS.gov list. I'm sure more will come into play over time, but closing this out as a finished initial effort.

**Comment by chadlawlis** [comment]
Note to revisit FRSP vs. FRED: https://github.com/nationalparkservice/places-data/issues/324.

**Comment by nateirwin** [comment]
Thanks, @cwlawlis802. I'm using this in the new HFC park map interface now.
