### ISSUE TITLE
Create task to Synchronize CartoDB parks table and update unit codes

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-data#285]
We need an automatic process to make sure the CartoDB parks table is up to date with our internal table and that the unit codes can be changed without changing the rest of the park information.

**Comment by chadlawlis** [comment]
The `unit_code` changing problem was addressed with the use of `unit_id`, right @jimmyrocks?

**Comment by jimmyrocks** [comment]
right

**Comment by chadlawlis** [comment]
@jimmyrocks can we close this out?

If so, could you insert the SQL you used to create the new table for reference?

**Comment by jimmyrocks** [comment]
SQL for the database creation can be found here:
https://github.com/nationalparkservice/places-data/tree/gh-pages/boundaries/database/views

**Comment by nateirwin** [comment]
So, which tables are out in CartoDB? Just the `parks` table?

**Comment by jimmyrocks** [comment]
There is one table in CartoDB, and it include data from The Parks and Parks Poly tables.
The Parks table in CartoDB is (currently) created with this query:

``` sql
SELECT "parks"."unit_id" as "unit_id",
  "parks"."unit_code" AS "unit_code",
  "parks"."unit_region" AS "region",
  "parks"."unit_desig_full" AS  "designation",
  "parks"."unit_name_short" || ' ' || COALESCE(parks.unit_desig_abbr, '')  AS "display_name",
  "parks"."unit_name_long" || ' ' || COALESCE(parks.unit_desig_full, '')  AS "full_name",
  "parks"."min_zoom_poly" AS "minzoompoly",
  "parks"."unit_url" AS "url",
  "parks"."subunit_of" AS "subunit_of",
  ST_X(ST_Transform(geom_point, 4326)) AS "longitude",
  ST_Y(ST_Transform(geom_point, 4326)) AS "latitude",
  "parks"."unit_state" AS "state",
  "parks"."last_updated" AS "updated_at",
  "parks"."date_created" AS "created_at",
  ST_Transform("parks_poly"."geom_poly", 4326) AS "the_geom"--,
  -- ST_Transform("parks_poly"."geom_poly", 3857) AS "the_geom_webmercator"
FROM
  "parks"
    LEFT JOIN "parks_poly" ON "parks"."unit_id" = "parks_poly"."unit_id"
WHERE
  lower("data_source") != 'label-only';
```

**Comment by nateirwin** [comment]
Ok great. So `latitude` and `longitude` contain the park centroid? Just making sure I understand the structure, because I'm going to extend NPMap.js' geocoder control to use points if a polygon doesn't exist.

**Comment by nateirwin** [comment]
Reopening this. The `alternate_unit_codes` table in CartoDB is not synced up with our internal parks database. This table is required by the NPS.gov park map viewer interface, so it's imperative that it is kept up-to-date.

**Comment by jimmyrocks** [comment]
Thanks for reopening this, I'll take a look

**Comment by jimmyrocks** [comment]
I think this should be closed by our new sync'd server. Thoughts?

**Comment by chadlawlis** [comment]
Any updates/changes to the boundaries database will be automatically/regularly pushed out to CartoDB through this new server, right? If so we're definitely good to close here.

**Comment by jimmyrocks** [comment]
That's correct. Closing
