### ISSUE TITLE
Document boundary process for external review

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#286]
> Something we can share with Lands and the regional coordinators so they understand how we’re handling boundaries
> And we need to start “looping” Roger Johnson and the regional coordinators in when parks want us to make changes

We have a good start here: https://github.com/nationalparkservice/places-data/blob/gh-pages/boundaries/README.md.

**Comment by chadlawlis** [comment]
Current boundary source status (**as of 12/07/15**):
- 35 from park/region (~9%)
- 311 from WSD_Parks (~76%)
- 57 from Land Resources Division (~14%)
- 4 with no geometry/source (~1%)  
  = 407 in total

**Park or region (35):**
Acadia National Park
African Burial Ground National Monument
Bandelier National Monument
Blue Ridge Parkway
Cape Hatteras National Seashore
Catoctin Mountain Park
Death Valley National Park
Fort Monroe National Monument
Fort Point National Historic Site
Gateway National Recreation Area
General Grant National Memorial
Glen Canyon National Recreation Area
Gloria Dei Church National Historic Site
Grand Canyon National Park
Grand Canyon-Parashant National Monument
Great Smoky Mountains National Park
Haleakala National Park
Klondike Gold Rush (Seattle Unit) National Historical Park
Korean War Veterans Memorial
Lake Mead National Recreation Area
Maggie L Walker National Historic Site
Mount Rainier National Park
National Capital Parks
New Bedford Whaling National Historical Park
New Orleans Jazz National Historic Park
Pinnacles National Park
Prince William Forest Park
Richmond National Battlefield Park
Saint Croix Island International Historic Site
San Antonio Missions National Historical Park
Saugus Iron Works National Historic Site
Shenandoah National Park
Statue Of Liberty National Monument
Theodore Roosevelt Birthplace National Historic Site
Waco Mammoth National Monument

**WSD_Parks (311):**
Abraham Lincoln Birthplace National Historical Park
Adams National Historical Park
Agate Fossil Beds National Monument
Alagnak Wild River
Alibates Flint Quarries National Monument
Allegheny Portage Railroad National Historic Site
Amistad National Recreation Area
Andersonville National Historic Site
Aniakchak National Monument & Preserve
Antietam National Battlefield
Apostle Islands National Lakeshore
Appalachian National Scenic Trail
Appomattox Court House National Historical Park
Arches National Park
Arkansas Post National Memorial
Arlington House, The Robert E. Lee Memorial
Aztec Ruins National Monument
Badlands National Park
Baltimore-Washington Parkway
Benjamin Franklin National Memorial
Bent's Old Fort National Historic Site
Bering Land Bridge National Preserve
Big Bend National Park
Big Cypress National Preserve
Big Hole National Battlefield
Bighorn Canyon National Recreation Area
Big South Fork National River & Recreation Area
Big Thicket National Preserve
Biscayne National Park
Black Canyon Of The Gunnison National Park
Bluestone National Scenic River
Booker T Washington National Monument
Boston National Historical Park
Boston Harbor Islands National Recreation Area
Bryce Canyon National Park
Buck Island Reef National Monument
Buffalo National River
Cabrillo National Monument
Canaveral National Seashore
Cane River Creole National Historical Park
Canyon De Chelly National Monument
Canyonlands National Park
Cape Cod National Seashore
Cape Krusenstern National Monument
Cape Lookout National Seashore
Capitol Reef National Park
Capulin Volcano National Monument
Carl Sandburg Home National Historic Site
Carlsbad Caverns National Park
Carter G. Woodson Home National Historic Site
Casa Grande Ruins National Monument
Castillo De San Marcos National Monument
Cedar Breaks National Monument
Cedar Creek & Belle Grove National Historical Park
Central High School National Historic Site
Chaco Culture National Historical Park
Chamizal National Memorial
Channel Islands National Park
Charles Pinckney National Historic Site
Chattahoochee River National Recreation Area
Chesapeaker & Ohio Canal National Historical Park
Chickamauga & Chattanooga National Military Park
Chickasaw National Recreation Area
Chimney Rock National Historic Site
Chiricahua National Monument
City of Rocks National Reserve
Colonial National Historical Park
Colorado National Monument
Congaree National Park
Constitution Gardens
Coronado National Memorial
Cowpens National Battlefield
Crater Lake National Park
Craters of The Moon National Monument & Preserve
Cumberland Gap National Historical Park
Cumberland Island National Seashore
Curecanti National Recreation Area
Cuyahoga Valley National Park
Dayton Aviation Heritage National Historical Park
Delaware Water Gap National Recreation Area
Denali National Park & Preserve
De Soto National Memorial
Devils Postpile National Monument
Devils Tower National Monument
Dinosaur National Monument
Dry Tortugas National Park
Ebey's Landing National Historical Reserve
Effigy Mounds National Monument
Eisenhower National Historic Site
Eleanor Roosevelt National Historic Site
El Malpais National Monument
El Morro National Monument
Eugene O'Neill National Historic Site
Everglades National Park
Fire Island National Seashore
Flight 93 National Memorial
Florissant Fossil Beds National Monument
Ford's Theatre National Historic Site
Fort Bowie National Historic Site
Fort Caroline National Memorial
Fort Davis National Historic Site
Fort Donelson National Battlefield
Fort Frederica National Monument
Fort Laramie National Historic Site
Fort Larned National Historic Site
Fort Matanzas National Monument
Fort Necessity National Battlefield
Fort Pulaski National Monument
Fort Raleigh National Historic Site
Fort Scott National Historic Site
Fort Smith National Historic Site
Fort Sumter National Monument
Fort Union National Monument
Fort Union Trading Post National Historic Site
Fort Vancouver National Historic Site
Fort Washington Park
Fossil Butte National Monument
Franklin Delano Roosevelt Memorial
Frederick Douglass National Historic Site
Fredericksburg & Spotsylvania National Military Park
Friendship Hill National Historic Site
Gates Of The Arctic National Park & Preserve
Gauley River National Recreation Area
George Rogers Clark National Historical Park
George Washington Memorial Parkway
George Washington Birthplace National Monument
George Washington Carver National Monument
Gettysburg National Military Park
Gila Cliff Dwellings National Monument
Glacier National Park
Glacier Bay National Park & Preserve
Golden Gate National Recreation Area
Golden Spike National Historic Site
Grand Portage National Monument
Grand Teton National Park
Grant-Kohrs Ranch National Historic Site
Great Basin National Park
Great Sand Dunes National Park & Preserve
Greenbelt Park
Green Springs National Historic Landmark District
Guadalupe Mountains National Park
Guilford Courthouse National Military Park
Gulf Islands National Seashore
Hagerman Fossil Beds National Monument
Harpers Ferry National Historical Park
Hawaii Volcanoes National Park
Herbert Hoover National Historic Site
Hohokam Pima National Monument
Home Of Franklin D Roosevelt National Historic Site
Homestead National Monument of America
Hopewell Culture National Historical Park
Hopewell Furnace National Historic Site
Horseshoe Bend National Military Park
Hot Springs National Park
Hovenweep National Monument
Hubbell Trading Post National Historic Site
Independence National Historical Park
Indiana Dunes National Lakeshore
International Peace Garden Memorial
Isle Royale National Park
Jean Lafitte National Historical Park and Preserve
Jewel Cave National Monument
Jimmy Carter National Historic Site
John Day Fossil Beds National Monument
John D Rockefeller Jr Memorial Parkway
John Muir National Historic Site
Johnstown Flood National Memorial
Joshua Tree National Park
Kalaupapa National Historical Park
Kaloko-Honokohau National Historical Park
Katmai National Park & Preserve
Kenai Fjords National Park 
Kennesaw Mountain National Battlefield Park
Keweenaw National Historical Park
Kings Canyon National Park
Kings Mountain National Military Park
Klondike Gold Rush National Historical Park
Knife River Indian Villages National Historic Site
Kobuk Valley National Park
Lake Chelan National Recreation Area
Lake Clark National Park & Preserve
Lake Meredith National Recreation Area
Lake Roosevelt National Recreation Area
Lassen Volcanic National Park
Lava Beds National Monument
Lewis and Clark National Historical Park
Lincoln Memorial
Lincoln Boyhood National Memorial
Lincoln Home National Historic Site
Little Bighorn Battlefield National Monument
Little River Canyon National Preserve
Lowell National Historical Park
Lyndon Baines Johnson Memorial Grove on the Patomac National Memorial
Lyndon B Johnson National Historical Park
Mammoth Cave National Park
Manassas National Battlefield Park
Manzanar National Historic Site
Marsh - Billings - Rockefeller National Historical Park
Martin Luther King Jr National Historic Site
Martin Van Buren National Historic Site
McLoughlin House
Mesa Verde National Park
Minidoka National Historic Site
Minute Man National Historical Park
Minuteman Missile National Historic Site
Mississippi National River & Recreation Area
Missouri National Recreational River
Mojave National Preserve
Monocacy National Battlefield
Montezuma Castle National Monument
Moores Creek National Battlefield
Morristown National Historical Park
Mount Rushmore National Memorial
Natchez National Historical Park
Natchez Trace Parkway
National Park of American Samoa
Natural Bridges National Monument
Navajo National Monument
New River Gorge National River
Nez Perce National Historical Park
Ninety Six National Historic Site
Niobrara National Scenic River
Noatak National Preserve
North Cascades National Park
Ocmulgee National Monument
Olympic National Park
Oregon Caves National Monument
Organ Pipe Cactus National Monument
Ozark National Scenic Riverways
Padre Island National Seashore
Palo Alto Battlefield National Historical Park
Pea Ridge National Military Park
Pecos National Historical Park
Pennsylvania Avenue National Historic Site
Perry's Victory & International Peace Memorial
Petersburg National Battlefield
Petrified Forest National Park
Petroglyph National Monument
Pictured Rocks National Lakeshore
Pipe Spring National Monument
Pipestone National Monument
Piscataway Park
Point Reyes National Seashore
Poverty Point National Monument
President's Park (White House)
President William Jefferson Clinton Birthplace Home
Presidio of San Francisco
Pu`uhonua O Honaunau National Historical Park
Puukohola Heiau National Historic Site
Rainbow Bridge National Monument
Redwood National and State Parks
Rock Creek Park
Rocky Mountain National Park
Rosie the Riveter WWII Home Front National Historical Park
Ross Lake National Recreation Area
Russell Cave National Monument
Sagamore Hill National Historic Site
Saguaro National Park
Saint Croix National Scenic River
Saint-Gaudens National Historic Site
Salinas Pueblo Missions National Monument
Salt River Bay National Historic Park and Ecological Preserve
Sand Creek Massacre National Historic Site
San Francisco Maritime National Historical Park
San Juan National Historic Site
San Juan Island National Historical Park
Saratoga National Historical Park
Scotts Bluff National Monument
Sequoia National Park
Shiloh National Military Park
Sitka National Historical Park
Sleeping Bear Dunes National Lakeshore
Springfield Armory National Historic Site
Steamtown National Historic Site
Stones River National Battlefield
Sunset Crater Volcano National Monument
Tallgrass Prairie National Preserve
Theodore Roosevelt National Park
Theodore Roosevelt Island
Thomas Edison National Historical Park
Thomas Stone National Historic Site
Timpanogos Cave National Monument
Timucuan Ecological & Historic Preserve
Tonto National Monument
Tumacácori National Historical Park
Tuskegee Airmen National Historic Site
Tuskegee Institute National Historic Site
Tuzigoot National Monument
Upper Delaware Scenic & Recreational River
Valley Forge National Historical Park
Vicksburg National Military Park
Vietnam Veterans Memorial
Virgin Islands National Park
Virgin Islands Coral Reef National Monument
Voyageurs National Park
Walnut Canyon National Monument
Washington Monument
Washita Battlefield National Historic Site
Whiskeytown National Recreation Area
White Sands National Monument
Whitman Mission National Historic Site
Wilson's Creek National Battlefield
Wolf Trap National Park for the Performing Arts
Wrangell - St Elias National Park & Preserve
Wright Brothers National Memorial
Wupatki National Monument
Yellowstone National Park
Yosemite National Park
Yucca House National Monument National Monument
Yukon - Charley Rivers National Preserve
Zion National Park

**Land Resources Division (57):**
American Memorial Park
Andrew Johnson National Historic Site
Assateague Island National Seashore
Boston African American National Historic Site
Brices Cross Roads National Battlefield Site
Brown v. Board of Education National Historic Site
Capitol Hill Parks
Castle Clinton National Monument
César E. Chávez National Monument
Charles Young Buffalo Soldiers National Monument
Christiansted National Historic Site
Clara Barton National Historic Site
Edgar Allan Poe National Historic Site
Federal Hall National Memorial
First Ladies National Historic Site
First State National Historic Park
Fort McHenry National Monument and Historic Shrine
Fort Stanwix National Monument
Frederick Law Olmsted National Historic Site
Fredericksburg National Military Park
Governors Island National Monument
Hamilton Grange National Memorial
Hampton National Historic Site
Harry S Truman National Historic Site
Honouliuli National Monument
James A Garfield National Historic Site
Jefferson National Expansion Memorial
John Fitzgerald Kennedy National Historic Site
John F. Kennedy Center for the Performing Arts
Longfellow House Washington's Headquarters National Historic Site
Lower Saint Croix National Scenic Riverway
Martin Luther King, Jr. Memorial
Mary McLeod Bethune Council House National Historic Site
Muir Woods National Monument
Nicodemus National Historic Site
Obed Wild & Scenic River
Port Chicago Naval Magazine National Memorial
Pullman National Monument
Rio Grande Wild & Scenic River
River Raisin National Battlefield
Roger Williams National Memorial
Saint Paul's Church National Historic Site
Salem Maritime National Historic Site
Santa Monica Mountains National Recreation Area
Sewall-Belmont House National Historic Site
Thaddeus Kosciuszko National Memorial
Theodore Roosevelt Inaugural National Historic Site
Tule Springs Fossil Beds National Monument
Tupelo National Battlefield
Ulysses S Grant National Historic Site
Vanderbilt Mansion National Historic Site
War In The Pacific National Historical Park
Weir Farm National Historic Site
William Howard Taft National Historic Site
Wind Cave National Park
Women's Rights National Historical Park
World War II Valor in the Pacific National Monument

**None (4):**
Paterson Great Falls National Historical Park
Alcatraz Island
Great Egg Harbor River
Ellis Island

**Comment by chadlawlis** [comment]
Tracking:
- GitHub ([open](https://github.com/nationalparkservice/places-data/labels/places-boundaries) and [closed](https://github.com/nationalparkservice/places-data/issues?q=label%3Aplaces-boundaries+is%3Aclosed))
- [Tracking Boundary Updates](https://docs.google.com/spreadsheets/d/1eGirQYk7N5QIXlkh5_lmrSy_4uuRLQYT30OSflGNaiI/edit#gid=0&vpid=A1) spreadsheet

Data sources:
- Geometries + labels: `places_boundaries` table
- Search/landing zooms + public download: CartoDB [`parks`](https://nationalparkservice.cartodb.com/u/nps/tables/parks)

**Comment by nateirwin** [comment]
I think we really need to go through the 311 WSD_Parks boundaries and compare them to the boundaries coming in from Lands. If the boundaries are the same, we should switch back to pulling from Lands.

Thoughts? Perhaps we can split this task up between the team so we can get through it faster?

**Comment by chadlawlis** [comment]
@nateirwin ya, I was thinking the same thing. I was also looking to get some context from you and @jimmyrocks as to why we originally pulled from WSD_Parks for so many units, instead of Lands - if these are all customized boundaries directly from the units or if this is a combination of Lands boundaries and custom unit boundaries, etc. I understand that the data source was aggregated for the state pages for WSD, but that's extent of the context I have around it (I'd like to provide context for this in our documentation).

**Comment by chadlawlis** [comment]
We could use `ST_Equals`(PostGIS) as a start to identify identical geometries between WSD_Parks and Lands, we would just need to load all WSD_Parks and all Lands boundaries into one database. I'm happy to take that on as a first step.

**Comment by nateirwin** [comment]
Not sure that I can answer your question about why so many of the park boundaries were labeled "WSD_Parks". I believe it might be because we just assumed that if a park had a boundary in that dataset we should use it over Lands. But my hunch is that most of the WSD_Parks boundaries are actually Lands boundaries, and it would be good to switch the source back to Lands, where possible.

**Comment by nateirwin** [comment]
I think the `ST_Equals` idea is a good one. I'd say go with it!

**Comment by chadlawlis** [comment]
Chances are not many geometries will be identical, though using a buffer or other acceptable difference is dangerous (could be projection issue, could be one small parcel change that's important, etc). So, I'll start with this `ST_Equals` comparison as a first step then these will have to be manually reviewed, most easily in CartoDB overlaying the two sources in map view.

**Comment by chadlawlis** [comment]
I'd like to create a Boundaries page on insidemaps to house this documentation, acting as both a documentation of process and somewhat of a disclaimer.

I would also like to include a dynamic table, like we have for Places data:

![places insidemaps 2015-12-16 16-46-10](https://cloud.githubusercontent.com/assets/1238636/11857353/b1b9d7ea-a414-11e5-852f-8aea845745fa.jpg)

At the very least I would like this table to track the number of units under each data source, and taking that one step further it would enable you to select a unit from the dropdown list to download the geometry currently in Places.

**Comment by nateirwin** [comment]
This is a great idea. It should be easy to implement once our new CartoDB table(s) are in place.

**Comment by chadlawlis** [comment]
Great. We might as well create the table using the current CartoDB `park` table, which will be replaced by the current `parks_temp` table once we are ready to make the transition (the underlying query to the table should remain the same).

**Comment by chadlawlis** [comment]
Being developed here https://github.com/nationalparkservice/insidemaps/tree/boundaries-doc.

**Comment by chadlawlis** [comment]
Remaining to-do:
- [ ] Transition WSD_Parks to Lands or park/region `data_source` (https://github.com/nationalparkservice/places-data/issues/348)
- [ ] Add boundary download field to Places landing page dynamic table on insidemaps(https://github.com/nationalparkservice/insidemaps/issues/70)
- [x] Add step by step language of ideal boundary update process including Lands and parks/regions
- [x] Add language about using the park preferred unit code

**Comment by chadlawlis** [comment]
The `boundaries-doc` branch was deleted, given how outdated it was compared with `master`, and a new branch was created for further development here: https://github.com/nationalparkservice/insidemaps/tree/boundaries-doc-new.

An initial pull request has been made here: https://github.com/nationalparkservice/insidemaps/pull/69. This is still a work in progress, not to be disseminated beyond preparation for the call with Lands tomorrow. Specific examples still need to be added to highlight particular differences between Lands and Park/Region-approved alternative sources that warrant their use.

**Comment by chadlawlis** [comment]
First draft of the doc is live here: http://insidemaps.nps.gov/places/boundaries/.

A separate issue has been created for the download table: https://github.com/nationalparkservice/insidemaps/issues/70. Transitioning from WSD_Parks to Lands is already separated out into #348. 

Tracking these separately, good to close out here.
