### ISSUE TITLE
Populate cartography fields for new unit WACO

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#288]
A boundary for the new unit WACO was just added to places_boundaries: https://github.com/nationalparkservice/places-data/issues/168.

@mtaylorlong, can you populate the cartography fields for this? These include:
- `unit_rank`
- `unit_urban`
- `ldir`
- `min_zoom_poly`
- `min_zoom_border`
- `min_zoom_tint_band`
- `min_zoom_label`
- `min_zoom_label_long`
- `min_zoom_label_center`
- `ldir_enforce`
- `min_zoom_simp`
- `max_zoom_label`

**Comment by mtaylorlong** [comment]
Done.
