### ISSUE TITLE
NEPE Nez Perce National Historical Park boundary shift

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#29]
Hey all, just a heads up that the Nez Perce National Historic Park units (there are more than 1) are all shifted about 100 meters west.  Thanks!

**Comment by nateirwin** [comment]
We'll take a look at this issue next week too.

**Comment by mtaylorlong** [comment]
@cwlawlis802: Will you revisit this issue to double check that we have good boundaries for Nez Perce? This is one that I need to move the labeling point for.

Also, would you mind setting it's `ldir_enforce` to `true`? Just noticed it has a double label in PT3.

**Comment by chadlawlis** [comment]
These boundaries are identical to the latest Lands release - @heidiogle please send along screenshots/updated source if you're still seeing an issue here.

`ldir_enforce` has been set to `true` and `data_source` to `Land Resources Division` (previously `WSD_Parks`).

**Comment by heidiogle** [comment]
This issue is now 9 months old so things may have changed since I first brought this up but here's a screen capture of one of the units along the Snake River.  It seems pretty evident to me that there is a boundary shift here.  I overlaid the Lands dataset @cwlawlis802 and yes, the error appears to be coming from that dataset.  So, I guess this is now an issue for Lands.  That said, Nez Perce isn't an IMR park (even though some of the units are in IMR) so I'll give PWR a heads up so they can follow up.
![capture](https://cloud.githubusercontent.com/assets/11545684/12369463/cd348c60-bbb4-11e5-901c-411e514a35e1.JPG)

**Comment by chadlawlis** [comment]
Agreed on the boundary shift there, thanks for flagging.

Let us know if you ping PWR, otherwise we will. Hopefully the park/region has something with better alignment, otherwise we'll have to stick with Lands.

**Comment by heidiogle** [comment]
I pinged Sandy at PWR.  Hopefully Roger knows about the issue and has plans to fix it in his Lands update.

**Comment by chadlawlis** [comment]
Thanks @heidiogle.

**Comment by heidiogle** [comment]
FYI - This issue is being addressed by the Lands team in the FY16 work plan.  Roger is hoping to have it fixed in the March 2016 release.

**Comment by chadlawlis** [comment]
Sounds good, thanks!

**Comment by chadlawlis** [comment]
Closing - this will be updated automatically once Lands addresses it, given `data_source = Land Resources Division'` in places_boundaries parks.
