### ISSUE TITLE
Populate "subunit_of" field in places_boundaries "parks" table

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#291]
- GOGA
- NPNH
- ...

Populate this table as we go: 

| unit_code | subunit_of |
| --- | --- |
| sequ | seki |
| kica | seki |

**Comment by chadlawlis** [comment]
cc @mtaylorlong @jakecoolidge @nateirwin as you think of these larger units containing smaller ones please add them as comments below so we populate a comprehensive list.

**Comment by jakecoolidge** [comment]
NCR parks--but as we know, this is really messy right now. I'm adding it just to keep it on our radar.
NAMA appears to include LINC, COGA, WAMO, VIVE, NWWM, KOWA, among others.
Hopefully some data coming to us from NCR will help dispel some of the confusion.

**Comment by mtaylorlong** [comment]
SEKI may fall into this category also. Even though Sequoia & Kings Canyon are merged as a unit, they still show two separate units with separate labels on the HFC map (and currently, we show the units separately also).

**Comment by chadlawlis** [comment]
For GOGA, we currently have individual unit geometries for these "subunits":
- PRSF (though this boundary is not rendered in Park Tiles)
- FOPO
- SAFR
- MUWO

ALCA should also be included in this - it is included in our current GOGA geometry, but does not have a standalone unit geometry.

I am in touch with the GIS Specialist @ GOGA to confirm this list and correct the geometries.

See also this issue https://github.com/nationalparkservice/places-data/issues/240 for reference.

**Comment by chadlawlis** [comment]
FRED might be considered a subunit of FRSP. Originally from https://github.com/nationalparkservice/places-data/issues/324.

**Comment by mtaylorlong** [comment]
If we do get the go-ahead to make FRED a subunit of FRSP, then SPOT should be a subunit of FRSP as well. Both FRED and SPOT are the old unit codes that merged. Again, this would be analogous to SEQU and KING becoming SEKI, but us still maintaining separated geometries for SEQU and KING in addition to the master boundary for SEKI.

**Comment by nateirwin** [comment]
How is this looking right now? I'm working on the HFC park map viewer, and it looks like SEKI still doesn't have a record in our parks table. Is there a table currently available on CartoDB that allows me to make the SEQU/KICA -> SEKI translation?

**Comment by chadlawlis** [comment]
This field has not yet been populated in the PostGIS parks table and is not available in CartoDB. I can add this field directly into CartoDB for now, for an interim solution for SEKI and any other parks you come across for the HFC viewer, but this is not something that has been established across all NPS units. Writing the PostGIS table out to CartoDB also appears to be experiencing issues (cc @jimmyrocks).

The idea is to house this field in the parks table itself, not a standalone table like `alternate_unit_codes`.

**Comment by mtaylorlong** [comment]
Really, all we need is to add a record for SEKI in our Parks table, then create a multi-polygon for it's boundary using both the SEQU and KING boundaries. Once that's pushed to the new CartoDB table, you should be good to go.

I agree that setting up the alternate unit codes info is still a good idea, but I don't think it's intended to address issues like this one.

**Comment by chadlawlis** [comment]
SEKI has been added as union of SEQU and KICA `WSD_Parks` geometries.

**Comment by chadlawlis** [comment]
Closing this and opening individual `subunit_of` issues per region, as they arise.

**Comment by jimmyrocks** [comment]
The boundaries were just updated last night? Should I run it again tonight
to capture these changes?

**Comment by chadlawlis** [comment]
Thanks @jimmyrocks but let's wait until later this week - I'll ping you when appropriate.
