### ISSUE TITLE
Add preset "Athletic Field"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#297]
http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpitch

Urban parks in particular need baseball fields, tennis courts, etc. 

GOGA is a good example, e.g. http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=19.49/-122.47419/37.80311.

**Comment by chadlawlis** [comment]
"Athletic Field"

**Comment by chadlawlis** [comment]
Added as `{"leisure":"pitch"}` as point and area. Land Recreation > Sports Field > Athletic Field.

"Sports Field" class to include more types down the road, per sport (baseball field, basketball court, tennis court, etc).

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
@jimmyrocks we were under the impression this had been added back in December - can we get this preset into Editor? We need it for the GOGA app, among others.

**Comment by jimmyrocks** [comment]
It looks like it was added on Dec 14. https://github.com/nationalparkservice/places-data/blob/gh-pages/data/presets/point/land_recreation/sports_field/athletic_field.json

I wonder if this is a bug with using the same class and superclass for points and polygons. I'll have to look into it deeper.

**Comment by chadlawlis** [comment]
This is now live.

**Comment by chadlawlis** [comment]
@jimmyrocks the area for this is functional, but the point does not seem to show up in Editor.

Reopening. Could be the bug you mentioned with presets using the same class and superclass for points and polygons?

**Comment by chadlawlis** [comment]
All set here - regenerated the presets and both the point and the area are now live in Editor.
