### ISSUE TITLE
Populate cartography fields for JAZZ

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#298]
A boundary for JAZZ was just added to places_boundaries: https://github.com/nationalparkservice/places-data/issues/293.

@mtaylorlong, can you populate the cartography fields for this? These include:
- `unit_rank`
- `unit_urban`
- `ldir`
- `min_zoom_poly`
- `min_zoom_border`
- `min_zoom_tint_band`
- `min_zoom_label`
- `min_zoom_label_long`
- `min_zoom_label_center`
- `ldir_enforce`
- `min_zoom_simp`
- `max_zoom_label`

**Comment by mtaylorlong** [comment]
Done. Updated all necessary fields for rendering in boundaries vector tiles and added region code, state, and website.
