### ISSUE TITLE
MLKM has no label

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#302]
http://insidemaps.nps.gov/park-tiles-3/#17/38.88613/-77.04498.

This is not associated with a unit designation in `places_boundaries` either - do we want to append "National Memorial" to this given the website? http://www.nps.gov/mlkm/index.htm

cc @mtaylorlong

**Comment by mtaylorlong** [comment]
Fixed this by updating it's min_zoom settings in the parks table.
![screen shot 2016-01-15 at 3 16 37 pm](https://cloud.githubusercontent.com/assets/4741443/12366847/090f672e-bb9b-11e5-91d8-7cd900d103f1.png)

**Comment by chadlawlis** [comment]
:+1:
