### ISSUE TITLE
Add tag for camping anchorage

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#31]
We have two sites marked as campgrounds situated in the midst of Yellowstone Lake, just off shore from Frank Island. They are campsites, sort of, but the idea is that campers will be camping overnight in their boat--no overnight camping is allowed on Frank Island. 

Is there a tag we could add that might allow us to symbolize these sites as anchorages instead of campgrounds? For more about this specific camping use case, see page 9 of the Yellowstone camping guide: http://www.nps.gov/yell/planyourvisit/upload/bctrip-planner_2012.pdf

Right now it looks odd to me to have the tent icon for a campground out over open water.

**Comment by chadlawlis** [comment]
We could use [`mooring=guest`](http://wiki.openstreetmap.org/wiki/Key:mooring)? Anchoring is different from using a mooring but it might fit our use case here. Another option is [`seamark:type=anchorage`](http://wiki.openstreetmap.org/wiki/OpenSeaMap/Anchorages).

Thoughts @jimmyrocks @nateirwin?

**Comment by nateirwin** [comment]
I know we have moorings in some parks, so my gut would be to go with `seamark:type=anchorage`. I doubt we have too many of these in our parks, though ;-)

**Comment by chadlawlis** [comment]
Water Recreation > Boat > "Anchorage"

Tag: `{"seamark:type":"anchorage"}`
