### ISSUE TITLE
PWR Data Seed: PINN Roads, Trails, Buildings

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#312]
Sandy from PWR requested that we seed the following data for Pinnacles using her published services:
- Roads
- Trails
- Buildings (from facilities)

Feature Server: [http://inppwcagis01:6080/arcgis/rest/services/PWR](http://inppwcagis01:6080/arcgis/rest/services/PWR)

**Comment by jakecoolidge** [comment]
Closing, see [this issue](https://github.com/nationalparkservice/places-data/issues/790).

**Comment by chadlawlis** [comment]
Thanks @jakecoolidge.
