### ISSUE TITLE
Create new `parks_temp` CartoDB boundaries table

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#315]
This new table will be populated by our `parks` table in the `places_boundaries` database (what we're referring to as the "PostGIS Parks" table, the other the "CartoDB Parks" table). Ultimately, the goal for this table is to replace the existing CartoDB Parks table for use in NPS products (apps, maps) and potentially for use as a cartographic table for public consumption.

Fields:
- `cartodb_id` (automatically generated by CartoDB)
- `the_geom`
- `area` (area in web mercator square meters)
- `latitude` (latitude of `the_geom` centroid)
- `longitude` (longitude of `the_geom` centroid)
- `designation` (park designation fully spelled out)
- `display_name` (park name with abbreviated designation)
- `full_name` (park name with fully spelled out designation)
- `state`
- `unit_code`
- `subunit_of`
- `region`
- `url` (we'll need to check these for parks with alternate unit codes)
- `created_at` (automatically generated by CartoDB)
- `updated_at` (automatically generated by CartoDB)

**Comment by chadlawlis** [comment]
@mtaylorlong @jimmyrocks let me know if this lines up with what we discussed, if so I'll go get started populating it from the PostGIS Parks table.

**Comment by nateirwin** [comment]
We have another table we are using to track which parks are locked in Places. That table also has the contact email address for whomever "locked" a park (right now, just regional email addresses, but could in the future be a local park contact).

I think we want to continue keeping that information separate from this core parks table.

**Comment by nateirwin** [comment]
I also think we should add `created_by` and `updated_by` columns. This is kind of a standard for everything we do in CartoDB.

**Comment by chadlawlis** [comment]
@nateirwin re: https://github.com/nationalparkservice/places-data/issues/315#issuecomment-163366452, @jimmyrocks said he is using the `places_lock` field in the current CartoDB Parks table, which is why we decided to maintain it. Is there another table this should be pulled from instead?

Re: https://github.com/nationalparkservice/places-data/issues/315#issuecomment-163366653, all of these fields will be populated by the PostGIS Parks table, so we will have to add these in there too. @jimmyrocks we'll need a way to make this automatic, like we are planning to do with `date_created` and `last_updated` in the PostGIS parks table.

**Comment by nateirwin** [comment]
@jimmyrocks: I thought you had switched over to pulling from the new table I created for this (as we discussed)? Here's the new table: `nps.parks_places_status`.

**Comment by jimmyrocks** [comment]
Nate, you're right, we did move that over… sorry to hold things up over
this!

**Comment by chadlawlis** [comment]
No worries @jimmyrocks, removing from list now.

**Comment by chadlawlis** [comment]
This is live here: https://nationalparkservice.cartodb.com/u/nps/tables/parks_temp.

The sync script is on the .191 server in /home/jim/dev/scratch.

**Comment by chadlawlis** [comment]
This table is live and the sync tool is in development.

Closing out now, but noting that we will rename this to replace the existing CartoDB `parks` table once sync is functional. At that point we will rename the current `parks` table and maintain only the attribute information that is not housed elsewhere (e.g. `address`, `blurb`, `climate`, etc in the event a service relies on it that we are unaware of).
