### ISSUE TITLE
Maintain antiquated CartoDB `parks` table fields after replacement with `parks_temp` table

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#316]
Related to https://github.com/nationalparkservice/places-data/issues/315, these fields are currently in the CartoDB Parks table, which we would like to remove through the creation of the `parks_temp` table (which will ultimately replace the current CartoDB Parks table). We need to pull an inventory of what, if any, services (apps, maps) are using these fields to understand the impact of their removal:
- `climate` (stagnant/disconnected field; not being updated = not fit for inclusion)
- `blurb` (stagnant/disconnected field; not being updated = not fit for inclusion)
- `address` (stagnant/disconnected field; not being updated = not fit for inclusion)
- `phone` (stagnant/disconnected field; not being updated = not fit for inclusion)
- `visitors` (stagnant/disconnected field, also no longer in use = not fit for inclusion. Possibly fit for inclusion in PostGIS table down the road, once/if park hierarchy calculations return)
- `poly_source` (no need for this in the CartoDB table, only PostGIS)

**Comment by chadlawlis** [comment]
@mtaylorlong @jimmyrocks confirm that these line up with what we discussed.

@nateirwin let us know what you think. These will remain in the CartoDB Parks table until it is ultimately replaced by the new `parks_temp` table. The thought is that these fields are not pulling from the CMS and/or are no longer in use, so if they are stagnant/antiquated there is no point in maintaining them, especially if this table will be available for public consumption. The unit's `url` will be maintained, for now, which is where most of this attribute information can be found.

**Comment by nateirwin** [comment]
I'd say let's preserve this information, but move it into a separate CartoDB table for now. We've long had plans to write a process for refreshing these fields from Web Services Division. We have never prioritized it, however.

The only maps I can think of that might be pulling from these fields are the state page maps. It should be trivial to migrate them over to point to a new table.

**Comment by chadlawlis** [comment]
@nateirwin we can just continue to maintain this in the current CartoDB parks table, then rename it  and remove the other fields once we are ready for `parks_temp` to replace it.

State page maps still pull from this table?

**Comment by nateirwin** [comment]
Yep, but we could write just a little bit of JavaScript and have the state page maps just pull directly from the page they're embedded on. This is the best solution, and it shouldn't take more than a few hours of dev.

**Comment by chadlawlis** [comment]
Sounds good - so, we'll keep these fields in the current CartoDB parks table until that script has been developed to pull the state page maps from the page they're embedded on. Once complete, we can completely remove the current CartoDB parks table and replace it with the new `parks_temp` table, which does not contain these fields.

**Comment by chadlawlis** [comment]
Done, thanks to @jimmyrocks.

Current `parks` table in CartoDB: https://nationalparkservice.cartodb.com/u/nps/tables/parks

Old table, `parks_20160202` in CartoDB: https://nationalparkservice.cartodb.com/u/nps/tables/parks_20160202, maintaining all attribute data etc.
