### ISSUE TITLE
Add lodging tag for stand-alone cabins?

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#32]
SHEN includes a number of individual cabins; I'm wondering if these should be mapped with a lodging icon/tagged tourism=alpine hut, building=yes?

**Comment by jimmyrocks** [comment]
I would think that build=cabin is the best tag to use
http://wiki.openstreetmap.org/wiki/Tag:building%3Dcabin

what do other people think?

**Comment by jakecoolidge** [comment]
I'm leaning in this direction. Lodges typically have multiple units, either a building with many rooms, or a main building with a grouping of separate cabins (like LeConte in GRSM). We don't mark individual cabins as points of interest in our maps; I wonder if this is something we'd want to look into? 

Also curious to hear what you all think.

**Comment by nateirwin** [comment]
Makes sense to me. If we are going with this, @jakecoolidge, can you work with @cwlawlis802 to get this added to our tagging wiki?

**Comment by chadlawlis** [comment]
This is currently in the wiki as `building=cabin`. I can add `Feat_Type=Backcountry Cabin` to the `GIS Tag` column in the wiki so we know to tag this the same way moving forward. I will also ping Angie to confirm any other variations of cabin in the GIS schema that might warrant a different tag.
