### ISSUE TITLE
Boundary for OBRI not rendering in PT3

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#321]
It renders in Places Editor, this is the view upon landing zoom from the dropdown:

![editor places insidemaps 2015-12-09 13-12-42](https://cloud.githubusercontent.com/assets/1238636/11697401/a51b2c12-9e76-11e5-830a-8b76c4436f43.jpg)

Only a point renders in PT3, this is the view upong landing zoom from the search bar (if you squint you can see "Obed WSR" label on the point, and the boundary does not render at any scale):

![park tiles 3 insidemaps 2015-12-09 13-12-58](https://cloud.githubusercontent.com/assets/1238636/11697421/baec751e-9e76-11e5-9aba-1a32f2774d44.jpg)

cc @mtaylorlong

**Comment by chadlawlis** [comment]
Related: PT3 displays error "There was an error getting the bounds for that park" when selecting "Obed Wild & Scenic River" from the search bar, on the initial try. Hitting return again successfully brings you to the unit zoom.

This may fix itself once the boundaries have been regenerated.

**Comment by mtaylorlong** [comment]
@mtaylorlong will tackle this in the parks database.

**Comment by mtaylorlong** [comment]
I have updated the min_zoom settings for OBED to 14. This should fix these issues.
