### ISSUE TITLE
"National Capital Parks" vs. "National Capital Parks - East"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#322]
Re: https://github.com/nationalparkservice/places-data/issues/245.

There are currently 3 records in our CartoDB parks table like 'national capital parks%' - "National Capital Parks" NACP with no `poly_source`, "National Capital Parks" NACA with `poly_source = npmap placeholder`, and "National Capital Parks - East" NACE with `poly_source = WSD_Parks`.

Both Editor and PT3 pull from both records with a poly_source, so NACA and NACE.

NACE is the only unit code identified by NPS.gov, while NACP and NACA are not.

Only one record is maintained in our PostGIS parks table - `unit_name_long = National Capital`, `unit_desig_full = Parks` and `unit_code = naca`. This is pulling from the NACA record in CartoDB with `poly_source = npmap placeholder`.

We should probably boil this down to one larger unit_code, like for GOGA or NPNH (to be used in the `subunit_of` field), with a master geometry housing all subunits. We should then add the other unit codes to the alternate unit code table, and remove the other records from the CartoDB parks table.

Other NCR issues, for reference:
- https://github.com/nationalparkservice/places-data/issues/87
- https://github.com/nationalparkservice/places-data/issues/279

**Comment by chadlawlis** [comment]
Reach out to Cynthia, GIS Specialist @ NCR, about this.

**Comment by chadlawlis** [comment]
My question to Cynthia on 12/22/15:

> One other question I have for you is unit code/labeling related. There are currently 3 unit codes and associated labels in our boundaries source associated with NCR - "National Capital Parks" NACP, "National Capital Parks" NACA, and "National Capital Parks - East" NACE. Looking at NPS.gov, NACE is the only recognized unit code with its own unit page http://www.nps.gov/nace/index.htm. So, which unit code and associated label do you at NCR identify with? We would like to use only one unit code and label combination, if appropriate/possible.

Her response:

> You ask a very good question about unit codes.  NCR is complicated in that respect.  Here's the short answer.  Use National Capital Parks-East (NACE), National Mall and Memorial (NAMA), or Rock Creek Park (ROCR) in lieu of National Capital Parks (NACP) or National Capital Parks (NACA), depending on where geographically the data is located.  If you look at the boundaries that I just sent, there's no NACA or NACP in the table so hopefully it will be more clear now.
> 
> Many, but not all, of the smaller NPS park units in DC were created by Congress under the name National Capital Parks.  Over time, the administration of the NPS park units in DC shifted and those NACA/NACP are now divided among three administrative units: National Capital Parks-East (NACE), National Mall and Memorial (NAMA), or Rock Creek Park (ROCR).  If you look simply at legislation, NACE and NAMA don't exist and ROCR doesn't managed as much area as is does now.  However, once you get out of the Congressional legislation and land ownership deeds, you are realistically dealing with NACE, NAMA, and ROCR.  So, from a visitor's perspective, please stick with NACE, NAMA, and ROCR, not NACA or NACP.  However, there's a bit more to it.
> 
> Another related issue is that you'll notice both unit code/name and group code/name are in the NCR data.  This is very important because some units within these administrative units are defined individually with their own code and/or name.  These units may have been established individually by legislation or the use of these individual units has become the standard over time.  Some of the units underneath the grouped administrative units have their own website others do not.  Each "group" administrative unit has their own superintendent.  Generally speaking, when we talk about about a "park" in NCR, we're referring to the administrative unit (group code/name).
> 
> While these group codes/names are very important because it tells you who the superintendent is, which resource management division to contact, what website to start from, etc., if you have to choose one, please go with the unit code and/or unit name.  I've gone through the data I provided to try to get the most descriptive name in the unit_name field.  I included names for little squares and circles where I could find the information.  However, if you want to know who administers the land, the group code/name will provide that.
> 
> I know it's a bit confusing, but does this help at all?  I think the Alaska Region also has some similar issues with unit vs group codes and names.

**Comment by mtaylorlong** [comment]
@cwlawlis802: Once you think this is straightened out in the parks table, I'll take another look in PT3.

**Comment by chadlawlis** [comment]
:+1: 

Awaiting a response from Cynthia re: detailed units currently in Places/PT that are missing from her seed. Once I hear back I will implement and we can review all rendering decisions for PT3. Looking forward to crossing this off the list.

**Comment by chadlawlis** [comment]
NACP is an alternate unit code for NACA, while NACA is a legislative unit and not actually used by NCR in practice (NACE, NAMA, and ROCR instead). See #597 for NACA removal issue.

NACE is our way forward. Closing.
