### ISSUE TITLE
Populate cartography fields for THJE

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#323]
A boundary for THJE was just added to the PostGIS parks table: https://github.com/nationalparkservice/places-data/issues/319.

@mtaylorlong, can you populate the cartography fields for this? These include:
- `unit_rank`
- `unit_urban`
- `ldir`
- `min_zoom_poly`
- `min_zoom_border`
- `min_zoom_tint_band`
- `min_zoom_label`
- `min_zoom_label_long`
- `min_zoom_label_center`
- `ldir_enforce`
- `min_zoom_simp`
- `max_zoom_label`

**Comment by jimmyrocks** [comment]
This might be where the old code comes in to calculate these. @mtaylorlong,
assign this to me if you want me to take a look tomorrow morning

**Comment by mtaylorlong** [comment]
Done. I eye-balled it. Should work.
