### ISSUE TITLE
Boundary for FRSP not rendering in PT3

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#324]
Similar to https://github.com/nationalparkservice/places-data/issues/321. 

There have been two boundaries - one for "Fredericksburg & Spotsylvania National Military Park" FRSP (from WSD_Parks) and another for "Fredericksburg" FRED (from Lands) (see https://github.com/nationalparkservice/places-data/issues/318). Both boundaries render in Editor, while only the FRED boundary (small land parcel) renders in PT3. A point and label for each record, however, renders in PT3 - while the labels do not adjust with scale (always using `unit_desig_abbr` of `NMP`).

The FRED (Lands) boundary has been removed from both CartoDB and PostGIS parks tables, so this will resolve itself for Editor once tiles are regenerated. 

We will have to take a look at PT3 once the tiles have been regenerated to see if this resolves the issue there as well.

cc @mtaylorlong

**Comment by mtaylorlong** [comment]
How would y'all feel about considering this a subunit issue? I think it's pretty analogous to SEKI.

This doesn't solve all the other issues mentioned above, but as we clean up the database records, I think it's worth making this change as well. @cwlawlis802: What do you think?

**Comment by chadlawlis** [comment]
@nateirwin should have contact info for the park, so let me reach out before we make any more decisions here. FRED could very well be considered a subunit of FRSP, although it is technically not considered a standalone unit by NPS.gov. I'll add that to the list here https://github.com/nationalparkservice/places-data/issues/291.

**Comment by chadlawlis** [comment]
Related: PT3 displays error "There was an error getting the bounds for that park" when selecting "Fredericksburg & Spotsylvania National Military Park" from the search bar, on the initial try. Hitting return again successfully brings you to the unit zoom.

This may fix itself once the boundaries have been regenerated.

The same issue exists for OBRI: https://github.com/nationalparkservice/places-data/issues/321#issuecomment-163691233.

**Comment by mtaylorlong** [comment]
Sure thing. To me, it comes down to whether or not people still talk about Fredericksburg as one thing and Spotsylvania as another. It's especially helpful to store separate subunits for labeling if they are in separate locations. If we talk to the park, I think it's important to make it clear that our subunit delineations are often made for cartographic reasons alone.

**Comment by chadlawlis** [comment]
Agreed, sounds good - I'll make that clear to the park.

**Comment by mtaylorlong** [comment]
@cwlawlis802: Once this is set up in the parks table the way we want (all properly sub-united), I'll go into Park Tiles 3 and make sure it's rendering properly.

**Comment by mtaylorlong** [comment]
The label "Fredericksburg & Spotsylvania" will display now – I've reset the min_zoom settings to 14. 

We still haven't acted on the subunit issue, so I'll keep this issue open but push it to 3.0.2. I'm assigning it to @cwlawlis802 to take it up once we hear back from the park.

**Comment by nateirwin** [comment]
In case this info is helpful: FRSP's boundary is still not rendering in the latest PT3.

**Comment by mtaylorlong** [comment]
I'm closing this one because the boundary and label are now appearing in PT3. However, we still need to fix the labeling for this park, but that's a separate issue.
