### ISSUE TITLE
represent POIs on Park Tiles 3 with generic symbol?

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#327]
Eric at IMR had an idea that will aid their review of Park Tiles 3: the ability to see those points of interest that are not one of the core categories with a generic symbol. Perhaps they are not visible at zooms lower than 15 (?) to alleviate visual clutter.

**Comment by nateirwin** [comment]
We could actually just bring these points in as a GeoJSON overlay. That way, they could easily be toggled on and off, and I feel like it would make it clear that they are not part of PT3 itself.

**Comment by mtaylorlong** [comment]
We've decided to remove POI's entirely from Park Tiles, and instead offer a more customizable POI vector overlay solution. See issues #381 and #380.
