### ISSUE TITLE
Add preset "Webcam"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#328]
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance

**Comment by chadlawlis** [comment]
Added "Webcam" as `{"man_made":"surveillance"}`. Service > Surveillance > Webcam.

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
The preset is now live, but it's associated with the wrong symbol:

<img width="357" alt="editor places insidemaps 2016-02-18 13-41-55" src="https://cloud.githubusercontent.com/assets/1238636/13157815/2ff8b068-d647-11e5-8073-b1303a300763.png">

**Comment by chadlawlis** [comment]
Presets were regenerated again today but the same symbol issue persists.

Closing this out and tracking symbol issue here https://github.com/nationalparkservice/places-editor/issues/111.
