### ISSUE TITLE
Add preset "Fumarole"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#329]
Holes in the ground that blow steam, but water never comes out of them.

Some are well established and named in YELL.

**Comment by chadlawlis** [comment]
Added "Fumarole" as `{"natural":"fumarole"}`. Natural Feature > Thermal > Fumarole.

Presets to be regenerated early next week, this should be available after that.

**Comment by chadlawlis** [comment]
Currently varying proposed tags in OSM:

`{"natural":"fumarole"}`: http://wiki.openstreetmap.org/wiki/Proposed_features/fumarole

`{"geological":"volcanic_fumarole"}`: http://wiki.openstreetmap.org/wiki/Proposed_features/Volcanic_features#Fumaroles

Going with the former to stay consistent with how we've been tagging thermal features thus far.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
This is now live.
