### ISSUE TITLE
BLCA/CURE boundary shift

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#33]
Hey guys, found another boundary shift for BLCA and CURE.  See below.  Thanks, H

![capture](https://cloud.githubusercontent.com/assets/11545684/7497265/9afc8d2a-f3d6-11e4-8103-9f0fff84fd3f.JPG)

![capture1](https://cloud.githubusercontent.com/assets/11545684/7497296/bf3c1c28-f3d6-11e4-8271-6d1db7ec78f7.JPG)

**Comment by nateirwin** [comment]
Thanks for letting us know about this, @heidiogle! We are going to sit down sometime next week to discuss how we can improve/streamline our boundary update process. We'll take a look at this then.

**Comment by jimmyrocks** [comment]
@heidiogle 
![image](https://cloud.githubusercontent.com/assets/98192/9481871/6a8b3c1e-4b4b-11e5-8e4d-76d9b7a7ae15.png)
Our current boundary is in Light Blue
The Boundary from the (Lands Dataset / IRMA / Roger) is in Red
Where they both overlap is a purple color

The Lands boundary for CURE fixes the strange border with BLCA, but it is also missing parts of the park that we currently include.

Would it be ok for us to move forward with the Lands boundary, or do you have an even better boundary that we can use?

Our BLCA dataset is identical to what is currently in Lands

**Comment by heidiogle** [comment]
Hey guys!  Please use the Lands boundary, always.  The Lands dataset is the legislative boundary for the parks, is the authoritative NPS boundary dataset and is what is publicly available now.  Where there are inaccuracies with the legislative boundary, Roger is aware of and is working on them.  Lands is the official repository for all legislative boundaries so if a park has a problem with a legislative boundary, they should consult with Roger and he can make the changes, then you guys would reflect that change once Roger updates the Lands dataset, which he does monthly.  Many parks will want to see their management boundaries though so figuring out how to render both the legislative boundary and the management boundary is something that will need to be addressed, hopefully before the Jan 1 release.  Management boundaries shouldn't replace legislative boundaries though, only be an additional rendering.  How that is rendered is where you guys can make your magic.

**Comment by jimmyrocks** [comment]
Thanks for your quick response, I will be using the Lands boundary for this tonight!

**Comment by nateirwin** [comment]
Whoa, y'all. While Lands is the official source for legislative boundaries, we accept boundaries from parks if they fe their boundary better represents the park.

@jimmyrocks: Leave this one as is for now. If it is in our dataset, we likely got it directly from the park. We should do more digging before changing.

**Comment by chadlawlis** [comment]
Both BLCA and CURE came directly from the parks, so we will maintain these boundaries for now. If the parks have new boundaries for us to use, or would like us to adopt the latest Land Resources Division boundary, we will do so.

Closing out.
