### ISSUE TITLE
Add preset "Hot Spring"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#330]

**Comment by chadlawlis** [comment]
Currently a proposed feature in OSM: http://wiki.openstreetmap.org/wiki/Proposed_features/Hot_Spring.

**Comment by chadlawlis** [comment]
Added "Hot Spring" as `{"natural":"hot_spring:}`. Natural Feature > Thermal > Hot Spring.

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
This is now live.
