### ISSUE TITLE
Add preset "Natural Feature" 

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#331]
`{"natural":"*}`

**Comment by chadlawlis** [comment]
Added "Natural Feature" as `{"natural":"*"}`. Natural Feature > Natural Feature > Natural Feature.

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
This is now live.

Looks like we would still like to add this as an area, tracking here: https://github.com/nationalparkservice/places-data/issues/340.
