### ISSUE TITLE
Add preset "Bookstore"

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#332]
`{"shop":"books"}`

**Comment by chadlawlis** [comment]
Added "Bookstore" as `{"shop":"books"}`. Service > Shopping > Bookstore.

Presets to be regenerated early next week, this should be available after that.

**Comment by nateirwin** [comment]
Cc/ @asouthwould

**Comment by chadlawlis** [comment]
This is now live.
