### ISSUE TITLE
Mismatches between HFC park maps list and our parks table

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#334]
HFC has maps for the following unit_codes, but they are missing from our CartoDB parks table:

unit_code,url,full_name
'alas', ,
'aleu', http://www.nps.gov/aleu, Aleutian World War II National Historic Area
'amre', ,
'azte', ,
'blac', http://www.nps.gov/blac, Blackstone River Valley National Heritage Corridor
'cali', http://www.nps.gov/cali, California National Historic Trail
'chna', ,
'copa', ,
'erca', ,
'exam', ,
'futp', ,
'glec', http://www.nps.gov/glec, Glen Echo Park
'grfa', http://www.nps.gov/grfa, Great Falls Park
'hrst', ,
'iatr', http://www.nps.gov/iatr, Ice Age National Scenic Trail
'jame', http://www.nps.gov/jame, Historic Jamestowne - Part of Colonial National Historical Park
'lecl', http://www.nps.gov/lecl, Lewis & Clark National Historic Trail
'lomi', ,
'mopi', http://www.nps.gov/mopi, Mormon Pioneer National Historic Trail
'move', ,
'naps', ,
'nats', ,
'natt', http://www.nps.gov/natt, Natchez Trace National Scenic Trail
'njco', ,
'noco', http://www.nps.gov/noco, North Country National Scenic Trail
'oreg', http://www.nps.gov/oreg, Oregon National Historic Trail
'ovvi', http://www.nps.gov/ovvi, Overmountain Victory National Historic Trail
'pine', http://www.nps.gov/pine, New Jersey Pinelands National Reserve
'pohe', http://www.nps.gov/pohe, Potomac Heritage National Scenic Trail
'pony', ,
'safe', http://www.nps.gov/safe, Santa Fe National Historic Trail
'semo', http://www.nps.gov/semo, Selma to Montgomery National Historic Trail
'trte', http://www.nps.gov/trte, Trail of Tears National Historic Trail
'usar', ,
'usmc', ,
'wanc', ,
'york', http://www.nps.gov/york, Yorktown Battlefield - Part of Colonial National Historical Park

Quite a few of them are National Trails and Heritage Areas. Others (the ones without a url or full name) may be invalid. I'd say we should focus on getting the trails and heritage areas added to our parks table - even if we don't have a geometry for now.

HFC also has a map for `seki`, but it still isn't in our table. Related to this issue: https://github.com/nationalparkservice/places-data/issues/291.

'seki' -> Currently matched to 'sequ' and/or 'kica'

Cc/ @cwlawlis802

**Comment by chadlawlis** [comment]
The following have been added to both PostGIS and CartoDB `parks` tables (along with PostGIS `parks_poly` and `parks_line`), _without geometries_:

| unit_code | url | full_name |
| --- | --- | --- |
| aleu | http://www.nps.gov/aleu | Aleutian World War II National Historic Area |
| blac | http://www.nps.gov/blac | Blackstone River Valley National Heritage Corridor |
| cali | http://www.nps.gov/cali | California National Historic Trail |
| glec | http://www.nps.gov/glec | Glen Echo Park |
| grfa | http://www.nps.gov/grfa | Great Falls Park |
| iatr | http://www.nps.gov/iatr | Ice Age National Scenic Trail |
| jame | http://www.nps.gov/jame | Historic Jamestowne - Part of Colonial National Historical Park |
| lecl | http://www.nps.gov/lecl | Lewis & Clark National Historic Trail |
| mopi | http://www.nps.gov/mopi | Mormon Pioneer National Historic Trail |
| natt | http://www.nps.gov/natt | Natchez Trace National Scenic Trail |
| noco | http://www.nps.gov/noco | North Country National Scenic Trail |
| oreg | http://www.nps.gov/oreg | Oregon National Historic Trail |
| ovvi | http://www.nps.gov/ovvi | Overmountain Victory National Historic Trail |
| pine | http://www.nps.gov/pine | New Jersey Pinelands National Reserve |
| pohe | http://www.nps.gov/pohe | Potomac Heritage National Scenic Trail |
| safe | http://www.nps.gov/safe | Santa Fe National Historic Trail |
| semo | http://www.nps.gov/semo | Selma to Montgomery National Historic Trail |
| trte | http://www.nps.gov/trte | Trail of Tears National Historic Trail |
| york | http://www.nps.gov/york | Yorktown Battlefield - Part of Colonial National Historical Park |

**SEKI** has also been added to both as well, as a union of the SEQU and KICA geometries from `WSD_Parks`:

``` sql
insert into parks_poly VALUES ((select max(unit_id) + 1 from parks_poly), 'seki', (select st_union((select geom_poly from parks_poly where unit_code = 'kica'), (select geom_poly from parks_poly where unit_code = 'sequ'))));
```

``` sql
INSERT INTO parks (unit_id, unit_name_short, unit_name_long, unit_desig_abbr, unit_desig_full, unit_code, unit_area, simp_type, geom_point, data_source, region_code, created_by, state, url) values ((select max(unit_id) + 1 from parks), 'Sequoia & Kings Canyon', 'Sequoia & Kings Canyon', 'NP', 'National Parks', 'seki', (select ST_Area(geom_poly) from parks_poly where unit_code = 'seki'), 'point', (select ST_Centroid(geom_poly) from parks_poly where unit_code = 'seki'), 'WSD_Parks', 'PWR', 'Chad Lawlis', 'California', 'http://www.nps.gov/seki/index.htm');
```

``` sql
insert into parks_line values ((select unit_id from parks where unit_code = 'seki'), 'seki');
```

The remaining units are as follows (the ones not on NPS.gov):

| unit_code | url | full_name |
| --- | --- | --- |
| alas | http://www.nps.gov/alas/index.htm |  |
| amre | http://www.nps.gov/amre/index.htm |  |
| azte | http://www.nps.gov/azte/index.htm |  |
| chna | http://www.nps.gov/chna/index.htm |  |
| copa | http://www.nps.gov/copa/index.htm |  |
| erca | http://www.nps.gov/erca/index.htm |  |
| exam | http://www.nps.gov/exam/index.htm |  |
| futp | http://www.nps.gov/futp/index.htm |  |
| hrst | http://www.nps.gov/hrst/index.htm |  |
| lomi | http://www.nps.gov/lomi/index.htm |  |
| move | http://www.nps.gov/move/index.htm |  |
| naps | http://www.nps.gov/naps/index.htm |  |
| nats | http://www.nps.gov/nats/index.htm |  |
| njco | http://www.nps.gov/njco/index.htm |  |
| pony | http://www.nps.gov/pony/index.htm |  |
| usar | http://www.nps.gov/usar/index.htm |  |
| usmc | http://www.nps.gov/usmc/index.htm |  |
| wanc | http://www.nps.gov/wanc/index.htm |  |

**Comment by chadlawlis** [comment]
@nateirwin should i add these remaining units in with just their unit codes? None seem to align with any "alternate unit codes" we've identified thus far.

**Comment by nateirwin** [comment]
Nah, I say let's leave them out for now. It seems to me like HFC invented some unit codes when they created new maps. Let's just add them, one-by-one, if/when they come up.

Closing. Thanks, @cwlawlis802!
