### ISSUE TITLE
Create regional units as multipolygons

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#335]
Currently using `ST_Union(geom1, geom2)` to merge subunit geometries into larger regional unit (e.g. SEQU + KICA = SEKI), but we need to do this in a way to maintain dividing line between the two as a multipolygon.

**Comment by chadlawlis** [comment]
http://stackoverflow.com/questions/24184927/postgis-merge-multipolygons-and-keeping-boundaries

**Comment by mtaylorlong** [comment]
This would be cool. Would we store these in a separate regions table?

**Comment by chadlawlis** [comment]
Separating out into individual issues:

NPNH https://github.com/nationalparkservice/places-data/issues/375
GOGA https://github.com/nationalparkservice/places-data/issues/376
SEKI https://github.com/nationalparkservice/places-data/issues/358

Will add others as they come up.

These will be stored in the PostGIS `parks` table as the geometry for each unit code.

**Comment by chadlawlis** [comment]
``` sql
CREATE TABLE group_subunits as SELECT
 st_multi(st_collect(geom_dump.the_geom)) AS geom_poly,
  ARRAY_AGG(DISTINCT unit_code) AS subunits,
  COALESCE(geom_dump.subunit_of, geom_dump.unit_code) AS unit_code
FROM (
  SELECT
    (ST_Dump(parks_poly.geom_poly)).geom AS the_geom,
    parks.subunit_of,
    parks.unit_code,
    parks.unit_id
  FROM
    parks_poly JOIN parks ON
      parks_poly.unit_id = parks.unit_id
    ) AS geom_dump
    where unit_code = 'seki' or unit_code = 'hafe'
GROUP BY
  COALESCE(geom_dump.subunit_of, geom_dump.unit_code);
```

Revise this code to only create regional multipolygons for each region, rather than all units period.

Note: Mapbox does not currently render multipolygons correctly (splitting the inner boundary lines into small polygons), so @jimmyrocks will open a ticket with them to resolve this.
