### ISSUE TITLE
JAME & YORK unit_name_short and unit_name_long

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#336]
JAME and YORK include "Part of Colonial National Historical Park Virginia" in their name/designation on NPS.gov. We should figure out how best to record their names in our boundary tables.

Possible solution:

| unit_name_short | unit_name_long |
| --- | --- |
| Historic Jamestowne | Historic Jamestowne - Part of Colonial |
| Yorktown Battlefield | Yorktown Battlefield - Part of Colonial |

The `unit_name_long` is then concatenated with `unit_desig_abbr` of "NHP" (National Historical Park) for the label on the map.

cc @mtaylorlong

**Comment by mtaylorlong** [comment]
How about this:

Short Names:
- Historic Jamestowne NHP
- Yorktown Battlefield NHP

Long Names:
- Historic Jamestowne - Colonial National Historic Park
- Yorktown Battlefield - Colonial National Historic Park

| unit_name_short | unit_name_long | unit_desig_abbr | unit_desig_full | subunit_of |
| --- | --- | --- | --- | --- |
| Historic Jamestowne | Historic Jamestowne - Colonial | NHP | National Historic Park | colo |
| Yorktown Battlefield | Yorktown Battlefield - Colonial | NHP | National Historic Park | colo |

**Comment by nateirwin** [comment]
I'm actually not sure we need to add "Colonial" to the name at all. I know it's on their website, but I would say that most visitors probably don't care that Jamestowne and Yorktown are part of Colonial. That's something we care about internally, but it would be like saying "Washington Monument - Part of National Capital East".

**Comment by mtaylorlong** [comment]
Ooh - love the Washington Monument analogy @nateirwin. I'm convinced.

We do, however, still need to think about how the labeling works. Do y'all think it's okay to handle this like other subunits with the Colonial NHS label showing at smaller scales, then going away at larger scales when Jamsetowne and Yorktown appear?

**Comment by nateirwin** [comment]
That sounds like a good approach to me.

**Comment by mtaylorlong** [comment]
Here's another one that I can handle after @cwlawlis802 sets these up as subunits in the parks table.

Chad: I'm assigning this to you. Once you've sub-united these parks, you can kick it back to me for the finishing touches.

**Comment by chadlawlis** [comment]
Okay, JAME and YORK attribute data has been updated (`unit_name_short`, `unit_name_long`, `data_source`, and `subunit_of`).

Currently, COLO has a `geom_poly` but JAME and YORK do not. However, COLO's geometry includes them both. So, I will need to split out separate geometries for each JAME and YORK from COLO's current geometry, so we can search/zoom to these individual units and apply labels in PT3.

Opening new issue for this...

**Comment by chadlawlis** [comment]
Not sure what else you're looking to do here @mtaylorlong - removing my assignment but will let you close when appropriate.

**Comment by mtaylorlong** [comment]
:+1: As long as JAME and YORK have their own records (and more importantly, point geometries), then I'm good to go in PT3. 

Do they have point geometries that fall within their individual polygons?

**Comment by chadlawlis** [comment]
They do not - I believe their `geom_point` was created by a `SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_code = 'colo'`. So, once individual geometries have been created via https://github.com/nationalparkservice/places-data/issues/384 I can run this function to pull from their unique geometries for unique label points. Or, we can drop points on top of them manually now and upload as `geom_point` for a solution in the mean time.

**Comment by mtaylorlong** [comment]
I can wait. :smile:

**Comment by chadlawlis** [comment]
Closing - see https://github.com/nationalparkservice/places-data/issues/384#issuecomment-185275373 for context.

Only thing left to do here is adding custom label points for JAME and YORK, which is #547.
