### ISSUE TITLE
Park labels disappear when unit_desig is NULL

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#337]
@jimmyrocks: We were missing quite a few labels in the National Mall area, and I believe the problem seems to be that these labels have NULL in their designation fields. I'm guessing that when the name and designation are put together, the NULL values are throwing an error that results in no name at all.

Is there any way you can modify the rendering process so that labels are still made for parks with NULL in their designation fields? There are a handful of cases where we do this intentionally. I was hoping that appending NULL to the name would still at least give us the name. Let me know what you can do.

**Comment by jimmyrocks** [comment]
I can replace all NULL values with '', blank text values. This will be done
using the coalesce(field, '') function

**Comment by mtaylorlong** [comment]
Sounds good. That should solve the problem. We'll see after next time you run the tiles. When you're finished with the replace, you can close this issue.

**Comment by jimmyrocks** [comment]
The new ones will be run today, so I would expect to see them live by
tonight / tomorrow morning.

**Comment by jimmyrocks** [comment]
@mtaylorlong This should be fixed, can you verify that it is working the way you intend?

**Comment by mtaylorlong** [comment]
Seems to be working properly!
