### ISSUE TITLE
POIs outside park boundary?

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#34]
Hey guys, I don't remember this coming up at the mapathon but Eric just asked a good question about POIs outside the park boundary that would potentially be interesting POIs for visitors and/or assist park staff.  The example he brought up is the fish hatchery just north of the DINO boundary (see park map).  Fish from that hatchery will inevitably come into the park and may be interesting to put in there.  But with the whole cookie-cutter approach, I'm not sure how that would work.  Anyways, something to consider and let me know what you guys think.  Thanks, H

http://www.nps.gov/parkmaps/dino

**Comment by heidiogle** [comment]
Hey all,  Here's another example of a problem with the cookie cutter approach at COLM.  This is also going to be the case at many other IMR parks (any probably throughout the service).  As you see below, COLM has a trail that runs in and out of the park boundary and the park will want to show the whole thing.  Maybe it won't be a problem with edge-matching but just something else to keep in mind during planning.  Obviously, we'll want to retain our attributes inside park boundaries.  Thanks, H

![capture](https://cloud.githubusercontent.com/assets/11545684/7592801/cd5f11fa-f892-11e4-9bc2-3bc76b16aeae.JPG)

**Comment by jimmyrocks** [comment]
I think that we should include these points on our maps. We still aren't
completely sure how we'd like to do the "cookie-cutter" approach. It's
always better to have more (good) data!

**Comment by nateirwin** [comment]
Here's what we're going to do (at least for now): We will accept data outside of park boundaries, but we may not use it in some of our products. For example, when we "go live" with a version of Park Tiles that uses only data from Places inside park boundaries, we may clip the dataset at the park boundary.

Our general recommendation is to not spend much time digitizing outside of a park boundary, but if the data is there, we'll leave it.
