### ISSUE TITLE
PT 3.0: Campground symbols do not render consistently

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/places-data#341]
At seeming odd levels and extents, campground symbols turn on and off. Campgrounds, arguably more cartographically significant than parking spaces and trailheads, should be symbolized clearly and consistently. 

![image](https://cloud.githubusercontent.com/assets/5861784/11955838/4abe679a-a883-11e5-8462-28c965ae29d1.png)

![image](https://cloud.githubusercontent.com/assets/5861784/11955845/54d7f4ee-a883-11e5-9dc4-940c21227a20.png)

**Comment by nateirwin** [comment]
Moved to the park-tiles repository: https://github.com/nationalparkservice/park-tiles/issues/175. Closing here.
