### ISSUE TITLE
LAVO buildings

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#342]
From Elizabeth Hale, the park's GIS Specialist:

> My request is for a one-time data replacement of LAVO buildings in Places with the attached geodatabase. Specifically there is a field in this geodatabase called "Places_Name" to use for building footprint names. This is to address concerns that our Chief Ranger and Water Treatment Operator have about building use info being tagged to non-public facilities like water treatment building or GOV fueling station. They do not mind if those building footprints appear but do not want them identified by their administrative use. In the attached dataset non-public facilities are labeled "Administrative Building" + Building Number to alleviate those concerns, and that is how we want them labeled for public distribution. Please let me know if you have any questions.

[Link to dataset](https://drive.google.com/open?id=0B9Ygi7kxEFrBUmNPY2VVQU1XaUk)

**Comment by jakecoolidge** [comment]
attributes were converted to tags as follows:

#### added

nps:source_system=LAVO_Buildings_Places_20151207.gdb
nps:source_system_key=Building_ID
building=yes

#### modified

Building_ID -> nps:source_system_key_value
Unit_Code -> nps:unit_code (entries made lowercase)
FMSS_ID -> nps:fmss_location_id
Places_Name -> name

#### deleted

Geometry_ID
Polygon_Type
Is_Extant
Edit_Date
Map_Method
Admin_Type
Federal_Entity_Type
Building_FCode
LCS_ID
ASMIS_ID
Park_ID
Region_Code
GlobalID
Distribute
Shape_Length
Shape_Area
