### ISSUE TITLE
FOLS data seed

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#343]
Relegated to the spam folder on Nov. 30(?):

"I have GIS information from Fort Larned NHS for you. Please let me know if you have any questions or need more information from us."

**Comment by jakecoolidge** [comment]
Data stored [here](https://drive.google.com/open?id=1D-U5_MwLSuXzB0Koi2Si5W_HtdfE26gEp7Oi0OVlV6Y). Data stored as lat/lngs in a table, inside a Google Document. Polygons are represented as a series of coordinates, so some conversion will be necessary.

**Comment by jimmyrocks** [comment]
This is the kind of fun data transformation I like to do! Let me know if
you need it in geojson, and I can write a script for you.

**Comment by jakecoolidge** [comment]
Hey @jimmyrocks, as long as the output is readable in QGIS, I'm set. Script at will! ;)

**Comment by jakecoolidge** [comment]
#### Point data

Seeded with the following attribute-to-tag conversions:
Location -> name
The following attributes were not uploaded:
Equipment number (2 columns), PDOP, HAF

In all cases, the Location attribute serves as both a name and an indicator of the type of point of interest. The following categories were identified, the most similar preset selected, and tagged accordingly:
Monument `historic=monument`
Regulatory Sign `tourism=information; information=sign; sign:type=regulatory`
Entrance Gate `barrier=gate`
Fire Hydrant `emergency=fire_hydrant`
Flag Pole `man_made=flagpole`
Entry Sign `tourism=information; information=sign`
History Kiosk `tourism=information; information=exhibit`
Historic Building `historic=yes; building=yes` (includes Historic Wellhouses, Historic Privies)
Historic Well `man_made=water_well; historic=yes`
Nature Trail Marker `tourism=information; information=guidepost`
Picnic Area `tourism=picnic_site`
Water Fountain `amenity=fountain`
Historic Marker `historic=marker`
Grave Marker `cemetery=grave`

These types were not imported, as they are not supported in Places:
Culverts
Picnic Lights
Water Lines
Pump House (this also appears to be mislocated in a random farm field far from the park)
Lift Station

additional tags added to all points:
`nps:unit_code=fols`
`nps:source_system=Fort Larned GIS Information`

**Comment by jakecoolidge** [comment]
As captured in the raw DMS-to-geojson conversion process, the polygons for parking areas were coarse enough to warrant digitization from imagery within Places Editor. Data provided informed the digitization process.

**Comment by jakecoolidge** [comment]
Digitized using Places Editor: roads, bridge, parking areas
Data not digitized-- 
--duplicates existing data: 
- buildings (one key exception, the Cooling Unit & Condenser)

--outside the scope of Places:
- oxbow
- fences
- culverts
