### ISSUE TITLE
FODA boundary parcel showing up in DC

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#354]
This is the landing zoom when searching for "Fort Davis National Historic Site" in PT3:

![foda_landing](https://cloud.githubusercontent.com/assets/1238636/12153736/c44f0884-b478-11e5-90cf-321c262141ff.jpg)

This is because of an unassociated parcel labeled as `unit_code = 'foda'` in DC:

![park tiles 3 insidemaps 2016-01-06 13-27-26](https://cloud.githubusercontent.com/assets/1238636/12153816/4ec1481a-b479-11e5-832e-10b6db3963e2.jpg)

![park tiles 3 insidemaps 2016-01-06 13-26-53](https://cloud.githubusercontent.com/assets/1238636/12153819/518a5e2e-b479-11e5-80aa-a15ef310ef62.jpg)

I will remove this parcel as part of the NCR boundary replacement process https://github.com/nationalparkservice/places-data/issues/347 and re-upload the single boudary in Texas: http://insidemaps.nps.gov/park-tiles-3/#16/30.5999/-103.8934.

**Comment by chadlawlis** [comment]
New, single boundary [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbQ0gta0FCcnh0ZlU).

**Comment by cwlawlis802** [comment]
The boundary has been corrected, leaving this open for PT3 labeling issue.

**Comment by chadlawlis** [comment]
Boundary has been fixed.

Labeling issue now here: https://github.com/nationalparkservice/places-data/issues/355.
