### ISSUE TITLE
FODA labeled twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#355]
FODA is labeled twice at Z10-13:

![park tiles 3 insidemaps 2016-01-06 13-29-58](https://cloud.githubusercontent.com/assets/1238636/12153872/9b6abf7a-b479-11e5-8a2a-eec7a9b0bddb.jpg)

cc @mtaylorlong.

**Comment by mtaylorlong** [comment]
This can be fixed by editing the FODA record in our parks table. We just need to set `ldir_enforce` to `true`. I'll do it next time I'm in the table, unless @cwlawlis802 can beat me to it. :wink:

**Comment by chadlawlis** [comment]
Done and done :heavy_check_mark:

**Comment by mtaylorlong** [comment]
@cwlawlis802: You are a god among men.
