### ISSUE TITLE
AMIS labels twice

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#356]
Perhaps similar to [FODA](https://github.com/nationalparkservice/places-data/issues/355), Amistad NRA labels twice at zooms 7-9.

**Comment by mtaylorlong** [comment]
This is another super-quick fix in the parks table. I'm going to tap Chad again on this since he's probably in the table as we speak. (It takes me like 5 minutes to remember how to log in).

@cwlawlis802: Will you change AMIS `ldir_enforce` to `true`? No rush.

**Comment by chadlawlis** [comment]
Done.
