### ISSUE TITLE
Add BUFF simplified line geometry

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#357]
I want to prep Park Tiles 3 for handing simplified boundaries as lines (helpful for national trails, rivers, scenic byways, etc), so I'm going to experiment with the Buffalo National River (BUFF).

@cwlawlis802: Here's a shapefile of the line geometry to store in the parks line geometry table for BUFF.
- [buff_line.zip](https://github.com/nationalparkservice/places-data/files/81806/buff_line.zip)  

The only other thing to do is switch the BUFF record's simplification type from point to line. Can you handle that too?

@jimmyrocks: I don't think we'll need to change anything in the rendering to accommodate this since we're already rendering our park lines for APPA.

**Comment by mtaylorlong** [comment]
This is lower priority than other fixes for the 3.0.1 release, but if the tiles are ready, I think I can implement it with not much work. It would serve as a helpful example for how other line-oriented boundaries can be dealt-with similarly.

**Comment by chadlawlis** [comment]
Updated `simp_type = 'line'` :heavy_check_mark:

I can try adding the `geom_line` now.

**Comment by chadlawlis** [comment]
Okay, `geom_line` has been added. Should be all set here.

**Comment by mtaylorlong** [comment]
:+1: Now I just have to pay attention to next time @jimmyrocks updates the vector tiles and jump in after that.
