### ISSUE TITLE
Integrate updated/corrected boundaries for WAPA and AMME from Lands dataset

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#36]
From Justin Mills (justin_s_mills@nps.gov)

I was just looking at the NPMap Park Tiles for our parks (War in the Pacific NHP/WAPA and American Memorial Park/AMME) and noticed that the boundaries for both parks have pretty serious datum errors.  These errors were in the NPS Lands Division official boundaries layer for many years, but they just fixed them a few weeks ago.

AMME is here:  http://www.nps.gov/npmap/tools/park-tiles/#16/15.2169/145.7272
The north side of the boundary should follow the coastline; the entire park outline is shifted southwest.

WAPA is here: http://www.nps.gov/npmap/tools/park-tiles/#13/13.4239/144.7263
You can see the WAPA datum shift pretty clearly here (the south-west boundaries should follow the curve of the big road):  http://www.nps.gov/npmap/tools/park-tiles/#17/13.46297/144.73348

Can you pull the updated boundaries into the Park Tiles to make sure this gets fixed?  

We have higher resolution boundary information available in-house based on land parcel maps and field GPS surveys; we'd be happy to share that with your team, as well.  I've been passing this stuff along to the PWR GIS folks, too, if it's easier to deal directly with them.

Thanks!  The NPMap products look great and perform very well; I think this is a great way forward for us!

**Comment by jimmyrocks** [comment]
Both WAPA and AMME have been updated with the IRMA/Lands Boundary
