### ISSUE TITLE
Add the parkTilesSymbol column

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-data#360]
Add the column to the JSON files and add a column for it in the database

This will be used to send the icon directly out to the vector tiles

**Comment by mtaylorlong** [comment]
This is no longer necessary as we're going all in on the vector overlay approach. 

However, for the sake of getting these columns in I'd like to rename that column in the NPS_Preset_Classes spreadsheet from `parkTilesSymbol` to `npmapSymbol` and populate it with all the appropriate icons we have available in NPMap Symbol Library. Then, we can use that spreadsheet to add an `npmapSymbol` column to our POI data in cartodb. How does that sound to you @jimmyrocks?

**Comment by mtaylorlong** [comment]
I'm actually closing this one, because it's pretty specific, and I'm assuming it was already taken care of. I'll open a separate issue for getting the symbol names into a cartodb table.
