### ISSUE TITLE
Add the parkTilesSymbol to vector tiles

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-data#361]
This will need to be done after this issue is closed: https://github.com/nationalparkservice/places-data/issues/360

**Comment by jimmyrocks** [comment]
This is only for POIs

**Comment by mtaylorlong** [comment]
No longer necessary due to the vector overlay approach (#380). If it's slowing down the rendering, you can remove it, but if not, it's no big deal to leave it there for now.
