### ISSUE TITLE
GLDE boundary + label not rendering

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#363]
@nateirwin noticed that the boundary for GLDE is currently not rendering or being labeled in PT3 (though we have a boundary) http://insidemaps.nps.gov/park-tiles-3/#17/39.93430/-75.14387:

![glde](https://cloud.githubusercontent.com/assets/1238636/12207945/dec086b8-b606-11e5-978e-d5465fcdc175.jpg)

This is because of how the carto fields in PostGIS `parks` are populated:

![glde_carto](https://cloud.githubusercontent.com/assets/1238636/12207995/3f9b8eba-b607-11e5-8766-c2f8e1f75644.jpg)

@mtaylorlong could you go in and populate these so this renders in PT3? Despite `min_zoom_label` being 15 it does not appear to render at Z15 or higher.

**Comment by mtaylorlong** [comment]
On it!

**Comment by mtaylorlong** [comment]
I have resolved this by resetting it's min_zoom settings to 14.
