### ISSUE TITLE
Missing boundaries for eight units

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#366]
The following units have a website but do not have a boundary in our database:
- CLMO
- DABE
- GREG
- IATR
- NPNH
- OKCI
- ROCA
- TOSY

I found these by going through the [list of brochure maps](http://www.nps.gov/hfc/cfm/carto-atoz.cfm) on the HFC site and comparing it to our parks table. It would be good to get these boundaries before we go live with PT3 to ensure that every park has at least one map (Park Tiles or a brochure map) on their new website.

Cc/ @cwlawlis802

**Comment by chadlawlis** [comment]
Thanks for generating this list, @nateirwin.

CLMO (NCR), DABE (MWR), GREG (NER), ROCA (NER), and TOSY (NER) do not have a geometry in our database (though GREG has a record) and are not included in Lands either. I can ping the regional GIS reps at NER and MWR to inquire.

IATR is a National Scenic Trail, which presents complications that @mtaylorlong is currently working through. Issue here https://github.com/nationalparkservice/places-data/issues/254. It currently has a record in our database, without a geometry.

NPNH is a `subunit_of` issue - we need a complete list of all units that fall within it to create a multipolygon from. @jakecoolidge will ping Mark about this.

OKCI issue open here https://github.com/nationalparkservice/places-data/issues/243. I've pinged IMR about this a couple of times, they do not seem to have anything nor does Lands.

**Comment by chadlawlis** [comment]
CLMO, DABE, NPNH, OKCI, ROCA, and TOSY were each added to `parks`, `parks_poly` and `parks_line`. Geometries will be added as they become available, which can be tracked on their individual issues - including GREG and IATR.

Closing.
