### ISSUE TITLE
Polygon boundary and label never display for THKO

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#367]
http://insidemaps.nps.gov/park-tiles-3/#19/39.94345/-75.14732

Cc/ @mtaylorlong

**Comment by mtaylorlong** [comment]
This one's another places table issue. I'm on it!

**Comment by mtaylorlong** [comment]
I've fixed this issue by setting all min_zoom attributes to 14.

**Comment by chadlawlis** [comment]
This appears to be persisting: http://insidemaps.nps.gov/park-tiles-3/#19/39.94328/-75.14736

cc @mtaylorlong

**Comment by chadlawlis** [comment]
I'm guessing this has been fixed and will be corrected once the tiles have been regenerated.

**Comment by mtaylorlong** [comment]
New boundaries render has fixed this issue:
![screen shot 2016-02-18 at 12 05 54 pm](https://cloud.githubusercontent.com/assets/4741443/13154815/0daaed46-d638-11e5-9062-9df0f3f4d6ed.png)
