### ISSUE TITLE
Populate `subunit_of` for GOGA

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#368]
Separating out from https://github.com/nationalparkservice/places-data/issues/291.

We currently have individual unit geometries for these "subunits":
- PRSF (though this boundary is not rendered in Park Tiles)
- FOPO
- SAFR
- MUWO

ALCA should also be included in this - it is included in our current GOGA geometry, but does not have a standalone unit geometry.

I am in touch with the GIS Specialist @ GOGA to confirm this list and correct the geometries.

See also this issue https://github.com/nationalparkservice/places-data/issues/240 for reference.

**Comment by chadlawlis** [comment]
From glancing at this list http://www.nps.gov/goga/planyourvisit/index.htm it looks like the following are subunits of GOGA:
- ALCA
- MUWO
- Marin Headlands (no unit code)
- FOPO
- Crissy Field (no unit code; part of The Presidio PRSF though)
- SAFR

Still need to discuss/confirm with Craig.

**Comment by mtaylorlong** [comment]
GOGA has proposed a new strategy for boundaries that no longer requires us to use the subunit approach.

**Comment by chadlawlis** [comment]
Well, we still want to populate the `subunit_of` field for information purposes right @mtaylorlong?

**Comment by mtaylorlong** [comment]
Yes, you're right. My bad. We'll leave this open and push it to 3.0.2.

**Comment by chadlawlis** [comment]
:+1:

**Comment by chadlawlis** [comment]
Okay, the following have been added with `subunit_of = 'goga'`:
- MUWO
- ALCA
- FOPO
- PRSF
- SAFR

Crissy Field and Marin Headlands are not units, so these do not warrant records in our table. They will be added as localities to receive labels in PT3.

To reiterate, `subunit_of` has no cartographic implications - it is simply a useful list of all units that are associated with a larger unit. We will be using `pt_render` moving forward to control hierarchical boundary renderings, in our new boundary table schema.
