### ISSUE TITLE
POI tag additions/revisions

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#37]
Just a heads up; I went through the NPS_Places_Presets spreadsheet and found a couple items to be aware of. I wanted to point you guys to them without actually modifying the document.

pathname: natural/prarie should be spelled natural/prairie

We have icons from HFC for the following, but I didn't find associated tags:
- Boat Tour
- Horseback Riding
- Litter Receptacle
- Pets on Leash area

Nothing too major; otherwise looks good!

**Comment by jimmyrocks** [comment]
Thanks for going through that!
Prairie is a hard word to type

I'm not sure what the do about the icons, but it's good to make a note of
it.

**Comment by chadlawlis** [comment]
Looks like `natural=prairie` is all set, and we have added `horseback riding` back in as a POI. I believe `amenity=waste_basket` should serve the same purpose as `litter receptacle`, otherwise I do not think we are currently supporting `boat tour` or `pets on leash area`.
