### ISSUE TITLE
Create GOGA as multipolygon

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#376]
See https://github.com/nationalparkservice/places-data/issues/368 for subunits and https://github.com/nationalparkservice/places-data/issues/240 for reference.

**Comment by mtaylorlong** [comment]
@cwlawlis802: Worked with GOGA and has this all straightened out. It still might need a little more tweaking in the labeling, but I'm closing out this issue since GOGA will no longer be handled with the subunit approach.
