### ISSUE TITLE
Populate carto fields for OKCI

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#377]
This is only a point, so probably only requires `min_zoom_label`, `min_zoom_label_long`, and `min_zoom_label_center`.

**Comment by mtaylorlong** [comment]
Here are the settings I used:
- `min_zoom_label`: 7 (plenty of space in OK)
- `min_zoom_label_long`: 14 (last chance for a long label)
- `min_zoom_label_center`: 100 (it will always be labeled as a point)

**Comment by mtaylorlong** [comment]
@cwlawlis802: I see the record for this site in my QGIS table, but I don't see the point on the map. It seems like it doesn't yet have a valid point geometry. Will you check up on this before we close out this ticket?

**Comment by chadlawlis** [comment]
This should be all set via https://github.com/nationalparkservice/places-data/issues/243#issuecomment-176951631.
