### ISSUE TITLE
Missing ALCA boundary

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#378]
See https://github.com/nationalparkservice/places-data/issues/240#issuecomment-162644360.

We need a standalone boundary to generate a label point and search landing extent.

**Comment by cwlawlis802** [comment]
I'm removing my assignment from these "missing boundary" issues in an effort to clean out my list of issues assigned to me. The standalone ALCA boundary will be generated with the GOGA update.

**Comment by chadlawlis** [comment]
This has been generated from the new boundary source Craig sent along. It is kind of a grey area as to whether this is really considered its own unit - really, it isn't - but for the purposes of NPS.gov and Park Tiles we will maintain it as its own for data querying and search functionality.

The "new" boundary is very similar to what we had before:

<img width="697" alt="alca" src="https://cloud.githubusercontent.com/assets/1238636/13163565/785eddae-d66b-11e5-9860-7a8393766b95.png">

**Comment by chadlawlis** [comment]
Data [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbR1dJWHlwOE9zeUk).
