### ISSUE TITLE
Mapbox tiles showing duplicate geometries

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#38]
This screenshot is of an area in Petersburg National Battlefield. You can see that multiple trail lines are displaying, but when I view this same area in Places Editor, there is only one representation of the line there. So it seems like Mapbox and Places are out-of-sync - at least for trails.

![places_x-ray](https://cloud.githubusercontent.com/assets/10443/7692155/1b143106-fd7e-11e4-9df2-dc36f3413bc0.jpg)

**Comment by jimmyrocks** [comment]
The way that the synchronization works for mbstudio would not allow for
this kind of error to show up. The sync tool re-renders an entire tile if
there is a change anywhere in it, and as far as I know, it's not possible
to update only part of a vector tile.

Can you send me the location in places so I can look at it further and see
why it's rendering incorrectly?

My best guess is that it's this location:
http://insidemaps.nps.gov/places/edit/#background=mapbox-satellite&map=17.74/-77.36559/37.22343&overlays=park-tiles-overlay

**Comment by nateirwin** [comment]
http://insidemaps.nps.gov/places/edit/#background=mapbox-satellite&map=18.00/-77.36671/37.22325&overlays=park-tiles-overlay

**Comment by makella** [comment]
Hi Jim,

If you look at [this map](http://www.nps.gov/maps/full.html?mapId=24b8ab4d-a35f-4927-9454-b11a73c81250) and zoom to PETE, you'll see that there are double lines drawing for a lot of the trails. It looks like the old geometries are still in there somehow. I'm using the data source nps-places-data.

I refreshed the data source so I'm not sure what's going on.  Hope this helps.

**Comment by jimmyrocks** [comment]
Yeah, that's what I thought.
I just re-ran the entire dataset, so that would eliminate any possibility
of a syncing problem.
Let's wait an hour, see if it gets updated
and if not, we need to dig into the vector tiles themselves, and possibly
open a ticket.
Thanks for finding this!

**Comment by makella** [comment]
Yeah, yesterday when I looked it seemed that the data had not been updated since 5/15 when I looked just now it said 5/18 so I'll keep an eye to see if things get updated.

**Comment by makella** [comment]
If you want to pull down the Mapbox Studio project to see the data on the map, you can find it [here](https://github.com/nationalparkservice/mapbox-studio-projects/tree/master/places_xray) and open up places_xray_fused.tm2.

**Comment by jimmyrocks** [comment]
Great, thanks!

**Comment by nateirwin** [comment]
Yeah, this is a major problem in PETE - with more than just trails: http://www.nps.gov/maps/full.html?mapId=41f2dea7-042e-494e-a879-5565b12880f2#16/37.2236/-77.3699.

**Comment by jimmyrocks** [comment]
I think I have it figured out, should be updated in the tiles by tomorrow.

**Comment by jimmyrocks** [comment]
I wasn't updating deleted objects on the database site, so things weren't
getting deleted

I changed the code here:
https://github.com/nationalparkservice/places-api/commit/5e4c480a341a4a12e26c90b2079620d463f0a804

and everything should get pushed in the next sync with cartodb
I'll be rerunning the places_data and poi this evening so we should see the
change tomorrow

**Comment by jimmyrocks** [comment]
![screen shot 2015-05-19 at 4 48 46 pm](https://cloud.githubusercontent.com/assets/98192/7715667/00d713c0-fe47-11e4-91d1-36fa1b7b989e.png)

**Comment by nateirwin** [comment]
Nice, @jimmyrocks!

**Comment by makella** [comment]
+1!
