### ISSUE TITLE
Fix all missing boundaries in parks table where min_zoom_poly > 14

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#382]
We should find a time to look through the entire parks table to identify boundaries that don't show up in Park Tiles because their min_zoom_poly is greater than 14. There are a few cases in which we do this on purpose to never show a boundary, but there are plenty where it needs to be adjusted. 

We should be able to to a clean sweep through the whole database to solve these. Technically, I can do it on my own, but I might need @cwlawlis802 looking over my shoulder for moral support. :)

**Comment by chadlawlis** [comment]
Sounds good, happy to help - I'll continue flagging issues as they emerge, otherwise let me know if you sit down for a database-wide sprint.

**Comment by jimmyrocks** [comment]
We used to account for this by adding another layer that was park_poly > 14
with all the park boundaries that show up later included.

**Comment by mtaylorlong** [comment]
I've updated the `parks` table by pushing all the min_zoom settings >14 back to 14. This is essentially the same thing as including an additional layer with all the parks included.

So, the helpful change is that all the park boundaries will be available for display. The scary change is that some very small parks will turn into polygons with full names at z14, which may cause some new collisions. If things are too crazy in SF, DC, and NYC, we can try to think of a better solution in the future. For now, I think this change does a lot more good than harm.
