### ISSUE TITLE
THRO Label Move

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#386]
Theodore Roosevelt National Park is spit into two properties, so the label point sits in between them. 

![screen shot 2016-01-15 at 5 05 56 pm](https://cloud.githubusercontent.com/assets/4741443/12368618/4704ea4a-bbaa-11e5-9250-3d1aa04ce069.png)

I want to move the point so it's over whichever part of the park is more 'primary' to the visitor experience (probably where a visitor center is).

**Comment by chadlawlis** [comment]
There appear to be two visitor centers - one in each parcel:
http://www.nps.gov/hfc/carto/PDF/THROmap1.pdf
http://www.nps.gov/hfc/carto/PDF/THROmap2.pdf

Might be another multi-label park, if possible.

**Comment by mtaylorlong** [comment]
Ah, tricky. I'm inclined to move the label to the southern unit for now. There are two visitor centers in the southern unit, and there seems to be more going on down there. I don't think this is a final solution though – I need to think of a way to label these disconnected parts without bulking up to code too much, but I think that will have to wait until the next release.

@cwlawlis802: Does this sound okay to you? Will you move the label point over the southern unit?

**Comment by chadlawlis** [comment]
@mtaylorlong works for me. From our conversation here https://github.com/nationalparkservice/places-data/issues/48#issuecomment-172136417 we can probably add a label-only point for each parcel, but still TBD.

So, for this - would you like me to move the primary label point `geom_point` for THRO to the southern parcel? Or add a label-only record for it (maintaining the original `geom_point` as it currently is)?

**Comment by mtaylorlong** [comment]
@cwlawlis802: Let's move the current primary point to the southern unit. Then, since this one seems a bit more straightforward, let's add a new label secondary label point over the northern unit and I'll update the attributes.

**Comment by chadlawlis** [comment]
Okay, I moved the primary label point over the southern area:

``` sql
UPDATE parks SET geom_point = (SELECT ST_GeomFromText('POINT(46.95275229576011 -103.45687866210938)', 3857)) WHERE unit_code = 'thro';
```

Similar to https://github.com/nationalparkservice/places-data/issues/48#issuecomment-177032909 we (@jimmyrocks @mtaylorlong) should iron out exactly how we want to handle adding label-only records to the parks table.

For the secondary, northern label-point, when we're ready:

``` sql
SELECT ST_GeomFromText('POINT(47.60017325737256 -103.38040351867676)', 3857)
```

**Comment by chadlawlis** [comment]
See context for decisions here https://github.com/nationalparkservice/places-data/issues/416.

Northern label-only point added via:

``` sql
INSERT INTO parks (
  unit_id,
  unit_name_short,
  unit_name_long,
  unit_desig_abbr,
  unit_desig_full,
  unit_code,
  geom_point,
  data_source)
VALUES (
  (SELECT max(unit_id) + 1 FROM parks),
  (SELECT unit_name_short FROM parks WHERE unit_id = '380'),
  (SELECT unit_name_long FROM parks WHERE unit_id = '380'),
  (SELECT unit_desig_abbr FROM parks WHERE unit_id = '380'),
  (SELECT unit_desig_full FROM parks WHERE unit_id = '380'),
  (SELECT unit_code FROM parks WHERE unit_id = '380'),
  (SELECT ST_GeomFromText('POINT(47.60017325737256 -103.38040351867676)', 3857)),
  'Label-only');
```

**Comment by chadlawlis** [comment]
Okay @mtaylorlong, handing off for carto field population. `unit_id = '465`.

**Comment by chadlawlis** [comment]
@mtaylorlong pointed out that the `geom_point` is showing up on Null Island.

We realized that when adding these coordinates we need to do so in 4326, then convert to 3857. I also realized that `ST_GeomFromText()` requires lon lat, not lat lon. So, to fix:

``` sql
-- reset point coordinate in 4326 for primary southern point
UPDATE parks
SET geom_point = (SELECT ST_GeomFromText('POINT(-103.45687866210938 46.95275229576011)', 4326))
WHERE unit_id = '380';

-- reset point coordinate in 4326 for label-only northern point
UPDATE parks
SET geom_point = (SELECT ST_GeomFromText('POINT(-103.38040351867676 47.60017325737256)', 4326))
WHERE unit_id = '465';

-- convert to 3857
UPDATE parks
SET geom_point = ST_Transform(ST_SetSRID(geom_point, 4326), 3857)
WHERE unit_code = 'thro';
```

**Comment by mtaylorlong** [comment]
Done. The northern unit will be labeled beginning at zoom 9.
