### ISSUE TITLE
add runways (polygons) as a preset

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#387]
Realized we're not going to get these rendered in our sources if it's not a preset first.

**Comment by jakecoolidge** [comment]
See [this issue](https://github.com/nationalparkservice/places-data/issues/231)

**Comment by chadlawlis** [comment]
+1

GRTE needs this.

**Comment by chadlawlis** [comment]
`{"aeroway":"runway"}` http://wiki.openstreetmap.org/wiki/Tag:aeroway%3Drunway

cc @asouthwould

**Comment by chadlawlis** [comment]
This has been added to the spreadsheet using `{"aeroway":"runway"}` as both Line and Area.

@jimmyrocks to regenerate presets for this to go live.

**Comment by chadlawlis** [comment]
This is live.
