### ISSUE TITLE
Features tagged as 'Lake', 'Area', etc. in Places rendering as 'Building'

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#39]
I noticed in DC that features like lakes and other areas are being rendered as buildings in the vector data source nps-places-data.

Here is an example (hover over and/or click on the different polygon features that aren't buildings):
http://www.nps.gov/maps/full.html?mapId=41f2dea7-042e-494e-a879-5565b12880f2#15/38.8877/-77.0403

Looking at this same area in the Places Editor, we can see that the features are not classified as building:
http://insidemaps.nps.gov/places/edit/#background=mapbox-satellite&map=15.54/-77.0386/38.8870&overlays=park-tiles-overlay

**Comment by jimmyrocks** [comment]
Currently, every polygon that is not a parking lot is a building.
This is because we don't have a defined set of tags to use for polygons,
and when we made this dataset, we only had buildings and parking lots
represented as polygons.

This should get fixed after the tags are defined, but in the meantime, I
can add a few more tags if you'd like.

**Comment by makella** [comment]
Ah, I see.  Is there a way to make anything that isn't a building or a parking lot type='other' or something temporary until tags are defined?

That way with map products coming from the data, we can symbolize 'other' in a different way.

**Comment by jimmyrocks** [comment]
I can look into doing that in the meantime. It shouldn't be too hard.

**Comment by makella** [comment]
what do @nateirwin  and @cwlawlis802  think?

**Comment by jimmyrocks** [comment]
I made the switch, it should show up sometime in the next day or so
let me know if any of you have other suggestions

**Comment by chadlawlis** [comment]
Let me know if you need any help with this @jimmyrocks. We should be all set with the new tagging presets, as you mentioned.

**Comment by jimmyrocks** [comment]
I made the update
If you're interested, here's the change:
https://github.com/nationalparkservice/mapbox-studio-projects/commit/0101c0d758f9e0ebee016e821e7997ff992be34b

it's a little hackish, but it should be cleared up in the next week or so

**Comment by makella** [comment]
Great!

@nateirwin do you want 'other' polygons symbolized on the map?

**Comment by nateirwin** [comment]
That would be great!

**Comment by makella** [comment]
Ok, color is  #473C8B type='Other'. Showing in the map now.

**Comment by jimmyrocks** [comment]
Looks good in DC at least!

**Comment by makella** [comment]
That's the only place I could find the 'others' :)

**Comment by nateirwin** [comment]
Ok, we're good to go on this.

**Comment by jimmyrocks** [comment]
Hopefully we'll be adding a lot more categories to this in the next few
weeks
