### ISSUE TITLE
Populate carto fields for DABE

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#392]
Populated/corrected `geom_point`, which is all we'll have for a "boundary" (via https://github.com/nationalparkservice/places-data/issues/370).

@mtaylorlong can you populate the carto fields `min_zoom_label`, `min_zoom_label_long`, and `min_zoom_label_center` so a unit dot and label render in PT3?

**Comment by mtaylorlong** [comment]
I set `min_zoom_label` to 9 so it comes in just after its surrounding parks.
