### ISSUE TITLE
POI Symbol Names in CartoDB

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#394]
The last big step to prepare for implementing a POI vector overlay for Park Tiles is getting symbol names into CartoDB. @jakecoolidge and I have added a selection of new symbols to npmap-symbol-library and @nateirwin is about to push a new release of NPMap.js that will include these symbols.

I've already added all the names we'll need in the NPS_Preset_Classes spreadsheet under the `npmapSymbol` column. Blanks should be treated as NULL and we'll assign them a generic 'dot' symbol.

@jimmyrocks: You'll be in charge of getting these symbol names into our POI table in CartoDB (on Monday). Let us know if there's anything we can do to help.

**Comment by mtaylorlong** [comment]
@nateirwin: I'm thinking about our POI's with no assigned symbol. Do you think they should be `NULL` in cartodb, or should we assign them a symbol of `dot` to make the front-end code easier to write?

**Comment by nateirwin** [comment]
I'd say let's leave them `null`. I can handle everything else on the frontend.

**Comment by mtaylorlong** [comment]
Update for @jimmyrocks: Good news Jim - we've decided you don't need to write symbol names into CartoDB for now. For the initial release, we're going to create a json file to handle which POI presets translate to which symbol in our library. This will make it easier to make adjustments in the beginning, and to accommodate customization for parks in the future. We may, someday, try to write these into CartoDB, but that day is not today.

Sound good?
