### ISSUE TITLE
Remove barrier=gate from GRTE roads

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#397]
Many of GRTE's roads include the tag `{"barrier":"gate"}`, which ultimately spits the segments out as `superclass=barrier` and `class=gate`. This is not the appropriate use of the `{"barrier":"gate"}` tag (it should be added as a vertex or a way intersecting another way at the location of the actual gate) and breaks road segments when rendering in Park Tiles.

So, I am removing the `{"barrier":"gate"}` tag from all way segments in GRTE to address this. They should be added back in at the location of the gate, if ultimately added back in (and this is not clear as is given the tag is included along entire way segments).

**Comment by chadlawlis** [comment]
Done.

**Comment by nateirwin** [comment]
Yep, sorry about this. I think I messed this up when I did the initial load of GRTE's roads into Places.

**Comment by chadlawlis** [comment]
No worries!
