### ISSUE TITLE
Invalid Point Geometries

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#398]
I've come up with a list of records in the `parks` table that don't seem to have valid point geometries. Some of these have reasons for not existing (no polygons), so can have points even without polygons, and some have just gone missing.

@cwlawlis802: Will you take a look at these?

**Units with invalid point geometries:**

| unit_code | unit_name_short | unit_desig_abbr |
| --- | --- | --- |
| mapr | Manhattan Project | NHP |
| okci | Oklahoma City | N MEM |
| loea | Lower East Side Tenement Museum | NHS |
| clmo | Claude Moore Colonial Farm | ... |
| roca | Roosevelt Campobello | IP |
| ... | Coltsville | NHP |
| york | Yorktown Battlefield | NHP |
| inup | Iñupiat Heritage Center | ... |
| hatu | Harriet Tubman Underground Railroad | NM |
| tosy | Touro Synagogue | NHS |
| npnh | National Parks of New York Harbor | ... |
| pohe | Potomac Heritage | NST |
| wapa | War In The Pacific | NHP |
| aleu | Aleutian World War II | NHA |
| jame | Historic Jamestown | NHP |
| lecl | Lewis & Clark | NHT |
| mopi | Mormon Pioneer | NHT |
| noco | North Country | NST |
| oreg | Oregon | NHT |
| ovvi | Overmountain Victory | NHT |
| pine | New Jersey Pinelands | N RES |
| safe | Santa Fe | NHT |
| semo | Selma to Montgomery | NHT |
| trte | Trail of Tears | NHT |
| amme | American Memorial | Park |
| blac | Blackstone River Valley | NHC |
| cali | California | NHT |
| glec | Glen Echo | Park |
| grfa | Great Falls | Park |
| iatr | Ice Age | NST |
| natt | Natchez Trace | NST |

**Comment by nateirwin** [comment]
We don't have geometries for NSTs, NHTs, NHAs, and NHCs.

**Comment by chadlawlis** [comment]
| unit_code | unit_name_short | unit_desig_abbr | status |
| --- | --- | --- | --- |
| mapr | Manhattan Project | NHP | missing geom https://github.com/nationalparkservice/places-data/issues/179 |
| okci | Oklahoma City | N MEM | :heavy_check_mark: https://github.com/nationalparkservice/places-data/issues/243 |
| loea | Lower East Side Tenement Museum | NHS | missing geom https://github.com/nationalparkservice/places-data/issues/28 |
| clmo | Claude Moore Colonial Farm | ... | missing geom https://github.com/nationalparkservice/places-data/issues/371 |
| roca | Roosevelt Campobello | IP | missing geom https://github.com/nationalparkservice/places-data/issues/373 |
| ... | Coltsville | NHP | missing geom https://github.com/nationalparkservice/places-data/issues/182 |
| york | Yorktown Battlefield | NHP | geom needs to be created from COLO https://github.com/nationalparkservice/places-data/issues/384 |
| inup | Iñupiat Heritage Center | ... | missing geom https://github.com/nationalparkservice/places-data/issues/236 |
| hatu | Harriet Tubman Underground Railroad | NM | missing geom https://github.com/nationalparkservice/places-data/issues/178 |
| tosy | Touro Synagogue | NHS | missing geom https://github.com/nationalparkservice/places-data/issues/374 |
| npnh | National Parks of New York Harbor | ... | geom needs to be created from subunits https://github.com/nationalparkservice/places-data/issues/375 |
| pohe | Potomac Heritage | NST | NST geoms currently unpopulated |
| wapa | War In The Pacific | NHP | :heavy_check_mark: https://github.com/nationalparkservice/places-data/issues/48#issuecomment-176975235 |
| aleu | Aleutian World War II | NHA | missing geom https://github.com/nationalparkservice/places-data/issues/234 |
| jame | Historic Jamestown | NHP | geom needs to be created from COLO https://github.com/nationalparkservice/places-data/issues/384 |
| lecl | Lewis & Clark | NHT | NHT geoms currently unpopulated |
| mopi | Mormon Pioneer | NHT | NHT geoms currently unpopulated |
| noco | North Country | NST | NST geoms currently unpopulated |
| oreg | Oregon | NHT | NHT geoms currently unpopulated |
| ovvi | Overmountain Victory | NHT | NHT geoms currently unpopulated |
| pine | New Jersey Pinelands | N RES | missing geom https://github.com/nationalparkservice/places-data/issues/403 |
| safe | Santa Fe | NHT | NHT geoms currently unpopulated |
| semo | Selma to Montgomery | NHT | NHT geoms currently unpopulated |
| trte | Trail of Tears | NHT | NHT geoms currently unpopulated |
| amme | American Memorial | Park | :heavy_check_mark: this has a valid `geom_point` |
| blac | Blackstone River Valley | NHC | NHC geoms currently unpopulated |
| cali | California | NHT | NHT geoms currently unpopulated |
| glec | Glen Echo | Park | missing geom https://github.com/nationalparkservice/places-data/issues/364 |
| grfa | Great Falls | Park | to be addressed by NCR update https://github.com/nationalparkservice/places-data/issues/347 |
| iatr | Ice Age | NST | NST geoms currently unpopulated https://github.com/nationalparkservice/places-data/issues/254 |
| natt | Natchez Trace | NST | NST geoms currently unpopulated |

**Comment by chadlawlis** [comment]
So, the majority of these will come once we tackle National Trails.

Otherwise, numerous emails have been sent for the other missing units (not National Trails) to the appropriate regional POCs. There is generally little traction for these right now, so they may have to wait for Lands. We could probably insert a point label by finding the park on the map, if we really wanted a filler in the mean time.

JAME + YORK, NPNH, and GRFA can all happen soon - they will be addressed as I work through the list of possible fixes. GLEC will likely not be included in the NCR update, given nobody (NPMap, NCR, or Lands) has a boundary on file.

**Comment by chadlawlis** [comment]
@mtaylorlong feel free to close this or keep open - I'm all set with tracking these individually on my end.

**Comment by mtaylorlong** [comment]
Nice work @cwlawlis802 going through this list! Since you're tracking these individually, I'll close this issue.
