### ISSUE TITLE
Some buildings missing from vector tiles

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#399]
@nateirwin Just noticed that some (not all) buildings are missing in the latest update of PT3. I looked at the vector tiles in studio, and the missing buildings are indeed missing from the tiles. The peculiar thing is that some buildings are in the tiles, and some aren't. I have confirmed that the missing buildings are still showing up in Editor, so the issue is somewhere in the tile creation.

**Example**
![missing-buildings-1](https://cloud.githubusercontent.com/assets/4741443/12660773/c02cfd72-c5d2-11e5-9389-1522b9b89f8b.png)
![missing-buildings-2](https://cloud.githubusercontent.com/assets/4741443/12660774/c1a17908-c5d2-11e5-9cf3-95e8e5cb1360.png)

@jimmyrocks: Can you solve this mystery?

**Comment by mtaylorlong** [comment]
Jim rendered tiles again last week to try to resolve our missing buildings issue, but as of Monday morning, we're still missing buildings from the tiles, including the Snow Lodge in YELL (example above). 

@jimmyrocks: Do you think this is happening on the Mapbox side? Any further ideas? I'd love to get this solved asap. A few missing buildings in one spot means there could be much more going unnoticed.

cc: @nateirwin, @cwlawlis802, @jakecoolidge.

**Comment by jimmyrocks** [comment]
I can run it again an see if that fixes it, but we may need to open a
support ticket with mapbox

**Comment by mtaylorlong** [comment]
We're going to send a support email to Mapbox. I'm including another screenshot below that shows the vector tile view from inside Mapbox Studio Classic:

![screen shot 2016-02-01 at 10 43 39 am](https://cloud.githubusercontent.com/assets/4741443/12725731/5922e662-c8d1-11e5-97d3-d755d5c95e94.png)

There's a lot to look at here since the OSM data is showing up underneath, but the NPS building data is visible at the bottom right in a lighter grey color. You can see that there's no such shape for the Snow Lodge.

**Comment by mtaylorlong** [comment]
Other relevant details:
- Location where this Snow Lodge issue is visible: [http://insidemaps.nps.gov/park-tiles-3/#18/44.45670/-110.82842](http://insidemaps.nps.gov/park-tiles-3/#18/44.45670/-110.82842)
- Data Source (Vector Tiles): **Places: Automated Data** `nps.nps-places-data` [link](https://www.mapbox.com/studio/data/nps.nps-places-data/)
- Data source is comprised of three subsets:
  - `nps_places_polygons` (where we're seeing missing buildings)
  - `nps_places_poi`
  - `nps_places_roads_and_trails`
- My best guess at the vector tile in question: `14/3148/5928`

**Comment by mtaylorlong** [comment]
**Update**: There is a way to request raw vector tiles through an API. We tile down to z14, so I identified the tile in question at z14:

http://a.tiles.mapbox.com/v4/nps.b0add3e6/14/3148/5928.png?access_token=pk.eyJ1IjoibnBzIiwiYSI6IkdfeS1OY1UifQ.K8Qn5ojTw4RV1GwBlsci-Q

![tile](https://cloud.githubusercontent.com/assets/4741443/12930838/d249bd4c-cf37-11e5-8d84-449066539d6a.png)

This URL will request the raw vector tile:
http://a.tiles.mapbox.com/v4/nps.nps-places-data/14/3148/5928.vector.pbf?access_token=pk.eyJ1IjoibnBzIiwiYSI6IkdfeS1OY1UifQ.K8Qn5ojTw4RV1GwBlsci-Q

**This vector tile is only 53 KB.** I believe the limit is 500 KB. As long as I've done this correctly, I think this confirms that _the issue is not the vector tile size_.

@jimmyrocks: Do you agree?

**Comment by mtaylorlong** [comment]
@jimmyrocks Solved this one yesterday. There was a caching issue in the tiles. He went through and updated everything to refresh and our buildings have returned!
