### ISSUE TITLE
Wrong location for Upper Delaware 

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#4]
https://github.com/nationalparkservice/park-tiles/issues/127

**Comment by jimmyrocks** [comment]
This is a strange problem. The location of Upper Delaware is actually correct in the database (as you can see if you zoom in). It looks like the click gets detected as being over the invisible label for Upper Delaware when you click on the Vanderbilt site point.

**Comment by jimmyrocks** [comment]
Is this still a problem? / Can't replicate

**Comment by nateirwin** [comment]
Just looked at it, and it may still be an issue. I think their comment was about zoom level 7 specifically, where the label appears to be over Poughkeepsie but then shifts way west at zoom levels 8-9 until it is actually over the park itself.

Not sure if we should consider this a `places-boundaries` issue; it might just be cartography.

**Comment by nateirwin** [comment]
http://www.nps.gov/npmap/tools/park-tiles/compare/#7/41.676/-75.010

**Comment by jakecoolidge** [comment]
That's interesting. The label appears at z7, but the park appears at z8. So, visually, you associate the label with one of the points located on the Hudson. I'll look at the style and see if I can understand what's happening there--either with the zoom level the park point/polygon appears at, or if shifting the label west could help.

**Comment by jakecoolidge** [comment]
The park point has a maxzoom of 5; the label and polygon have a minzoompoly of the polygon is 6. If we could up the maxzoom on the point to 6, that would be a step in the right direction.

**Comment by jakecoolidge** [comment]
Label-wise, Upper Delaware is has an ldir setting of NE, which is pushing it out towards the Hudson and Vanderbilt Mansion. I disabled the NE styling and the label centered itself over the Delaware River. I might suggest changing the ldir to N, or NW.

**Comment by jimmyrocks** [comment]
Wouldn't that put the point and label both on at Zoom 6?

**Comment by jakecoolidge** [comment]
Yes. Displaying both simultaneously would reduce the ambiguity somewhat. Unless I'm missing something.

**Comment by chadlawlis** [comment]
This appears to be fixed: http://insidemaps.nps.gov/park-tiles-3/#7/41.734/-73.553

![new york u s national park service 2016-02-02 13-26-14](https://cloud.githubusercontent.com/assets/1238636/12763244/8e20c8b8-c9b0-11e5-9d0f-51957fc932ae.jpg)

Closing.

**Comment by jimmyrocks** [comment]
This was a weird issue with the UTF grid, I'm glad to see it's fixed!
