### ISSUE TITLE
Building entrance/exit points going out to CartoDB as `type=building`

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#401]
http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=21.18/-110.71530/43.66022
http://localhost:1945/park-tiles-3/#19/43.66063/-110.71585
https://nps.cartodb.com/api/v2/sql?q=SELECT%20*%20FROM%20points_of_interest%20WHERE%20cartodb_id=4767370

**Comment by jimmyrocks** [comment]
Presets were changed to fix this issue, and all changed presets were recreated using this script:
https://github.com/nationalparkservice/places-api/blob/master/scripts/cleanup/update_tags.sql
