### ISSUE TITLE
ParkTiles 3 Submit Feedback Button

### ISSUE THREAD

**Issue by frogmapr** [nationalparkservice/places-data#402]
When I click the submit feedback button on the [park tiles three basemap](http://insidemaps.nps.gov/park-tiles-3/#16/44.3851/-110.5530) It tries to open up MS outlook on my PC and so I'm not able to email any feedback as I don't have MS Outlook.

Hope this helps!

Neal

**Comment by nateirwin** [comment]
Hi Neal,

Sounds like you have Outlook setup as your default email program. If you update that setting, you should be good to go.

**Comment by frogmapr** [comment]
Yep that was it!

Thanks :D
