### ISSUE TITLE
HAMP boundary needs correction

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#42]
Nigel Shaw (nigel_shaw@nps.gov) identified a mis-drawn boundary for Hampton National Historic Site. I'll update once we receive the screenshot.

**Comment by jakecoolidge** [comment]
We didn't receive a follow-up email with screenshots, but upon review I think I see what he's saying. The map from Harper's Ferry Center is above and our map is below. The main boundary follows Hampton Lane and then jogs north towards Saint Francis Road; our boundary appears to be shifted about 1,000 ft south.

![hamp-hfc-map](https://cloud.githubusercontent.com/assets/11392872/9041323/d48250be-39c4-11e5-9ba2-c8da8d1f58bf.png)
![hamp-park-tiles](https://cloud.githubusercontent.com/assets/11392872/9041324/d4924a96-39c4-11e5-9a19-b8e443847562.png)

**Comment by jimmyrocks** [comment]
Updated with IRMA/Lands Boundary
