### ISSUE TITLE
Compare GATE boundary to Lands

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#421]
The latest Lands release from 20160107 differs greatly from what we have in Places, which is pulling from a custom GATE source:

![gate](https://cloud.githubusercontent.com/assets/1238636/12770283/6a81ec26-c9dc-11e5-9532-c57fc93c90ad.jpg)

@jakecoolidge can you ask the NPNH folks what they prefer? Most of what is not covered by our current boundary is water, but there are some land differences as well.

**Comment by jakecoolidge** [comment]
The lands boundary dataset matches what GATE defines as its legislative boundary on their print maps, and is also the boundary we're using in the mobile apps. I will ask them if they're okay with integrating this into our reference dataset as well.

**Comment by chadlawlis** [comment]
Thanks @jakecoolidge :+1:

**Comment by jakecoolidge** [comment]
Mark C. is in favor of switching to the Lands boundary/legislative boundary.

**Comment by chadlawlis** [comment]
@jakecoolidge revisiting this issue - can you confirm that GATE wants to use the Lands boundary in Park Tiles instead of the current boundary (see screenshot above)?

**Comment by chadlawlis** [comment]
@jakecoolidge to revisit once more with Mark for confirmation. See "GATE Legislative Boundary in NPS Places" email.

**Comment by chadlawlis** [comment]
We are now good to go with the transition to the latest Lands release (20170630), per @jakecoolidge's request. The legislative boundary will be used in combination with parcel boundaries in PT.

Updated in DB via:

`psql -U postgres -d places_boundaries_v2 -c "UPDATE parks_poly SET geom_poly = (SELECT wkb_geometry FROM lands_20170630 WHERE unit_code = 'GATE'), data_source = 'Land Resources Division' WHERE unit_id = 158;"`

`psql -U postgres -d places_boundaries_v2 -c "UPDATE parks SET unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 158) WHERE unit_id = 158;"`

Will go live once boundaries are regenerated.

**Comment by chadlawlis** [comment]
This is now live in PT.
