### ISSUE TITLE
Transition DENA from WSD_Parks to Lands

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#428]
Denali National Park & Preserve (DENA) is currently pulling from WSD_Parks, and is identical (excluding inner boundaries) to the latest Lands release from 20160107:

![dena](https://cloud.githubusercontent.com/assets/1238636/12801722/1b414e2a-ca9c-11e5-9585-488379dfbbce.jpg)
_cross hatched is WSD_Parks, pink base layer is Lands_20160107_

The Lands boundary includes an inner line, while WSD_Parks does not.

So, going to transition to Lands.

**Comment by cwlawlis802** [comment]
Note: the inner geometry will not be maintained, given `ST_Union(wkb_geometry)`. Mapbox does not currently support rendering inner line geometries in multipolygons - see more here https://github.com/nationalparkservice/places-data/issues/335#issuecomment-172139587.

**Comment by chadlawlis** [comment]
Done via:

``` sql
-- update boundary geometry from Lands table
UPDATE parks_poly
SET geom_poly = (SELECT ST_Union(wkb_geometry) FROM lands_20160107 WHERE unit_code = 'DENA')
WHERE unit_code = 'dena';

-- update parks table attributes via new boundary
UPDATE parks
SET data_source = 'Land Resources Division'
WHERE unit_code = 'dena';
```

**Comment by chadlawlis** [comment]
Note: the inner geometry will not be maintained, given `ST_Union(wkb_geometry)`. Mapbox does not currently support rendering inner line geometries in multipolygons - see more here https://github.com/nationalparkservice/places-data/issues/335#issuecomment-172139587.

**Comment by chadlawlis** [comment]
Reopening this - @jimmyrocks and I are looking into a way of maintaining these inner boundaries, given it delineates the National Preserve from the Park.

**Comment by chadlawlis** [comment]
Okay, this is all set now with the geometry in parks maintaining the inner boundaries separating the two National preserve areas from the large Park area:

![dena_output](https://cloud.githubusercontent.com/assets/1238636/12827542/7ac4245c-cb3d-11e5-8c8f-8a170532190c.jpg)
_output DENA geometry currently in `parks_

Unfortunately we couldn't figure out how to do this successfully in PostGIS, so this is a bit of a manual process. I took the boundary from Lands and in QGIS ran "Vector" > "Geometry Tools" > "Singleparts to multipart" using `unit_code` as the "Unique ID field". This output a single multipolygon geometry maintaining the inner boundary lines, as desired. This output was then loaded onto the server and used to updated DENA's `geom_poly` in `parks_poly` via [the usual process](https://github.com/nationalparkservice/npmap-scratch/blob/master/database/boundaries/README.md#updating-a-boundary-in-postgresql).

**Comment by chadlawlis** [comment]
For reference, the SQL @jimmyrocks conjured up:

``` sql
UPDATE
  "parks_poly"
SET
  "the_geom" = (
    SELECT
    ST_Multi(
      St_Collect(
        "dumped_geom"."geom"
      )
    )
    FROM (
      SELECT
      lower("lands_20160107"."unit_code") AS "unit_code",
      (ST_Dump("lands_20160107"."wkb_geometry")).geom AS "geom"
      FROM
      "lands_20160107"
      WHERE
      lower("lands_20160107"."unit_code") = "parks_poly"."unit_code"
    ) AS "dumped_geom"
    GROUP BY "dumped_geom"."unit_code"
  )
WHERE
  "parks_poly"."unit_code" = 'dena';
```

Which produced this:

![qgis 2 10 1-pisa 2016-02-04 11-57-14](https://cloud.githubusercontent.com/assets/1238636/12827777/8656fed8-cb3e-11e5-89bc-e6bbfc764572.jpg)

This should be possible in PostGIS, but we're obviously doing something wrong here.
