### ISSUE TITLE
Support for parking_aisle

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#43]
It looks like we aren't currently supporting `service=parking_aisle`. This is something I map regularly in both OpenStreetMap and Places. Did we leave it out on purpose, or was this an oversight?

http://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle

**Comment by chadlawlis** [comment]
Hm, that seems to be an oversight. It's in the original [mapathon schema guide](https://github.com/nationalparkservice/places-data/wiki/Places-Data-Schema-Guide#1-roads) but didn't seem to make its way into the [presets doc](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272). We should definitely add this in.

**Comment by chadlawlis** [comment]
@asouthwould do you mind if I add this into the presets doc?

I think a good workflow to approach continuing changes to our presets is to flag our intention to update/add tags on Github through these issue posts in the `places-data` repo and once confirmed update/add them in the presets doc. How does that sound? I know there are other components that will be affected, like Regan's [arc2osm translation script](https://github.com/regan-sarwas/arc2osm), so we'll need to make sure we are keeping everything up to date.

**Comment by asouthwould** [comment]
I think we never got around to discussing the details for parking during our mapathon... so we simply added a Parking POI with amenity=parking for points and areas. I think it makes perfect sense to add Parking Aisles. Do I understand correctly that parking_aisles will be tagged highway=service, service=parking_aisle? Once you add this to the spreadsheet, I will make sure there's a way to include these in the Roads container and transfer from GIS > OSM and OSM > GIS. Does that sound reasonable?

**Comment by nateirwin** [comment]
Yep, `highway=service` and `service=parking_aisle`.

**Comment by chadlawlis** [comment]
Great, I'll add it to the spreadsheet. @asouthwould where are you pulling the `JSON_Fields` and `JSON_Terms` fields?

**Comment by asouthwould** [comment]
I pulled fields and terms from the wiki pages and included additional terms where they seemed to fit.

**Comment by chadlawlis** [comment]
Okay, parking aisle has been added to [the doc](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272) (row #104). @asouthwould could you take a look and make sure the GIS fields line up? I am not quite sure what the `Road_Values`, `Road_Default`, and `Road_GIS_Tags` fields are.

**Comment by asouthwould** [comment]
Done. I also made two additional updates: 

In column `Road_GIS_Tags`, corrected the attribute name to `RDNAME`.

In column `Trail_GIS_Tags`, added new attribute `TRLSURFACE` and mapped in column `Trail_OSM_Tags` to `surface`.

@regan-sarwas is using these columns to ensure correct data mappings in translations between GIS and OSM.

**Comment by chadlawlis** [comment]
Great, sounds like we are all set with this.
