### ISSUE TITLE
Downhill Ski Trail Discussion

### ISSUE THREAD

**Issue by asouthwould** [nationalparkservice/places-data#44]
As I update the Trail and Roads containers in preparation for the data call, I've encountered something that I want to bring to the group. I've been speaking with Kerry Shakarjian regarding the minor differences between our Trails data standard and the feature types able to be created in Places.

She has concerns over Downhill Ski Trail: 

> Downhill Ski Trails will get someone killed if its not a designated ski area. Its probably too late but if Downhill Ski Trail is more for backcountry it should be renamed to Backcountry Ski Trail or something.
> 
> It looks like Yosemite is the only NP with a ski resort in it's boundaries- Badger Pass. Do we have any  other legitimate downhill ski trails in a National Park or other units??​ ​Rocky Mountain NP used to have a ski area but its closed and the ski runs are not converted to trails.​ Plus downhill ski runs are not maintainable as a trail due to slope etc. They might be snow trails but they're not terra trails.
> 
> Based on another coworkers knowledge from working at ski areas, they usually don't allow for hiking directly up the ski runs or mountain biking. Those hiking trails differ from the downhill ski trails and use switchbacks etc. Downhill ski trails are not maintained as a trail on the ground if at all other than brushing out skier obstacles. In my opinion if it doesn't have an official classification for design (Trail Class) then we might be looking at law suits here. Trail Classes are not determined in the field, they are based on the design of a trail before a trail is built.
> 
> To me calling a downhill ski trail = hiking is a dangerous assumption. Maybe we need to add Other as a TrailUse option so this information has somewhere to go other than Hike??? 

Based on this conversation, are there any thoughts on continuing to use Downhill Ski Trail tagged as `piste:type=downhill`? 

[Wiki](http://wiki.openstreetmap.org/wiki/Key:piste:type) defines this as

> An alpine/downhill ski route.

Any thoughts on adding a Backcountry Ski Trail, which could be tagged as `piste:type=skitour, piste:grooming=backcountry`? Or simply quantifying `piste:type=downhill` with `piste:grooming=backcountry`?

[Wiki](http://wiki.openstreetmap.org/wiki/Key:piste:type) defines this as

> A recommended ski tour way or area that is generally used by many skiers during a season for the purpose of a nordic ascent and a downhill descent in the backcountry. Generally the descent is recommended near the ascent route for safety and terrain judgement and the descent is not mapped. To map an alternate descent, use piste:type=downhill with piste:grooming=backcountry. Implies piste:grooming=backcountry. 

Thoughts @nateirwin and @cwlawlis802?

**Comment by chadlawlis** [comment]
Per my comments in the `highway=path` vs. `highway=track` issue [here](https://github.com/nationalparkservice/places-editor/issues/54#issuecomment-109099417) I recommend maintaining `route=piste` and `piste:type=` to classify downhill ski, cross-country ski, snowshoe, and dogsled trails. These should not be confused with hiking trails. We can add `piste:type=skitour` for backcountry trails, if distinguishing off-piste vs. in-boundary ski trails is of concern.

**Comment by nateirwin** [comment]
I think we should support backcountry trails, as well. Then it is up to the park to decide if they use the downhill tags or the backcountry tags.

**Comment by asouthwould** [comment]
I added Backcountry Ski Trail as `piste:type=skitour` to the spreadsheet. I will update the pending container, as appropriate.

If I'm understanding comments from @cwlawlis802 then we should also update the spreadsheet column `OSM_Tag` to reflect the removal of the `highway` tag. 

However, if any of the `piste:type` trails are multi-use with another type where `highway=path` or `highway=track` then the "higher order" tag exists, correct?

**Comment by chadlawlis** [comment]
Yes, we should update the `OSM_Tag` column to reflect the change to `route=piste` and `piste:type=` - I'll do this now.

Good question re: multi-use trails. I think maintaining both makes sense, given we want to avoid the combination `highway=track` and `piste:type=` without `route=piste` because `piste:type=` is only logical (and translatable to OSM) given `route=piste`. This also gives us cartographic freedom to choose how we want to render that trail - as a hiking trail, ski trail, etc.

**Comment by chadlawlis** [comment]
The `OSM_Tag` column has been [updated in the doc](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272) and winter sport trails have been added as `Piste` [in the tracing guide](http://nationalparkservice.github.io/places-tracing-guide/#piste).

**Comment by chadlawlis** [comment]
As discussed in [this issue](https://github.com/nationalparkservice/places-data/issues/53) we have chosen to remove `route=piste` given the tag's limitations documented in the wiki (only intended for use as a relation). All `piste:type=` associated features will now be tagged with only `piste:type=` along with optional fields (including `piste:difficulty=`).
