### ISSUE TITLE
Support tunnels for roads and trails

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#45]
I created this as a new issue in the Places Tracing Guide, but then realized it might get more attention here! We need to support both bridges (which are currently documented in the tracing guide) and tunnels for roads and trails.

**Comment by chadlawlis** [comment]
Both are currently supported in the editor - [bridge](https://github.com/nationalparkservice/places-editor/blob/master/data/presets/presets/nps/bridge/yes_bridge.json) and [tunnel](https://github.com/nationalparkservice/places-editor/blob/master/data/presets/presets/nps/tunnel/yes_tunnel.json) - but tunnel needs to be added to the guide so I will add that.

**Comment by chadlawlis** [comment]
Tunnel has been [added to the guide](http://nationalparkservice.github.io/places-tracing-guide/#tunnel). The [bridge description](http://nationalparkservice.github.io/places-tracing-guide/#bridge) has been updated as well.

I will close [this issue](https://github.com/nationalparkservice/places-tracing-guide/issues/2) when the GIF has been updated.
