### ISSUE TITLE
CASA labeled twice

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#454]
![park_maps___insidemaps](https://cloud.githubusercontent.com/assets/10443/12930651/c4451882-cf36-11e5-9eb7-b6aa72d5f2a8.jpg)

**Comment by chadlawlis** [comment]
@mtaylorlong should know the solution on this one - we've dealt with this before.

There is only one record in Parks for this, probably related to a min_zoom setting of some sort.

**Comment by cwlawlis802** [comment]
Labeling okay (only once) in PT3 and Editor, however.

**Comment by chadlawlis** [comment]
Looks like its only happening at Z14-16.

**Comment by mtaylorlong** [comment]
Yeah. This seems to happen when a label point is close to a tile edge and the label is being placed opportunistically. My fix for this is to "hard code" the label direction by setting `ldir_enforce` to `t` in the `parks` table.

I just made the update in the `parks` table. It should be fixed next time @jimmyrocks updates the boundaries tiles.
