### ISSUE TITLE
Move unit label points from `Parks` into new table

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#456]
Given the number of unit label records in our `parks` table (context https://github.com/nationalparkservice/places-data/issues/416) it is probably best to move these into a new, standalone table to maintain the integrity of the `parks` table as simply an index of all units with their boundaries.

Given we currently have `parks`, `parks_poly`, and `parks_line` I think a logical name for this would be `parks_point`.

cc @nateirwin @jimmyrocks @mtaylorlong

**Comment by mtaylorlong** [comment]
I suggest we call it the new table `parks_label`. The real "point" for a park is in the main `parks` table. Once we set up the new table, we could pull all the points from the `parks` table into `parks_label`, then generate new points in the `parks` table that represent true centroids. 

This change will actually require a bit of refiguring for our rendering to Mapbox by @jimmyrocks. Right now, we render park points from the `parks` table. With the new setup, we would need to render those points from the `parks_label` table, but still pull the min_zoom settings and all that from the `parks` table. It's the same way we handle the polygons and lines – it just requires some new sql.

The other change on my end would happen with editing. If I needed to edit a min_zoom setting, I would do so with the parks table, but if I needed to edit a label point's location, I would do so with the `parks_label` table. Not a big deal – I'd just have to remember not to touch the points in the `parks` table.

**Comment by nateirwin** [comment]
What do you all think about only storing polygons in the `parks` table, storing a centroid for each park in a `park_centroid` table, and storing label points in `parks_label`? If we don't have a polygon for a park, `the_geom` in `parks` will just be `null`.

**Comment by mtaylorlong** [comment]
The reason we chose to store points in the `parks` table instead of polygons was that the polygons were so big, it made it difficult to work with the table when you just wanted to modify min_zoom settings. I still vote for keeping the geometry associated with `parks` as the centroid. Alternately, we could store no geometry with the main `parks` table, keeping each geometry in it's own separate table.

**Comment by nateirwin** [comment]
I'm talking about CartoDB here

**Comment by mtaylorlong** [comment]
Ah. I see. Then yes. I thought we already kept polygons in the parks table in cartodb. Adding those other tables sounds reasonable to me.

Based on our conversation yesterday, we could make a `parks_bbox` table too... for bounding boxes.

**Comment by nateirwin** [comment]
> Based on our conversation yesterday, we could make a `parks_bbox` table too... for bounding boxes.

And a `parks_aoi` table ;-)

**Comment by mtaylorlong** [comment]
Nah. `parks_aoi` is just for me in Park Tiles. :wink:

**Comment by chadlawlis** [comment]
So, what's the consensus on this @nateirwin @mtaylorlong? I'm kind of neutral on this so just let @jimmyrocks and I know what you're thinking and we can implement.

The one note I'll make here is that the `geom_point` in `parks` is not always the actual centroid of the unit's polygon - these have been moved on numerous occasions for cartographic reasons. So, if you wanted actual centroids for every unit we would need to regenerate these.

**Comment by mtaylorlong** [comment]
I'm proposing that we reorganize the `places_boundaries` db as outlined in issue #543.

**Comment by chadlawlis** [comment]
This is all set via #543.
