### ISSUE TITLE
Move centroid for WAPA label 

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#48]
From Justin Mills (justin_s_mills@nps.gov)

The label location for WAPA is in the middle of nowhere.  Because it is a park made up of multiple polygons, the labeling centroid is being drawn in a place that is not even near the main parts of the park.

Justin would like the label moved to one of the two following areas:

I think the best place would be in the Asan Beach Unit, which is our flagship unit and receives (by far) the most visitors:

http://www.nps.gov/npmap/tools/park-tiles/#17/13.47385/144.71042 (in the middle, more or less)

The Asan Inland Unit would also be very good:

http://www.nps.gov/npmap/tools/park-tiles/#16/13.4666/144.7161

**Comment by nateirwin** [comment]
Here's a graphic Justin sent me via email:

![inbox__104_messages_](https://cloud.githubusercontent.com/assets/10443/10771468/8c4d5eb2-7cb6-11e5-880e-f7e036937e27.jpg)

**Comment by mtaylorlong** [comment]
I'm going to tackle this one finally, next time I get into the places table. I agree with the recommended primary placement that Mamata suggested.

Whether or not we could store a second point for the same unit code is an interesting thought experiment...
cc: @cwlawlis802.

**Comment by chadlawlis** [comment]
Shooting from the hip here, but we could probably add another label-only record to `parks` with the unit name and `geom_point` to add another label to a different location.

Not sure this is ideal, though - cc @jimmyrocks

**Comment by jimmyrocks** [comment]
I think Chad's approach makes the most sense. I think this is how we do
ELIS and ALCA

**Comment by mtaylorlong** [comment]
I think this makes sense. However, I think we need to be clear that this is different than how we handle subunits (like ELIS and ALCA). This approach would only apply to single units that have separated holdings that need to be independently labeled at higher zoom levels. In these cases, we will store an extra point record for the same unit. In some cases, we may even name this record slightly differently if the HFC maps do so (ex: Park Name - North Unit).

This will have to be a manual process though. In the example above, we're only adding an additional label to the other large chunk of the park, not the smaller fragments. I'll have to go in and properly set the min_zoom settings for these duplicate labels too.

@cwlawlis802: If you're up for trying this out, let me know when you're ready so I can update the min_zoom stuff.

**Comment by nateirwin** [comment]
How would we handle this example: Petersburg National Battlefield is made up of three different distinct areas, all of which have their own names but really aren't sub-units:
- The Eastern Front
- The Western Front
- Grant's Headquarters at City Point

Currently the label displays in the middle of nowhere for the park. The primary area is the Eastern Front, but each of the other areas should be labeled as well.

http://insidemaps.nps.gov/park-tiles-3/#12/37.2254/-77.4568

**Comment by chadlawlis** [comment]
@mtaylorlong sounds good. Do you need anything from me to move forward with this?

@nateirwin this appears to be a similar issue. Sounds like we can add additional label-only records so that each parcel is assigned a label.

**Comment by mtaylorlong** [comment]
I'm tempted to add "The Eastern Front', "The Western Front", and "Grant's Headquarters at City Point" as locales. However, it would be more consistent to add them as additional records in the points table.

The tricky part with this example is that if we create a record called "Petersburg - Western Front" then we'll look back at the main record and wonder why it's not called "Petersburg - Eastern Front". This is why I was tempted to use Locales instead. This may require and in-person discussion to come to a final conclusion...

**Comment by nateirwin** [comment]
Locales actually may be a good solution in this case, as the separate parcels aren't official subunits. Maybe I'll just go with that... should I add them to Places?

**Comment by chadlawlis** [comment]
@nateirwin locales seem to make sense for your example, given they are actual and distinct areas recognized by the park. I say go ahead and add to Places.

**Comment by mtaylorlong** [comment]
Locales are certainly much easier to implement. I'll make sure that the locale labels have a touch of green to suggest their NPS-ness. If we want to be really clear that these units belong to the park, we can address that in the locale label. Example: "Short Park Name - Locale Name". 

So let's add locale names for Petersburg.

**Comment by chadlawlis** [comment]
@mtaylorlong if you can get me coordinates for the additional label-only records for WAPA I can add these to the Parks table. If you feel like going in and doing it all at once (including `min_zoom` fields), use this example query for populating the `geom_point`, using the appropriate (different) coordinates:

``` sql
UPDATE
        parks
    SET
        geom_point = (
            SELECT
                    ST_GeomFromText ('POINT(-81.49133831262589 41.47369879064407)')
        )
    WHERE
        unit_code = 'wapa'
;
```

**Comment by nateirwin** [comment]
Alright, locales added to PETE.

I'll stop hijacking the thread now.

**Comment by mtaylorlong** [comment]
@cwlawlis802: Let's go with this.

lat: 13.388666
lon: 144.655149

**Comment by mtaylorlong** [comment]
@cwlawlis802: I just looked into this issue to check it off my list, and I couldn't find the point in QGIS. It seems like it might be an invalid geometry. I think this is included in the general issue #398.

**Comment by chadlawlis** [comment]
WAPA's `geom_poly` is a valid MULTIPOLYGON in 3857 - updated the `geom_point` via

``` sql
`UPDATE parks SET geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_code = 'wapa') WHERE unit_code = 'wapa'`
```

Centroid is all set. We will need to manually create custom label points to address the label per area issue from above.

**Comment by chadlawlis** [comment]
I set the primary label point over the area to the north, per https://github.com/nationalparkservice/places-data/issues/48#issuecomment-151633293:

``` sql
UPDATE parks SET geom_point = (SELECT ST_GeomFromText('POINT(13.46524348959541 144.71395790576932)', 3857)) WHERE unit_code = 'wapa';
```

**Comment by chadlawlis** [comment]
I can also set another point over the area to the south, using the coordinates @mtaylorlong provided:

``` sql
SELECT ST_GeomFromText('POINT(13.388666 144.655149)', 3857)
```

but I will have to insert this as a new record. @jimmyrocks @mtaylorlong should I replicate all existing attributes for WAPA into a new record with a new unit_id? We should think this through a little more before inserting label-only records, to make sure everything links up appropriately.

**Comment by chadlawlis** [comment]
See context for decisions here https://github.com/nationalparkservice/places-data/issues/416.

Southern label-only point added via:

``` sql
INSERT INTO parks (
  unit_id,
  unit_name_short,
  unit_name_long,
  unit_desig_abbr,
  unit_desig_full,
  unit_code,
  geom_point,
  data_source)
VALUES (
  (SELECT max(unit_id) + 1 FROM parks),
  (SELECT unit_name_short FROM parks WHERE unit_id = '404'),
  (SELECT unit_name_long FROM parks WHERE unit_id = '404'),
  (SELECT unit_desig_abbr FROM parks WHERE unit_id = '404'),
  (SELECT unit_desig_full FROM parks WHERE unit_id = '404'),
  (SELECT unit_code FROM parks WHERE unit_id = '404'),
  (SELECT ST_GeomFromText('POINT(13.388666 144.655149)', 3857)),
  'Label-only');
```

**Comment by chadlawlis** [comment]
Okay @mtaylorlong, handing off for carto field population. `unit_id = '464'`.

**Comment by chadlawlis** [comment]
@mtaylorlong pointed out that the `geom_point` is showing up on Null Island.

We realized that when adding these coordinates we need to do so in 4326, then convert to 3857. I also realized that `ST_GeomFromText()` requires lon lat, not lat lon. So, to fix:

``` sql
-- reset point coordinate in 4326 for primary northern point
UPDATE parks
SET geom_point = (SELECT ST_GeomFromText('POINT(144.71395790576932 13.46524348959541)', 4326))
WHERE unit_id = '404';

-- reset point coordinate in 4326 for label-only southern point
UPDATE parks
SET geom_point = (SELECT ST_GeomFromText('POINT(144.655149 13.388666)', 4326))
WHERE unit_id = '464';

-- convert to 3857
UPDATE parks
SET geom_point = ST_Transform(ST_SetSRID(geom_point, 4326), 3857)
WHERE unit_code = 'wapa';
```

**Comment by mtaylorlong** [comment]
Done! The second WAPA label (southern unit) will appear at zoom 12.
