### ISSUE TITLE
Add new presets

### ISSUE THREAD

**Issue by heidiogle** [nationalparkservice/places-data#50]
Hi all!

Here are some feature types we would like to see added (all as points unless noted):
1. ATM
2. Bike Rack
3. Brochure Box
4. Bulletin Board
5. Canyoneering Route (line)
6. Climbing Route (line)
7. Continental Divide (line)
8. Driving Tour (line)
9. Dumpster
10. Education Center
11. Electric Vehicle Parking
12. Flag Pole
13. Floating Restroom
14. Fish Cleaning
15. Fish Hatchery
16. Gate
17. Gazebo
18. Grill
19. Graveyard
20. Horseback, riding (rental, guided tour)
21. Interpretive Sign
22. Mailbox
23. Museum
24. Picnic Table
25. River Access
26. Roadside Pullout (point, line or polygon)
27. Sculpture
28. Tornado Shelter
29. Trail Register
30. Unmaintained Route (line)
31. Zebra Mussel Decontamination Station

Here are some feature types we would like to see removed:
1. Building Under Construction - Consider removing this as a safety issue and a data maintenance issue.  We don't want to public attracted to construction sites and we don't want to have to remember to update Places once construction is completed.
2. Primary, secondary, tertiary & trunk links - Consider removing these they require research to understand and they do not currently exist within datasets.

We would like to suggest the following changes to existing presets to match public knowledge/usage:
1. Viewpoint – Consider changing to Overlook to match current park data and HF maps
2. Sanitary Disposal Station – If this refers to an RV Dump Station, consider changing to RV Dump Station or simply Dump Station. The public and park staff are far more likely to recognize this feature as Dump Station.
3. Campfire – Consider making this Campfire Ring. Most parks that allow fires generally only allow them in designated fire rings, especially those that have this data.
4. Primary, secondary, tertiary, trunk roads, unclassified roads, unknown road - Consider making this just Road.  Perhaps breaking roads out into 2WD, 4WD, dirt, paved, etc. is necessary.

Here are some feature types to discuss further:
1. Wheelchair Accessible – It is unclear what this indicates. This seems to be more an attribute of another feature type (like a restroom or trial) than a stand-alone feature type.
2. Garage & Garages – Is there a difference?
3. Point of Interest – If something is not in the presets, is this the catch-all?

We would also like to see support for warning validators/law enforcement/superintendents/cultural resource chiefs/etc when certain feature types are added, that is, those that could be deemed sensitive or non-public information by certain parks.  Examples of these would include:
1. Apartments
2. Administrative Office
3. ATV trail
4. Cabin
5. Canal
6. Cave Entrance
7. Cemetery
8. Commercial Building
9. Dam
10. Detached Home
11. Dormitory
12. Grave
13. Graveyard
14. Headquarters
15. Historic Building
16. Historic Mine
17. Historic Ruins
18. House
19. Hut
20. Industrial Building
21. Military Area
22. Office
23. Quarry (Mine)
24. Reservoir
25. Residential Building
26. Residential Road
27. Retail Building
28. Row House
29. School Building
30. Service Road
31. Shaft (Mine)
32. Shed
33. Spring
34. Stable
35. Static Mobile Home
36. Tower
37. Tunnel
38. University Building
39. Warehouse
40. Water Well

**Comment by chadlawlis** [comment]
Thanks for taking the time to put this together. We will take a look through and get back to you with responses when we can. Some of this we can probably cover on the data call as well, now that it is spelled out explicitly.

**Comment by cwlawlis802** [comment]
@heidiogle are you okay with closing this out? We have been addressing these requests through comments on the [Tag Outline](https://docs.google.com/document/d/1G-Jx5OcYdkYMKNVuhhsg-WyFqqeGrRRBIU5dhjG7_-U/edit) doc on our regular Places tagging calls.

**Comment by chadlawlis** [comment]
Adding remaining requested and agreed upon presets from our latest Places tagging call, to be implemented before our first tagging freeze:

### Points of Interest

| Superclass | Class | Type | Suggested Tag |
| --- | --- | --- | --- |
| Building | Agricultural | Ranch | `{"landuse":"farmland"}` |
| Locality | Region | Cultural Landscape | `{"place":"locality","historic":"landscape"}` |
| Locality | Region | Historic District | `{"place":"locality","historic":"district"}` |
| Locality | Region | Junction | `{"place":"locality","locality_type":"junction"}` |
| Miscellaneous | Art | Totem Pole | `{“man_made”:”totem_pole”}` |
| Natural Feature | Desert | Desert | `{"natural":"desert"}` |
| Natural Feature | Grassland | Plain | `{"natural":"grassland","grassland_type":"plain"}` |
| Natural Feature | Grove | Grove | `{"natural":"grove"}` |
| Natural Feature | Rock Formation | Pillar | `{"natural":"rock", "rock_type":"pillar"}` |
| Natural Feature | Thermal | Mud Pot | `{"natural":"mud"}` |
| Natural Feature | Valley | Canyon | `{"natural":"canyon"}` |
| Service | Airport | Seaplane Base | `{"seamark:type":"seaplane_landing_area"}` |
| Service | Shopping | Gift Shop | `{"shop":"gift"}` |
| Water Recreation | Access | Water Access | `{"natural":"water"}` |
| Water Recreation | Boat | Boat Dock | `{"man_made":"pier","mooring":"yes"}` |
| Water Recreation | Boat | Boat Storage | `{"amenity":"boat_storage"}` |

### Area

| Superclass | Class | Type | Suggested Tag |
| --- | --- | --- | --- |
| Water Recreation | Boat | Boat Dock | `{"man_made":"pier","mooring":"yes"}` |
| Building | Miscellaneous | Fortification | `{"historic":"archaeological_site","site_type":"fortification"}` |

### Line

| Superclass | Class | Type | Suggested Tag |
| --- | --- | --- | --- |
| Natural Line | Valley | Canyon | `{"natural":"canyon"}` |
| Railroad | Railroad | Railroad | `{"railway":"rail"}` |
| Trail | Unmaintained | Unmaintained Route | `{"highway":"path","mainenance":"no"}` |

**Comment by cwlawlis802** [comment]
Copying over altNames for "Pillar": `["chimney", "monument", "pinnacle", "pohaku", "rock tower"]`

Copying over altNames for "Plain": `["flat", "meadow"]`

**Comment by chadlawlis** [comment]
All new presets have been added to the spreadsheet and are live in Editor.
