### ISSUE TITLE
Compare CAHA WSD_Parks boundary to Lands

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#513]
Currently pulling from WSD_Parks, which is noticeably different than the latest Lands release from 20160107:

![caha](https://cloud.githubusercontent.com/assets/1238636/12958569/88b85d10-cfef-11e5-9b0a-c2442a54d8f5.jpg)

cc @jakecoolidge

**Comment by jakecoolidge** [comment]
Interesting; the Lands boundary includes the Pea Island NWR, which typically isn't depicted on printed maps as within the CAHA boundary. (The WSD boundary resembles typical depictions.)

**Comment by chadlawlis** [comment]
From Dave @ CAHA, 2/10/16:

> Short story, I believe we want to continue to display CAHA just like the HFC map, with Pea Island NWR as its own distinct area.
> Longer story, the land and facilities of Pea Island NWR fall under NPS jurisdiction, with an agreement with the USFWS for them to have and manage the refuge.

So, let's keep this as-is until instructed otherwise by the park.

Thanks for reaching out about this @jakecoolidge.

**Comment by jakecoolidge** [comment]
:+1:
