### ISSUE TITLE
VOYA labeling twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#517]
Z7 only

![voya](https://cloud.githubusercontent.com/assets/1238636/12984528/66559c44-d0ab-11e5-8298-a03e9e822e5c.jpg)

Should be an easy fix by setting `ldir_enforce` to `t` in the `parks` table (context https://github.com/nationalparkservice/places-data/issues/454#issuecomment-182145144)

**Comment by chadlawlis** [comment]
Hm, `ldir_enforce` already set to `t`.

Handing over to you, @mtaylorlong.

**Comment by mtaylorlong** [comment]
This should resolve itself once @jimmyrocks pushes the latest updated vector tiles to Mapbox.

**Comment by mtaylorlong** [comment]
I've confirmed that the new boundaries update has resolved this issue.
