### ISSUE TITLE
Consider labeling PULL + INDU sooner

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#519]
`min_zoom_label` currently set to Z8 for PULL, Z6 for INDU, but looks like there may be some real estate to label sooner:

![pull](https://cloud.githubusercontent.com/assets/1238636/12984805/c212a6ac-d0ac-11e5-91a4-fe69ca9aaecc.jpg)

Feedback via Lands regional/national office https://github.com/nationalparkservice/places-data/issues/515.

**Comment by mtaylorlong** [comment]
The label settings you're seeing (z6 and z8) are my update. Once these are pushed to mapbox, the park labels will show up much sooner.

**Comment by mtaylorlong** [comment]
With the new boundary update, Indiana Dunes is now labeled at z6 and Pullman is labeled at z8.
