### ISSUE TITLE
CUVA labeling twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#521]
Z8-9

![cuva](https://cloud.githubusercontent.com/assets/1238636/12985135/4070c3b6-d0ae-11e5-8a05-d838b8814daa.jpg)

`ldir_enforce` currently set to `t` so not sure what's going on here.

**Comment by mtaylorlong** [comment]
This should be resolved once @jimmyrocks pushes out updates to Mapbox.

**Comment by mtaylorlong** [comment]
I've confirmed that the new boundaries update has resolved this issue.
