### ISSUE TITLE
FOUS labeling twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#522]
Z8-9

![fous](https://cloud.githubusercontent.com/assets/1238636/12985316/21a59b36-d0af-11e5-90f6-3b413c956b85.jpg)

`ldir_enforce` currently set to `t` so not sure what's going on here.

**Comment by mtaylorlong** [comment]
This should be resolved once @jimmyrocks pushed these updates to Mapbox.

**Comment by mtaylorlong** [comment]
I've confirmed that the new boundaries update has resolved this issue.
