### ISSUE TITLE
WICL boundary not rendering

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#524]
`min_zoom_poly` set to Z14 but not rendering at any zoom level, only a point:

![wicl](https://cloud.githubusercontent.com/assets/1238636/12985661/0348d408-d0b1-11e5-8450-ca2ea5e4b7b4.jpg)

We have a boundary for this, see https://github.com/nationalparkservice/places-data/issues/523.

**Comment by mtaylorlong** [comment]
This should be resolved once @jimmyrocks pushed these updates to Mapbox.

**Comment by mtaylorlong** [comment]
I've confirmed that the new boundaries update has resolved this issue. Slick Willy (as we call him in Arkansas) will be proud.
