### ISSUE TITLE
ULSG labeling twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#525]
Z10-14

![ulsg](https://cloud.githubusercontent.com/assets/1238636/12985916/079e087e-d0b2-11e5-9028-8ac67e3eb3de.jpg)

`ldir_enforce` currently set to `t` so not sure what's going on here.

**Comment by mtaylorlong** [comment]
This should be resolved once @jimmyrocks pushed these updates to Mapbox.

**Comment by mtaylorlong** [comment]
I've confirmed that the new boundaries update has resolved this issue.
