### ISSUE TITLE
JEFF labeling late

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#526]
`min_zoom_label` set to Z6, currently labels starting at Z11:

![jeff](https://cloud.githubusercontent.com/assets/1238636/12986472/aaf64764-d0b4-11e5-8812-03f0c27addd2.jpg)

**Comment by mtaylorlong** [comment]
This should be resolved once @jimmyrocks pushed these updates to Mapbox.

**Comment by chadlawlis** [comment]
This has been confirmed as resolved.
