### ISSUE TITLE
EFMO labeling twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#527]
Z7 only

![efmo](https://cloud.githubusercontent.com/assets/1238636/12986516/ef63e17c-d0b4-11e5-83a0-246cc7200f23.jpg)

`ldir_enforce` currently set to `t` so not sure what's going on here.

**Comment by mtaylorlong** [comment]
This should be resolved once @jimmyrocks pushed these updates to Mapbox.

**Comment by mtaylorlong** [comment]
I've confirmed that the new boundaries update has resolved this issue.
