### ISSUE TITLE
Populate carto fields for new unit SEMO

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#532]
Boundary just added from Lands via #411.

Although technically the unit is a National Trail the geometry is a rectangular polygon. So, I set simp_type to point and this should generally be easier to manage (like any other unit boundary).

**Comment by mtaylorlong** [comment]
I've updated the carto fields for SEMO. The label will appear at z6 (pretty good for a little park - not much else around it).

**Comment by mtaylorlong** [comment]
I've confirmed that the new boundaries update includes this park. The label shows up at the highest level (z6), with no duplication.
