### ISSUE TITLE
AMME restroom showing VC label in Editor

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#540]
In PT3, AMME has a restroom with no name:

![amme_pt3](https://cloud.githubusercontent.com/assets/1238636/12995173/a7e4ccca-d0e2-11e5-9107-11ae3036201e.jpg)
http://insidemaps.nps.gov/park-tiles-3/#17/15.21750/145.72400

In Editor, this restroom displays a label of "American Memorial Park Visitor Center":
![amme](https://cloud.githubusercontent.com/assets/1238636/12995186/c16e3d52-d0e2-11e5-83ff-8f1877dcf9cf.jpg)
http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&map=17.24/145.72195/15.21592

Though when you click on the POI, the name field is null:
<img src="https://cloud.githubusercontent.com/assets/1238636/12995200/e19def64-d0e2-11e5-9272-23bf025aac2b.jpg" width="400px">

Any idea what's going on here @jimmyrocks?

**Comment by nateirwin** [comment]
@cwlawlis802: It looks like multiple points are stacked on top of each other in the location of the visitor center

**Comment by chadlawlis** [comment]
Yikes, good catch... 

Closing.

**Comment by chadlawlis** [comment]
http://10.147.153.193/api/0.6/changeset/data/7777/full.html
