### ISSUE TITLE
Places Boundaries Database Reorganization

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#543]
attn: @nateirwin, @cwlawlis802, @jimmyrocks, @jakecoolidge:

Last fall, we reorganized our `places_boundaries` database and made great progress in opening up control over how parks show up in PT3. We were so organized, in fact, that we got greedy and started trying to use the `parks` table to add secondary labels to the map. I've thought a lot about this, and I think we need a different approach to handling these labels. **I think it's time we separate labels into their own table.**

Separating labels into their own table means that min_zoom settings have to come with them. If we do this, then we might as well be consistent and move min_zoom settings that deal with polygons into the polygons table.  Below, I've presented my outline for a reorganized the database:
## Database Structure

Here's what I think we need:
- `parks`
- `alt_unit_codes`
- `parks_poly`
- `parks_line`
- `parks_point`
- `parks_label`
### `parks`

The master table that goes out to cartodb along with polygon boundaries. This table includes records for units and subunits only (no sites). Subunits are noted by their `subunit_of` field. `unit_id` is the primary key, used to relate geometries to these records. This table doesn't need any geometries.
- `unit_id`
- `unit_code`
- `subunit_of`
- `unit_name_short` fully formed for cartodb
- `unit_name_long` fully formed for cartodb
- `unit_desig_abbr`
- `unit_desig_full`
- `unit_area`
- `unit_region`
- `unit_state`

Note: The unit names broken apart for labeling in Park Tiles are stored in the `park_label` table.
### `alt_unit_codes`

The alternate unit codes table stores handles cases where a park has switched unit codes and may use the old one in one context and the new one in another.
### `parks_poly`

The parks polygon table stores polygon geometries for each record in the parks table (units and subunits). There is a one-to-one relationship between `parks` and `parks_poly`.
- `unit_id`
- `unit_code`
- `min_zoom_poly`
- `min_zoom_border`
- `min_zoom_tintband`
- `simp_type`
- `pt_render`
- `data_source`
- `date_created`
- `last_updated`
- `geom_poly`

Note: a subunit polygon will duplicate a part of its parent unit's polygon, but the parent unit's polygon will be a multipolygon that includes its subunits.
### `parks_line`

The parks line table stores line geometries for each record in the parks table (units and subunits). Only certain parks (those with `parks_geom.simp_type=line`) need a line geometry at smaller scales. There is a one-to-one relationship between `parks` and `parks_line`.
- `unit_id`
- `unit_code`
- `pt_render`
- `geom_line`
### `parks_point`

The parks point table stores a point geometry for each park that represents its true geographic centroid. There is a one-to-one relationship between `parks` and `parks_point`.
- `unit_id`
- `unit_code`
- `pt_render`
- `geom_point`
### `parks_label`

The parks label table stores all the point geometries used to place labels in parks. It stores labels for units, subunits, and sites, all with their own min_zoom settings. There is a one-to-many relationship between `parks` and `parks_label`.
- `label_id`
- `unit_id`
- `unit_code`
- `label_type` options: unit, subunit, site
- `label_name_short`
- `label_name_long`
- `min_zoom_label`
- `min_zoom_label_long`
- `min_zoom_label_center`
- `ldir`
- `ldir_enforce`
- `pt_render`
- `geom_label`

**Comment by mtaylorlong** [comment]
In the above strategy, I refer to **units**, **subunits**, and **sites**. I think this is a helpful way of deciding how we handle the data. The `parks` table contains records for only units and subunits, and these records all have polygon geometries. For sites (label-only), we have additional records in the `park_labels` table, but they don't need their own geometries.

Here's my best shot at defining the difference between units, subunits, and sites:
- **Unit**: A unit is the standard NPS property. Units typically have one superintendent. I think we're pretty comfortable with the concept of a unit (at least the simple ones).
- **Subunit**: A subunit is a property that may be managed by a broader unit, but _has its own unit code and nps.gov webpage_. We keep separate records and geometries for subunits because there are contexts in which we need to single them out when searching and/or zooming to bounding geometries on a map.
- **Site (label only)**: A site is a property that's part of a unit or subunit but is physically separated such that it needs its own label. We don't need to store a new record in the `parks` table for sites. A site may correspond to a unit or subunit that also has its own label. As such, a site requires a distinct record in the `parks_label` table, but nowhere else.

So, when a new park comes onboard, or an unlabelled property is brought to our attention, we can use these definitions to decide how to handle it.

**Comment by nateirwin** [comment]
This all sounds good to me.

To make sure I'm clear: CartoDB would basically just be the `parks` table plus the polygon from the `parks_poly` table - if it exists?

**Comment by mtaylorlong** [comment]
@nateirwin: That's correct.

**Comment by chadlawlis** [comment]
Just to reiterate for future reference, `parks_point` will be used for parks with only a point as a "boundary". So, after we initially run `ST_Centroid(geom_poly)` on `parks_poly` to generate `parks_point` we will be adding custom/hard-coded points that were not generated from an area geometry. So with that in mind, we will want to make sure to only re-run ST_Centroid on units where geom_poly is not null, so as to avoid overwriting the custom points as null.

The other thing to note here is that geocoding a unit with only a point boundary for PT3 search etc will have to ping the `parks_point` table. The geocoder should look in `parks_poly` for a geometry first, if null look in `parks_point` for `geom_point` on the same unit code.

**Comment by nateirwin** [comment]
I'm ready to implement in the NPMap.js geocoded when the data's out in CartoDB.

**Comment by chadlawlis** [comment]
Anything left to address here before closing @nateirwin @mtaylorlong @jimmyrocks?

**Comment by mtaylorlong** [comment]
Nope. This one's good to go!

**Comment by chadlawlis** [comment]
@nateirwin has point geocoding been implemented in the NPMap.js geocoder? Per https://github.com/nationalparkservice/places-data/issues/543#issuecomment-185963114
