### ISSUE TITLE
Add labels for JAME and YORK

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#547]
Separating out from #384.

![colo](https://cloud.githubusercontent.com/assets/1238636/13115679/f7d5c4c4-d555-11e5-9236-5dd970bc13f1.png)

http://www.nps.gov/hfc/carto/PDF/COLOmap1.pdf
http://www.nps.gov/hfc/carto/PDF/JAMEmap1.pdf
http://www.nps.gov/hfc/carto/PDF/YONBmap1.pdf

**Comment by mtaylorlong** [comment]
@cwlawlis802: I'm ready to add labels for JAME and YORK. All the settings are correct in the database. Just need geometries. Use these:
- JAME: `-76.7537927,37.2065425`
- YORK: `-76.4983177,37.2194616`

**Comment by chadlawlis** [comment]
👍 

Done via: 

``` sql
BEGIN;
UPDATE parks_label
SET geom_label = (SELECT ST_GeomFromText('POINT(-76.7537927 37.2065425)', 4326))
WHERE label_id = 437;

UPDATE parks_label
SET geom_label = (SELECT ST_GeomFromText('POINT(-76.4983177 37.2194616)', 4326))
WHERE label_id = 32;

UPDATE parks_label
SET geom_label = ST_Transform(ST_SetSRID(geom_label, 4326), 3857)
WHERE label_id = 437 OR label_id = 32;
COMMIT;
```

Will go live once boundaries are regenerated.

**Comment by chadlawlis** [comment]
These labels are good to go.

**Comment by mtaylorlong** [comment]
One final step here - adding records for JAME and YORK to `parks`, `parks_point`, and `parks_poly`. Since we're handling these as subunits, they need their own record in every table, not just the label table. 

I've created two separate polygons for the subunit areas. These will not appear in pt3 as long as we set `pt_render=false` in the `parks_poly` and `parks_point` tables.

Subunit shapefiles: [jame_york_poly.zip](https://github.com/nationalparkservice/places-data/files/314478/jame_york_poly.zip)

@cwlawlis802: Will you create these records and add these polygons? Let me know when you're done and I'll look through everything to make sure the settings are correct for pt3.

**Comment by chadlawlis** [comment]
As we discussed JAME and YORK each already have records in all tables, so we're all set there.

`min_zoom_poly` was originally 14 but has been updated to 8, the same as COLO.

I will add these geometries in for JAME and YORK and set `pt_render = 'f'` in both `parks_poly` and `parks_point`.

We'll need to confirm with @jimmyrocks that we can exclude these boundaries from rendering/generating unit codes in Places Editor (we only want the COLO boundary to render and generate the COLO unit code for all data added in this area). Otherwise, we could maintain only the point geometry for each subunit which will be hooked into the NPMap.js geocoder (to enable searching for units with only a point geometry).

**Comment by chadlawlis** [comment]
Email Roger @ COLO once this is all set to encourage him to activate Park Tiles for COLO, JAME, and YORK on NPS.gov.

**Comment by chadlawlis** [comment]
Geometries have been added and associated attributes updated via:

``` sql
BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM jame),
    data_source = 'npmap',
    pt_render = 'false',
    pt_fill = 'false'
WHERE
    unit_id = 438;
UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 438)
WHERE
    unit_id = 438;
UPDATE 
    parks_point
SET
    geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_id = 438),
    pt_render = 'false'
WHERE
    unit_id = 438;
COMMIT;

BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM york),
    data_source = 'npmap',
    pt_render = 'false',
    pt_fill = 'false'
WHERE
    unit_id = 450;
UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 450)
WHERE
    unit_id = 450;
UPDATE 
    parks_point
SET
    geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_id = 450),
    pt_render = 'false'
WHERE
    unit_id = 450;
COMMIT;
```

All set to go in and tweak any remaining carto attributes, @mtaylorlong.

**Comment by mtaylorlong** [comment]
Everything looks good to me! Should be all set after we run the tiles next.

**Comment by chadlawlis** [comment]
These are now live.

**Comment by chadlawlis** [comment]
However, JAME and YORK are not available through the geocoder, so it looks like the pseudo boundary solution didn't work. cc @mtaylorlong

**Comment by mtaylorlong** [comment]
@cwlawlis802: I think the geocoder still isn't hooked up to our new parks table.

**Comment by chadlawlis** [comment]
You're right @mtaylorlong - we'll have to test again once it is.
