### ISSUE TITLE
Add building access tags in vector tiles

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#549]
@cwlawlis802 and I have become aware of a need to distinguish between public and private buildings in the parks. We could do so very easily through the `access` tag. Some parks (like GRTE and YELL) already are using this tag in Places. With a very simple tweak to the cartocss, we could make these buildings faded, which would really help keep the focus on public areas.

@jimmyrocks: Will you tweak the rendering of places_polygons to add `access` as an attribute? I'm assuming most of the cases we're looking for will be `access=no` or `access=private`. It's up to you if you want to make them lowercase or not. I'm assuming they are all lowercase, but you never know unless you enforce it.

If this is a quick change, let us know when it's in place. The GRTE style is already set up to use it, so we'll check on the results as soon as access is rendering into the tiles.

**Comment by jakecoolidge** [comment]
I believe @jimmyrocks already added this tag to places_polygons. In the example below, the access tag is available, even though the tag hasn't been populated for the building I selected.

![screen shot 2016-02-17 at 5 16 21 pm](https://cloud.githubusercontent.com/assets/11392872/13129454/5aa3bcd4-d59a-11e5-85e7-2879e8be7635.png)

**Comment by jimmyrocks** [comment]
Can confirm, polygons include the field access with the query:
 `nps_render_polygon.tags->'access' AS "access",`

**Comment by mtaylorlong** [comment]
Oops. My bad @jimmyrocks. I was looking at a building in GRTE with no access attribute and made the general assumption about all buildings.

![screen shot 2016-02-18 at 8 57 09 am](https://cloud.githubusercontent.com/assets/4741443/13149192/bc24231c-d61d-11e5-9474-e81548965948.png)

If the building has no access tag, it looks like access won't show up as an attribute in the tiles. Does that sound right to you?

**Comment by jimmyrocks** [comment]
yeah, that's just a space saving tactic in vector tiles

**Comment by mtaylorlong** [comment]
Okay. This is all set. I've added a style that makes buildings with access of 'no' or 'private' 70% transparent. I'm also handling access=no roads the same way for consistency. I'm updating the blog post to indicate that buildings get the same treatment.

**Comment by chadlawlis** [comment]
Awesome, GRTE will be happy to have this.
