### ISSUE TITLE
Adding horseback riding + building entrance

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#55]
We have added `Horseback Riding` (POI) and `Entrance/Exit` (vertex) to the [preset spreadsheet](https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272) after a review of our old vs. new presets (these are commonly used tags that were left out).

@asouthwould could you populate the GIS tag columns in the spreadsheet for us?

**Comment by asouthwould** [comment]
In the following cases, we have two different types serving as the trailhead/access point and linear trail:
- `Canoe Access` (POI) and `Non-Motorized Watercraft Trail` (Trail)
- `Boat Launch` (POI) and `Motorized Watercraft Trail` (Trail)

In the other cases, we have a single type serving as both. For example: `Bicycle Trail` (POI and Trail).

`Equestrian Trail` currently matches the latter example and serves as both a POI for the trailhead/access point and linear trails. If we add `Horseback Riding`, then we should remove the current point option for `Equestrian Trail` and change to:
- `Horseback Riding` (POI) and `Equestrian Trail` (Trail)

My initial thought is that keeping the same type for POI and Trail, where applicable, makes our data more consistent and easier to process trailheads. Any thoughts? @cwlawlis802 @nateirwin

**Comment by chadlawlis** [comment]
This raises a good point. However, using {`highway=path`,`bicycle=yes`} isn't a very fitting preset for a POI. So, @jimmyrocks raised the idea of adding these as optional fields to `highway=trailhead`, making the bicycle trail POI preset {`highway=trailhead`,`bicycle=yes`} and the same for ATV, horse, 4wd, motorcycle, and snowmobile. We think leaving the following as separate POI and Trail make sense:

> - `Canoe Access` (POI) and `Non-Motorized Watercraft Trail` (Trail)
> - `Boat Launch` (POI) and `Motorized Watercraft Trail` (Trail)

How does this sound @asouthwould?

**Comment by asouthwould** [comment]
I like that idea a lot. Especially since it helps differentiate tagging on points vs. lines.

Shall I update the spreadsheet? I'm thinking put those items on two lines since the tagging is different in the two geometries.

**Comment by chadlawlis** [comment]
Great. Yes, please do update the spreadsheet. We'll need to add `bicycle`, `atv`, `4wd_only`, `motorcycle`, and `snowmobile` as optional fields for the `highway=trailhead` tag along with creating a new line for each POI. 

Feel free to comment here when the spreadsheet is updated and close the issue. Thanks!

**Comment by jimmyrocks** [comment]
I'll look into making a trailhead preset fields list that includes:
• bicycle
• atv
• 4wd_only
• motorcycle
• snowmobile

• horse
• foot

• motor_vehicle
• canoe

• motorcycle
• motorboat

that should keep it all in one POI
do we need to add horse=yes and foot=yes to that list as well?

**Comment by chadlawlis** [comment]
:+1: 

Yes, `horse=yes` and `foot=yes` as well.

**Comment by jimmyrocks** [comment]
I added them in the list in the previous comment

**Comment by jimmyrocks** [comment]
I'm going to add canoe=yes and motor_vehicle=yes to it as well and I'm going to call the present "Approved Uses"

**Comment by jimmyrocks** [comment]
Might as well add motorcycle and motorboat to the list so it supports all of our uses.

**Comment by chadlawlis** [comment]
Okay, so `highway=trailhead` along with the associated "approved use" encompasses all trail type POIs, including motorized and non-motorized watercraft trails now? And we are leaving the trail line presets the same?

**Comment by jimmyrocks** [comment]
Yes, that sounds correct!

**Comment by chadlawlis** [comment]
Great. Just checking so I can update the guide accordingly. So `nps/trailuse` will appear as an optional field titled "Approved Uses" and will allow the options mentioned [here](https://github.com/nationalparkservice/places-data/issues/55#issuecomment-112906061)? E.g. {`highway=trailhead`,`atv=yes`} is the POI for an ATV trail?

**Comment by jimmyrocks** [comment]
Correct

**Comment by chadlawlis** [comment]
To review, for @asouthwould's visibility:

`nps/trailuse` will appear as optional field titled "Approved Uses" for `highway=trailhead` (Trailhead), among other tags. `nps/wateruse` will appear as optional field titled "Approved Uses" for `leisure=slipway` (Boat Launch), providing `motorboat=` and `canoe=` options.

Canoe Access is it's own classification `{leisure=slipway,canoe=yes}` otherwise it will default to Boat Launch if `{leisure=slipway}`, `{leisure=slipway,motorboat=yes}`, or `{leisure=slipway,motorboat=yes,canoe=yes}`.

**Comment by chadlawlis** [comment]
Looks like we are all set here, closing out.
