### ISSUE TITLE
Update PORE boundary

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#561]
We are transitioning an area formerly rendered as GOGA to PORE, given it is PORE managed:

<img width="598" alt="pore" src="https://cloud.githubusercontent.com/assets/1238636/13164060/aceeaae6-d66f-11e5-9f24-88020844d270.png">

There is some overlap along the border, which will require a little tweaking to line up. PORE is currently pulling from WSD_Parks. Addition area data [here](https://drive.google.com/drive/u/1/folders/0B0AXEdn7N9KbYjIxN2xBOE84OU0).

**Comment by chadlawlis** [comment]
After looking at this closer I am realizing that the overlapping areas are the same in Lands (the boundary Craig provided was generated from Lands data), so unfortunately there is nothing we can do about it until either the park or Lands addresses this.

![lands_pore_goga](https://cloud.githubusercontent.com/assets/1238636/14123084/0ca9eeb2-f5bc-11e5-8e25-7b52ec95cfb0.png)

![lands_pore_goga_overlap](https://cloud.githubusercontent.com/assets/1238636/14123121/46e9c3cc-f5bc-11e5-89ee-f746d9c8ffec.png)

So, I will proceed with adding this in its current form.

**Comment by chadlawlis** [comment]
I pinged GOGA about this, and below are the various responses (see https://basecamp.com/1759697/projects/10932573/messages/56444543):

From Will, Park Ranger:

> This area is signed as GGNRA in the field and thus I would think should be included in the park area. It is managed by PORE but in the GOGA legislative boundary. 

From Craig, GIS Specialist

> Will is correct regarding Leg vs Management. The only issue is which park
> will provide content in Places. No Mobile pins are in the PORE managed GOGA
> area. PORE would be mapping trails, roads, buildings, parking and POI. Does
> PORE plan to have a mobile app too?

And finally, the deciding opinion from Michele, Chief of Interp:

> In some maps we have used different shades of green to denote areas that
> are legislatively our but not managed by us. Seems too complicated. Because
> we are not planning on populating with pins, my inclination is to only put
> managed areas.

So, this area is to be assigned to PORE.

**Comment by chadlawlis** [comment]
The WSD_Parks boundary currently in Places, before merging with the adjacent management boundary, is identical to the Lands boundary:

![pore](https://cloud.githubusercontent.com/assets/1238636/14399745/ff0aaa6e-fdac-11e5-880b-5aa39aa66c7b.png)

To generate the new merged boundary, in QGIS I did a "Union" between the WSD_Parks boundary and the PORE managed area sent along by GOGA - both of which are identical to Lands areas. I then did a "Dissolve" on the output, on `unit_code` (all 3 records had unit_code PORE), and finally did a "Singleparts to Multipart" conversion.

The result looks like this:

![pore_places](https://cloud.githubusercontent.com/assets/1238636/14399801/8b8228a0-fdad-11e5-920f-e1631ee2adad.png)

The line between the legislative PORE boundary and the adjacent management area is maintained, mirroring the legislative boundary overlapping the management area (given the two overlap, one has to overlap or take precedence over the other):

![pore_places_2](https://cloud.githubusercontent.com/assets/1238636/14399826/e53ae526-fdad-11e5-9233-cccca2c69dc2.png)

Done via:

``` sql
BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM pore)
WHERE
    unit_code = 'pore';

UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_code = 'pore'),
    data_source = 'GOGA'
WHERE
    unit_code = 'pore';
COMMIT;
```

**Comment by chadlawlis** [comment]
Will close once confirmed live in Park Tiles. 

I imagine there may be an issue with the boundary line, similar to GRSA (#693) and others with inner boundary lines maintained - but TBD.

**Comment by chadlawlis** [comment]
The tiles were regenerated on Saturday, 4/9, and while the boundary is now live it is being cut off differently at different zoom levels. It looks the same in the source http://10.147.153.191:3000/source?id=tmsource:///home/jmcandrew/dev/places-data/boundaries/database/project/nps-places-reference.tm2source as it does in Park Tiles, so something probably went wrong during the process.

We'll need to regenerate the tiles again and hope this resolves.

**Comment by chadlawlis** [comment]
Okay, this has been reverted to the original Lands boundary (without the neighboring PORE managed, GOGA legislative Lands area to the east) to save face for the time being.

Done via:

``` sql

BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM lands_20160331 WHERE unit_code = 'pore'),
    data_source = 'Land Resources Division'
WHERE
    unit_id = 327;

UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 327)
WHERE
    unit_id = 327;

UPDATE 
    parks_point
SET
    geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_id = 327)
WHERE
    unit_id = 327;
COMMIT;
```

Craig @ GOGA is reaching out to PORE to confirm approval to display this PORE managed, GOGA legislative area in question as part of PORE in Park Tiles. We will proceed if/once we have that approval in writing, to defend against any opposition. In the mean time, this area will not appear at all.

**Comment by chadlawlis** [comment]
@mtaylorlong can you upload the PORE boundary (legislative + management area in question) you merged here?

**Comment by mtaylorlong** [comment]
Here's my merged boundary: [pore_merged.zip](https://github.com/nationalparkservice/places-data/files/221912/pore_merged.zip)

Disclaimer: In some places where the two main polygons met, it was clear they were "trying" to follow the same line, but in a few places they diverged in intentional squarish lines that I thought may represent private land I shouldn't cover up. So there are a couple squares in the middle that were preserved, but there were a few other tiny fragments of open space between the two boundaries that got merged together.

@cwlawlis802: Take a look at my merge with the original two boundaries and see if it makes sense to you.

**Comment by chadlawlis** [comment]
Sounds good, thanks @mtaylorlong. Craig and I are going to wait to have PORE approval in writing to move forward with this - if/once we have that we'll review this and get a sign off from PORE before implementing.

**Comment by chadlawlis** [comment]
The original PORE boundary is now live.

Removing the "waiting-on-boundary-tiles" label but keeping this open, as the management area still needs to be addressed (waiting on Craig/PORE for confirmation on how best to move forward).

**Comment by chadlawlis** [comment]
PORE boundary to remain as is. This area will be added back in as GOGA, though GOGA is not managing any of the map data in this area, PORE is.
