### ISSUE TITLE
Update OLYM Boundary

### ISSUE THREAD

**Issue by ryanjhodge** [nationalparkservice/places-data#572]
The current Olympic NP boundary on Park Tiles is shifted and/or outdated. So much so that the main visitor center in Port Angeles is actually outside the park boundary.

![places](https://cloud.githubusercontent.com/assets/4172213/13368299/0dd5e9e4-dc9e-11e5-88bf-9c44933cc3e7.PNG)

I grabbed the latest boundary from Lands (in blue below) and overlayed it on Park Tiles:

![olym-boundary](https://cloud.githubusercontent.com/assets/4172213/13368339/58c1895e-dc9e-11e5-863f-e000f46a66da.PNG)

**Comment by chadlawlis** [comment]
Thanks for the catch @ryanjhodge. Do you have a contact at the park we could ping to confirm this change? The boundary currently in Places is likely outdated, pulling from a legacy source "WSD_Parks" which was compiled some time ago.

**Comment by chadlawlis** [comment]
From Roger @ OLYM:

> I worked with Roger Johnson and Dan Konzek (from the Fort Collins Lands office) on a draft of our boundary in 2011 and since then, we have had two legislative changes to our boundary (which are included in this shapefile).  Unfortunately, by NPS Lands standards, this is still considered draft because our regional lands office still hasn't reviewed/approved it.

New boundary [here](https://drive.google.com/open?id=0B0AXEdn7N9Kbak51WF84QTJyWGc).

Thanks for connecting us @ryanjhodge!

**Comment by chadlawlis** [comment]
Done via:

``` sql
BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT ST_Union(wkb_geometry) FROM olym),
    data_source = 'olym'
WHERE
    unit_id = 304;
UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 304)
WHERE
    unit_id = 304;
UPDATE 
    parks_point
SET
    geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_id = 304)
WHERE
    unit_id = 304;
COMMIT;
```

This will go live once boundaries are regenerated, likely tomorrow.

**Comment by chadlawlis** [comment]
This is now live.
