### ISSUE TITLE
PARA boundary is missing

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#6]
https://github.com/nationalparkservice/park-tiles/issues/120

**Comment by jimmyrocks** [comment]
Related to: https://github.com/nationalparkservice/places-data/issues/9

**Comment by jimmyrocks** [comment]
https://nationalparkservice.cartodb.com/u/nps/tables/fixed_lake/map

**Comment by jimmyrocks** [comment]
Updated in CartoDB
