### ISSUE TITLE
Address overlapping NCR boundaries in PT3

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#614]
With the NCR update #347 we have two sets of overlapping boundaries:

wamo, wwii, coga, vive, linc, kowa, mlkm, frde, jefm overlapping nama:

![nama_overlap](https://cloud.githubusercontent.com/assets/1238636/13470773/dade6f0e-e06a-11e5-8405-6980bc1c6fb4.png)

lyba overlapping gwmp:

![gwmp_overlap](https://cloud.githubusercontent.com/assets/1238636/13470799/007cbe50-e06b-11e5-83f1-142e3bc576df.png)

This will need custom attention in PT3 to render appropriately (likely removing the poly-fill for the smaller units overlapping the larger). All smaller units are subunits of the larger unit they overlap, which is set to be addressed in Editor via https://github.com/nationalparkservice/places-editor/issues/108.

**Comment by chadlawlis** [comment]
Are we okay to close this @mtaylorlong?

**Comment by mtaylorlong** [comment]
@cwlawlis802: Yes. 

In the case of NCR, I let the boundaries overlap, but I don't apply a tint bad to the overlapping boundaries to reduce visual clutter. Once we reorganize our database, I can even remove the fill on these boundaries so the green color is consistent throughout (right now, the green is darker where boundaries overlap).
