### ISSUE TITLE
Two new presets: 'Water' and 'Potable Water'

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#623]
These suggestions came in from the GIS Specialist at Death Valley.

Cc/ @cwlawlis802 and @asouthwould

**Comment by chadlawlis** [comment]
Potable water is already a preset so all set there.

What is the intention with Water vs. Potable Water?

**Comment by nateirwin** [comment]
Not sure about that. I think we're good to go on this.

Thanks!
