### ISSUE TITLE
Modify name of "Zebra Mussel Decontamination Station"

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#624]
A comment from Kerry at Lake Meade:

> Can Zebra Mussel Decontamination Station be changed to Aquatic Invasive Species Decontamination Station? We have Quagga Mussels in Lake Mead but Aquatic Invasive Species is the preferred term around here and would cover both Zebra and Quagga mussels.

Cc/ @cwlawlis802 and @asouthwould

**Comment by chadlawlis** [comment]
Fine by me.

**Comment by jakecoolidge** [comment]
I emailed with Tom P. about this, and we have a HFC symbol we can adapt for this preset once it goes live.

**Comment by chadlawlis** [comment]
The name has been changed to "Aquatic Invasive Species Decontamination Station" and the tags from `{"amenity":"boat_wash","type":"zebra_mussel"}` to `{"amenity":"boat_wash","type":"aquatic_invasive"}`.

The zebra-mussel-decontamination symbol has been removed, to be replaced with a new symbol @jakecoolidge is migrating from HFC.

The changes will go live once the presets have been regenerated - likely at the end of this week or early next week.

**Comment by chadlawlis** [comment]
@jakecoolidge any update on the HFC symbol for this?

**Comment by chadlawlis** [comment]
This is now live as "Aquatic Invasive Species Decontamination Station".

We still need to add the symbol, once we have it.

**Comment by chadlawlis** [comment]
Tracking symbol here: https://github.com/nationalparkservice/symbol-library/issues/130.
