### ISSUE TITLE
Buck Island Reef Unit Designation Missing

### ISSUE THREAD

**Issue by ryanjhodge** [nationalparkservice/places-data#625]
![capture](https://cloud.githubusercontent.com/assets/4172213/13691628/4f832cf2-e6ef-11e5-9727-6007b363bca0.PNG)

Looks like the value of the unit designation for Buck Island Reef is set to it's own alpha code (BUIS).

**Comment by chadlawlis** [comment]
Strange, thanks for the catch @ryanjhodge.

cc @mtaylorlong. This is in Park Tiles [2.1](http://www.nps.gov/npmap/tools/park-tiles/#12/17.7693/-64.6892), not [3](http://insidemaps.nps.gov/park-tiles-3/#12/17.7693/-64.6892).

**Comment by chadlawlis** [comment]
Everything looks good in the `parks` table on both the server and CartoDB.

**Comment by mtaylorlong** [comment]
Ah yes. Park Tiles 2.1 is still using our old boundaries source. This is the second boundaries issue in 2.1 that has come up in the past couple weeks. I believe it's time to update 2.1 with our new boundaries data. I should be able to take care of this by the end of the week.

**Comment by mtaylorlong** [comment]
@ryanjhodge: I've updated our tiles to our new source for boundaries, which resolves this issue.

![screen shot 2016-03-18 at 10 55 17 am](https://cloud.githubusercontent.com/assets/4741443/13885445/0b340de6-ecf8-11e5-82e1-01f47d9a7433.png)

Thanks again for identifying the issue!
