### ISSUE TITLE
Preset for park "neighborhoods"

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#63]
We talked about this some at the mapathon, but I don't believe we came to a conclusion on how we are going to handle areas of parks. It looks like we are using `place=village` currently. Is this what we are going with? And, if so, we should probably document it in the tracing guide:

![editor___places___insidemaps](https://cloud.githubusercontent.com/assets/10443/8241211/3d749588-15c5-11e5-87b4-6e7c1f42f1fd.jpg)

Cc @cwlawlis802, @makella

**Comment by chadlawlis** [comment]
Good question. I do not remember coming to a conclusion on this one, although `place=village` makes sense. We also discussed `place=hamlet` which is of smaller scale, according to the wiki, or `place=neighborhood`, which also seems to fall below `place=village` in scale.

@jimmyrocks @asouthwould any thoughts/recollections here?

**Comment by chadlawlis** [comment]
@nateirwin would this make the most sense under `Points of Interest` in the guide?

**Comment by nateirwin** [comment]
I believe that is where we decided to stash it.

Perhaps we can use all three classifications but rename them to something that makes more sense to the NPS?

Interested to hear what others have to say about this too.

**Comment by nateirwin** [comment]
Ok, @cwlawlis802: I talked to @makella about this and we agreed that we should go with one simple classification for now. So I guess we should go with `place=village` for now. We can always expand the list out in the future, if necessary.

I think we should also name the preset something that better fits the NPS. Perhaps `Park District` or just `District`?

**Comment by chadlawlis** [comment]
Okay, that sounds good. So are we intending to use this for park-specific neighborhoods (is a Park District a specific administrative unit of a park?) or is this intended for the city/town neighborhoods in which parks reside?

**Comment by nateirwin** [comment]
I don't know that all districts are administrative units, but many would be. Others may just be an area of a park that has a name. I think we'll need to be pretty flexible with this.

I don't think many of these will be city/town neighborhoods.

**Comment by chadlawlis** [comment]
It looks like Places editor currently supports [`place=locality`](https://github.com/nationalparkservice/places-editor/blob/master/data/presets/presets/nps/place/locality.json), not [`place=village`](https://github.com/nationalparkservice/places-editor/blob/master/data/presets/presets/place/village.json).

@jimmyrocks we'll need to add `place=village` in. Do we still want to support `place=locality`?

**Comment by jimmyrocks** [comment]
Locality is what is supported based on the spreadsheet.

Is this something we want to change?

**Comment by nateirwin** [comment]
I'm actually good with either, so if locality is supported already, let's just go with that.

I do think we need to change the preset name to something more meaningful to the NPS though.

**Comment by chadlawlis** [comment]
The [OSM wiki](http://wiki.openstreetmap.org/wiki/Tag:place%3Dlocality) is interesting, not sure if it falls directly in line with our use case but I'm okay with using it. 

I can update the `.json`, how about we call it `Park District`?

**Comment by nateirwin** [comment]
Park District is perfect. We may need to pivot down the road, but that should work well for now.

**Comment by chadlawlis** [comment]
Great, will rename to that and add to the guide in the `Points of Interest` section.

**Comment by chadlawlis** [comment]
Updated in editor: https://github.com/nationalparkservice/places-editor/commit/7b449fd1c0f5c8df9ba162c301553e326917f970

**Comment by jimmyrocks** [comment]
Updated in the spreadsheet:
https://docs.google.com/spreadsheets/d/1sQZRUZDe8vPu8PANxoIc5k0Pv85xNd5ae4uGJ0fwEt0/edit#gid=1063193272
