### ISSUE TITLE
Render Fortification areas in Park Tiles

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#630]
Areas tagged `{"historic":"archaeological_site","site_type":"fortification"}` do not currently render in Park Tiles 3.

There will be a number of these in GOGA, among other units.

cc @mtaylorlong

**Comment by mtaylorlong** [comment]
@cwlawlis802 and I confirmed yesterday that fortifications will display like any other building in PT3 because they are part of the superclass 'buildings'.

**Comment by nateirwin** [comment]
This came up when this preset was first added to Places, but fortifications aren't always buildings. In many parks, they are simple mounds of dirt. We don't have to explore this now, but we may have to revisit in the future.
