### ISSUE TITLE
Check all parks with ldir_enforce = 'f' for double labels

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#633]
The following parks have `ldir_enforce = 't'`, which means they are prone to a double label in Park Tiles. Let's check these manually and get rid of all double labeled parks in one broad stroke.

cc @nateirwin @mtaylorlong 

| name | unit_code | ldir_enforce | checked? |
| --- | --- | --- | --- |
| Abraham Lincoln Birthplace National Historical Park | abli | f | :heavy_check_mark: |
| Acadia National Park | acad | f | :heavy_check_mark: |
| Agate Fossil Beds National Monument | agfo | f | [#639](https://github.com/nationalparkservice/places-data/issues/639) |
| Alagnak Wild River | alag | f | :heavy_check_mark: |
| Alcatraz Island | alca | f | :heavy_check_mark: |
| Alibates Flint Quarries National Monument | alfl | f | :heavy_check_mark: |
| Allegheny Portage Railroad National Historic Site | alpo | f | :heavy_check_mark: |
| American Memorial Park | amme | f | :heavy_check_mark: |
| Anacostia Park | anac | f | :heavy_check_mark: |
| Andersonville National Historic Site | ande | f | :heavy_check_mark: |
| Aniakchak National Monument & Preserve | ania | f | :heavy_check_mark: |
| Andrew Johnson National Historic Site | anjo | f | [#650 ](https://github.com/nationalparkservice/places-data/issues/650) |
| Antietam National Battlefield | anti | f | :heavy_check_mark: |
| Apostle Islands National Lakeshore | apis | f | :heavy_check_mark: |
| Appalachian National Scenic Trail | appa | f | :heavy_check_mark: |
| Arches National Park | arch | f | :heavy_check_mark: |
| Arlington House, The Robert E. Lee Memorial | arho | f | :heavy_check_mark: |
| Arkansas Post National Memorial | arpo | f | [#651](https://github.com/nationalparkservice/places-data/issues/651) |
| Assateague Island National Seashore | asis | f | :heavy_check_mark: |
| Aztec Ruins National Monument | azru | f | :heavy_check_mark: |
| Badlands National Park | badl | f | :heavy_check_mark: |
| Bandelier National Monument | band | f | :heavy_check_mark: |
| Baltimore-Washington Parkway | bawa | f | :heavy_check_mark: |
| Benjamin Franklin National Memorial | befr | f | :heavy_check_mark: |
| Bering Land Bridge National Preserve | bela | f | :heavy_check_mark: |
| Bent's Old Fort National Historic Site | beol | f | :heavy_check_mark: |
| Big Bend National Park | bibe | f | :heavy_check_mark: |
| Big Cypress National Preserve | bicy | f | [#655](https://github.com/nationalparkservice/places-data/issues/655) |
| Big Hole National Battlefield | biho | f | :heavy_check_mark: |
| Biscayne National Park | bisc | f | :heavy_check_mark: |
| Big South Fork National River & Recreation Area | biso | f | :heavy_check_mark: |
| Big Thicket National Preserve | bith | f | :heavy_check_mark: |
| Black Canyon Of The Gunnison National Park | blca | f | :heavy_check_mark: |
| Bluestone National Scenic River | blue | f | :heavy_check_mark: |
| Boston African American National Historic Site | boaf | f | :heavy_check_mark: |
| Boston Harbor Islands National Recreation Area | boha | f | :heavy_check_mark: |
| Boston National Historical Park | bost | f | :heavy_check_mark: |
| Booker T Washington National Monument | bowa | f | :heavy_check_mark: |
| Bryce Canyon National Park | brca | f | :heavy_check_mark: |
| Brices Cross Roads National Battlefield Site | brcr | f | :heavy_check_mark: |
| Brown v. Board of Education National Historic Site | brvb | f | :heavy_check_mark: |
| Buffalo National River | buff | f | :heavy_check_mark: |
| Buck Island Reef National Monument | buis | f | :heavy_check_mark: |
| Cabrillo National Monument | cabr | f | :heavy_check_mark: |
| Canyon De Chelly National Monument | cach | f | :heavy_check_mark: |
| Castle Clinton National Monument | cacl | f | :heavy_check_mark: |
| Cape Cod National Seashore | caco | f | :heavy_check_mark: |
| Casa Grande Ruins National Monument | cagr | f | [#688](https://github.com/nationalparkservice/places-data/issues/688) |
| Cape Hatteras National Seashore | caha | f | [#690](https://github.com/nationalparkservice/places-data/issues/690) |
| Cape Krusenstern National Monument | cakr | f | :heavy_check_mark: |
| Cape Lookout National Seashore | calo | f | :heavy_check_mark: |
| Canaveral National Seashore | cana | f | :heavy_check_mark: |
| Canyonlands National Park | cany | f | :heavy_check_mark: |
| Capitol Reef National Park | care | f | :heavy_check_mark: |
| Cane River Creole National Historical Park | cari | f |  |
| Carl Sandburg Home National Historic Site | carl | f |  |
| Catoctin Mountain Park | cato | f |  |
| Carlsbad Caverns National Park | cave | f |  |
| Capulin Volcano National Monument | cavo | f |  |
| Carter G. Woodson Home National Historic Site | cawo | f |  |
| Cedar Creek & Belle Grove National Historical Park | cebe | f |  |
| Cedar Breaks National Monument | cebr | f |  |
| César E. Chávez National Monument | cech | f |  |
| Chamizal National Memorial | cham | f |  |
| Chattahoochee River National Recreation Area | chat | f |  |
| Chickamauga & Chattanooga National Military Park | chch | f |  |
| Chaco Culture National Historical Park | chcu | f |  |
| Chickasaw National Recreation Area | chic | f |  |
| Chiricahua National Monument | chir | f |  |
| Channel Islands National Park | chis | f |  |
| Chesapeake & Ohio Canal National Historical Park | choh | f |  |
| Charles Pinckney National Historic Site | chpi | f |  |
| Christiansted National Historic Site | chri | f |  |
| Chimney Rock National Historic Site | chro | f |  |
| Little Rock Central High School National Historic Site | chsc | f |  |
| Charles Young Buffalo Soldiers National Monument | chyo | f |  |
| City of Rocks National Reserve | ciro | f |  |
| Clara Barton National Historic Site | clba | f |  |
| Colorado National Monument | colm | f |  |
| Colonial National Historical Park | colo | f |  |
| Congaree National Park | cong | f |  |
| Coronado National Memorial | coro | f |  |
| Cowpens National Battlefield | cowp | f |  |
| Crater Lake National Park | crla | f |  |
| Craters of The Moon National Monument & Preserve | crmo | f |  |
| Cumberland Island National Seashore | cuis | f |  |
| Curecanti National Recreation Area | cure | f |  |
| Dayton Aviation Heritage National Historical Park | daav | f |  |
| David Berger National Memorial | dabe | f |  |
| Denali National Park & Preserve | dena | f |  |
| Devils Postpile National Monument | depo | f |  |
| De Soto National Memorial | deso | f |  |
| Devils Tower National Monument | deto | f |  |
| Death Valley National Park | deva | f |  |
| Delaware Water Gap National Recreation Area | dewa | f |  |
| Dinosaur National Monument | dino | f |  |
| Dry Tortugas National Park | drto | f |  |
| Ebey's Landing National Historical Reserve | ebla | f |  |
| Edgar Allan Poe National Historic Site | edal | f |  |
| Thomas Edison National Historical Park | edis | f |  |
| Eisenhower National Historic Site | eise | f |  |
| Ellis Island | elis | f |  |
| El Malpais National Monument | elma | f |  |
| El Morro National Monument | elmo | f |  |
| Eleanor Roosevelt National Historic Site | elro | f |  |
| Eugene O'Neill National Historic Site | euon | f |  |
| Everglades National Park | ever | f |  |
| Federal Hall National Memorial | feha | f |  |
| Fire Island National Seashore | fiis | f |  |
| First Ladies National Historic Site | fila | f |  |
| Florissant Fossil Beds National Monument | flfo | f |  |
| Flight 93 National Memorial | flni | f |  |
| Fort Bowie National Historic Site | fobo | f |  |
| Fossil Butte National Monument | fobu | f |  |
| Fort Caroline National Memorial | foca | f |  |
| Fort Donelson National Battlefield | fodo | f |  |
| Fort Dupont Park | fodu | f |  |
| Fort Foote Park | fofo | f |  |
| Fort Frederica National Monument | fofr | f |  |
| Fort Laramie National Historic Site | fola | f |  |
| Fort Larned National Historic Site | fols | f |  |
| Fort Matanzas National Monument | foma | f |  |
| Fort McHenry National Monument and Historic Shrine | fomc | f |  |
| Fort Monroe National Monument | fomr | f |  |
| Fort Necessity National Battlefield | fone | f |  |
| Fort Point National Historic Site | fopo | f |  |
| Fort Pulaski National Monument | fopu | f |  |
| Fort Raleigh National Historic Site | fora | f |  |
| Fort Scott National Historic Site | fosc | f |  |
| Fort Smith National Historic Site | fosm | f |  |
| Fort Stanwix National Monument | fost | f |  |
| Fort Sumter National Monument | fosu | f |  |
| Ford's Theatre National Historic Site | foth | f |  |
| Fort Union National Monument | foun | f |  |
| Fort Vancouver National Historic Site | fova | f |  |
| Fort Washington Park | fowa | f |  |
| Franklin Delano Roosevelt Memorial | frde | f |  |
| Frederick Douglass National Historic Site | frdo | f |  |
| Friendship Hill National Historic Site | frhi | f |  |
| Frederick Law Olmsted National Historic Site | frla | f |  |
| Fredericksburg & Spotsylvania National Military Park | frsp | f |  |
| First State National Historic Park | frst | f |  |
| Gates Of The Arctic National Park & Preserve | gaar | f |  |
| Gauley River National Recreation Area | gari | f |  |
| General Grant National Memorial | gegr | f |  |
| Gettysburg National Military Park | gett | f |  |
| George Washington Birthplace National Monument | gewa | f |  |
| Gila Cliff Dwellings National Monument | gicl | f |  |
| Glacier National Park | glac | f |  |
| Glen Canyon National Recreation Area | glca | f |  |
| Gloria Dei Church National Historic Site | glde | f |  |
| Glen Echo Park | glec | f |  |
| Governors Island National Monument | gois | f |  |
| Great Basin National Park | grba | f |  |
| Grand Canyon National Park | grca | f |  |
| Greenbelt Park | gree | f |  |
| Great Egg Harbor River | greg | f |  |
| Great Falls Park | grfa | f |  |
| Grant-Kohrs Ranch National Historic Site | grko | f |  |
| Great Sand Dunes National Park & Preserve | grsa | f |  |
| Great Smoky Mountains National Park | grsm | f |  |
| Green Springs National Historic Landmark District | grsp | f |  |
| Grand Teton National Park | grte | f |  |
| Guilford Courthouse National Military Park | guco | f |  |
| Gulf Islands National Seashore | guis | f |  |
| George Washington Carver National Monument | gwca | f |  |
| George Washington Memorial Parkway | gwmp | f |  |
| Harpers Ferry National Historical Park | hafe | f |  |
| Hagerman Fossil Beds National Monument | hafo | f |  |
| Hamilton Grange National Memorial | hagr | f |  |
| Harmony Hall | haha | f |  |
| Haleakala National Park | hale | f |  |
| Hampton National Historic Site | hamp | f |  |
| Herbert Hoover National Historic Site | heho | f |  |
| Horseshoe Bend National Military Park | hobe | f |  |
| Hopewell Culture National Historical Park | hocu | f |  |
| Home Of Franklin D Roosevelt National Historic Site | hofr | f |  |
| Hopewell Furnace National Historic Site | hofu | f |  |
| Homestead National Monument of America | home | f |  |
| Honouliuli National Monument | hono | f |  |
| Hot Springs National Park | hosp | f |  |
| Hovenweep National Monument | hove | f |  |
| Harry S Truman National Historic Site | hstr | f |  |
| Hubbell Trading Post National Historic Site | hutr | f |  |
| Independence National Historical Park | inde | f |  |
| Indiana Dunes National Lakeshore | indu | f |  |
| Iñupiat Heritage Center | inup | f |  |
| Isle Royale National Park | isro | f |  |
| James A Garfield National Historic Site | jaga | f |  |
| New Orleans Jazz National Historic Park | jazz | f |  |
| Jewel Cave National Monument | jeca | f |  |
| Jefferson National Expansion Memorial | jeff | f |  |
| Jimmy Carter National Historic Site | jica | f |  |
| John Day Fossil Beds National Monument | joda | f |  |
| John Fitzgerald Kennedy National Historic Site | jofi | f |  |
| Johnstown Flood National Memorial | jofl | f |  |
| John Muir National Historic Site | jomu | f | :heavy_check_mark: |
| Joshua Tree National Park | jotr | f | :heavy_check_mark: |
| Kalaupapa National Historical Park | kala | f | :heavy_check_mark: |
| Katmai National Park & Preserve | katm | f | :heavy_check_mark: |
| Kenilworth Park & Aquatic Gardens | keaq | f | :heavy_check_mark: |
| Kenai Fjords National Park | kefj | f | :heavy_check_mark: |
| Kennesaw Mountain National Battlefield Park | kemo | f | :heavy_check_mark: |
| Keweenaw National Historical Park | kewe | f | :heavy_check_mark: |
| Kings Mountain National Military Park | kimo | f | :heavy_check_mark: |
| Klondike Gold Rush National Historical Park | klgo | f | :heavy_check_mark: |
| Klondike Gold Rush National Historic Park - Seattle Unit | klse | t | #670 |
| Knife River Indian Villages National Historic Site | knri | f | :heavy_check_mark: |
| Kobuk Valley National Park | kova | f | :heavy_check_mark: |
| Korean War Veterans Memorial | kowa | f | :heavy_check_mark: |
| Lava Beds National Monument | labe | f | :heavy_check_mark: |
| Lake Chelan National Recreation Area | lach | f | :heavy_check_mark: |
| Lake Clark National Park & Preserve | lacl | f | :heavy_check_mark: |
| Lake Mead National Recreation Area | lake | f | :heavy_check_mark: |
| Lake Meredith National Recreation Area | lamr | f | :heavy_check_mark: |
| Lake Roosevelt National Recreation Area | laro | f | :heavy_check_mark: |
| Lassen Volcanic National Park | lavo | f | :heavy_check_mark: |
| Little Bighorn Battlefield National Monument | libi | f | :heavy_check_mark: |
| Lincoln Boyhood National Memorial | libo | f | :heavy_check_mark: |
| Lincoln Home National Historic Site | liho | f | #687 |
| Lincoln Memorial | linc | f | :heavy_check_mark: |
| Little River Canyon National Preserve | liri | f | :heavy_check_mark: |
| Lower East Side Tenement Museum National Historic Site | loea | f | :heavy_check_mark: |
| Longfellow House Washington's Headquarters National Historic Site | long | f | :heavy_check_mark: |
| Lower Saint Croix National Scenic Riverway | losa | f | :heavy_check_mark: |
| Lowell National Historical Park | lowe | f | :heavy_check_mark: |
| Lyndon Baines Johnson Memorial Grove on the Potomac National Memorial | lyba | f | :heavy_check_mark: |
| Lyndon B Johnson National Historical Park | lyjo | f | :heavy_check_mark: |
| Marsh - Billings - Rockefeller National Historical Park | mabi | f | :heavy_check_mark: |
| Mammoth Cave National Park | maca | f | :heavy_check_mark: |
| National Mall | mall | f | :heavy_check_mark: |
| Martin Luther King Jr National Historic Site | malu | f | :heavy_check_mark: |
| Manhattan Project National Historical Park | mapr | f | :heavy_check_mark: |
| Martin Van Buren National Historic Site | mava | f | :heavy_check_mark: |
| Maggie L Walker National Historic Site | mawa | f | :heavy_check_mark: |
| McLoughlin House | mcho | t | #685 |
| Mesa Verde National Park | meve | f | :heavy_check_mark: |
| Minidoka National Historic Site | miin | f | :heavy_check_mark: |
| Minute Man National Historical Park | mima | f | :heavy_check_mark: |
| Minuteman Missile National Historic Site | mimi | f | :heavy_check_mark: |
| Mississippi National River & Recreation Area | miss | f | :heavy_check_mark: |
| Martin Luther King, Jr. Memorial | mlkm | f | :heavy_check_mark: |
| Missouri National Recreational River | mnrr | f | :heavy_check_mark: |
| Montezuma Castle National Monument | moca | f | :heavy_check_mark: |
| Moores Creek National Battlefield | mocr | f | :heavy_check_mark: |
| Mojave National Preserve | moja | f | :heavy_check_mark: |
| Monocacy National Battlefield | mono | f | :heavy_check_mark: |
| Mount Rainier National Park | mora | f | :heavy_check_mark: |
| Mount Rushmore National Memorial | moru | f | :heavy_check_mark: |
| Muir Woods National Monument | muwo | f | :heavy_check_mark: |
| Natural Bridges National Monument | nabr | f | :heavy_check_mark: |
| National Capital Parks - East | nace | f | :heavy_check_mark: |
| National Mall & Memorial Parks | nama | f | :heavy_check_mark: |
| Natchez Trace Parkway | natr | f | :heavy_check_mark: |
| Navajo National Monument | nava | t | #681 |
| New Bedford Whaling National Historical Park | nebe | f | :heavy_check_mark: |
| New River Gorge National River | neri | f | :heavy_check_mark: |
| Nicodemus National Historic Site | nico | t | #680 |
| Niobrara National Scenic River | niob | f | :heavy_check_mark: |
| Ninety Six National Historic Site | nisi | f | :heavy_check_mark: |
| Noatak National Preserve | noat | f | :heavy_check_mark: |
| North Cascades National Park | noca | f | :heavy_check_mark: |
| National Park of American Samoa | npsa | f | :heavy_check_mark: |
| Obed Wild & Scenic River | obri | f | :heavy_check_mark: |
| Ocmulgee National Monument | ocmu | f | :heavy_check_mark: |
| Oklahoma City National Memorial | okci | f | #664 |
| Olympic National Park | olym | t | #663 |
| Oregon Caves National Monument | orca | f | :heavy_check_mark: |
| Oxon Cove Park & Oxon Hill Farm | oxhi | f | :heavy_check_mark: |
| Ozark National Scenic Riverways | ozar | f | :heavy_check_mark: |
| Palo Alto Battlefield National Historical Park | paal | f | :heavy_check_mark: |
| Pennsylvania Avenue National Historic Site | paav | f | :heavy_check_mark: |
| Grand Canyon-Parashant National Monument | para | f | :heavy_check_mark: |
| Pecos National Historical Park | peco | f | :heavy_check_mark: |
| Petrified Forest National Park | pefo | f | :heavy_check_mark: |
| Pea Ridge National Military Park | peri | f | :heavy_check_mark: |
| Petroglyph National Monument | petr | f | :heavy_check_mark: |
| Perry's Victory & International Peace Memorial | pevi | f | :heavy_check_mark: |
| New Jersey Pinelands National Reserve | pine | f | :heavy_check_mark: |
| Pinnacles National Park | pinn | f | :heavy_check_mark: |
| Pictured Rocks National Lakeshore | piro | f | :heavy_check_mark: |
| Pipe Spring National Monument | pisp | f | :heavy_check_mark: |
| Port Chicago Naval Magazine National Memorial | poch | f | :heavy_check_mark: |
| Presidio of San Francisco | prsf | f | :heavy_check_mark: |
| Prince William Forest Park | prwi | f | :heavy_check_mark: |
| Pullman National Monument | pull | f | :heavy_check_mark: |
| Rainbow Bridge National Monument | rabr | f | :heavy_check_mark: |
| Richmond National Battlefield Park | rich | f | :heavy_check_mark: |
| Rio Grande Wild & Scenic River | rigr | f | :heavy_check_mark: |
| River Raisin National Battlefield | rira | f | :heavy_check_mark: |
| Roosevelt Campobello International Park | roca | f | :heavy_check_mark: |
| Ross Lake National Recreation Area | rola | f | :heavy_check_mark: |
| Rocky Mountain National Park | romo | f | :heavy_check_mark: |
| Rosie the Riveter WWII Home Front National Historical Park | rori | f | :heavy_check_mark: |
| Roger Williams National Memorial | rowi | t | #653 |
| Russell Cave National Monument | ruca | f | :heavy_check_mark: |
| San Antonio Missions National Historical Park | saan | f | :heavy_check_mark: |
| Saint Croix National Scenic River | sacn | t | #648 |
| San Francisco Maritime National Historical Park | safr | f | :heavy_check_mark: |
| Saint-Gaudens National Historic Site | saga | f | :heavy_check_mark: |
| Saguaro National Park | sagu | f | :heavy_check_mark: |
| Sagamore Hill National Historic Site | sahi | f | :heavy_check_mark: |
| Saugus Iron Works National Historic Site | sair | f | :heavy_check_mark: |
| San Juan Island National Historical Park | sajh | t | #644 |
| San Juan National Historic Site | saju | f | :heavy_check_mark: |
| Salem Maritime National Historic Site | sama | f | :heavy_check_mark: |
| Santa Monica Mountains National Recreation Area | samo | f | :heavy_check_mark: |
| Sand Creek Massacre National Historic Site | sand | f | :heavy_check_mark: |
| Salinas Pueblo Missions National Monument | sapu | f | :heavy_check_mark: |
| Saratoga National Historical Park | sara | f | :heavy_check_mark: |
| Salt River Bay National Historic Park and Ecological Preserve | sari | f | :heavy_check_mark: |
| Scotts Bluff National Monument | scbl | t | #641 |
| Sewall-Belmont House National Historic Site | sebe | f | :heavy_check_mark: |
| Sequoia National Park | seki | f | :heavy_check_mark: |
| Kings Canyon National Park | seki | f | :heavy_check_mark: |
| Sequoia & Kings Canyon National Parks | seki | f | :heavy_check_mark: |
| Selma to Montgomery National Historic Trail | semo | f | :heavy_check_mark: |
| Shenandoah National Park | shen | f | :heavy_check_mark: |
| Shiloh National Military Park | shil | f | :heavy_check_mark: |
| Sitka National Historical Park | sitk | f | :heavy_check_mark: |
| Sleeping Bear Dunes National Lakeshore | slbe | f | :heavy_check_mark: |
| Springfield Armory National Historic Site | spar | f | :heavy_check_mark: |
| Steamtown National Historic Site | stea | f | :heavy_check_mark: |
| Statue Of Liberty National Monument | stli | f | :heavy_check_mark: |
| Stones River National Battlefield | stri | f | :heavy_check_mark: |
| Sunset Crater Volcano National Monument | sucr | f | :heavy_check_mark: |
| Suitland Parkway | suit | f | :heavy_check_mark: |
| Tallgrass Prairie National Preserve | tapr | f | :heavy_check_mark: |
| Theodore Roosevelt Island | this | f | :heavy_check_mark: |
| Theodore Roosevelt Birthplace National Historic Site | thrb | f | :heavy_check_mark: |
| Theodore Roosevelt Inaugural National Historic Site | thri | f | :heavy_check_mark: |
| Theodore Roosevelt National Park | thro | f | :heavy_check_mark: |
| Thomas Stone National Historic Site | thst | f | :heavy_check_mark: |
| Timpanogos Cave National Monument | tica | t | #637 |
| Timucuan Ecological & Historic Preserve | timu | f | :heavy_check_mark: |
| Tonto National Monument | tont | f | :heavy_check_mark: |
| Touro Synagogue National Historic Site | tosy | f | :heavy_check_mark: |
| Tuskegee Airmen National Historic Site | tuai | f | :heavy_check_mark: |
| Tuskegee Institute National Historic Site | tuin | f | :heavy_check_mark: |
| Tumacácori National Historical Park | tuma | f | :heavy_check_mark: |
| Tupelo National Battlefield | tupe | f | :heavy_check_mark: |
| Tule Springs Fossil Beds National Monument | tusk | f | :heavy_check_mark: |
| Tuzigoot National Monument | tuzi | f | :heavy_check_mark: |
| Upper Delaware Scenic & Recreational River | upde | f | :heavy_check_mark: |
| Valley Forge National Historical Park | vafo | f | :heavy_check_mark: |
| World War II Valor in the Pacific National Monument | valr | f | :heavy_check_mark: |
| Vanderbilt Mansion National Historic Site | vama | f | :heavy_check_mark: |
| Vicksburg National Military Park | vick | f | :heavy_check_mark: |
| Virgin Islands Coral Reef National Monument | vicr | f | :heavy_check_mark: |
| Virgin Islands National Park | viis | f | :heavy_check_mark: |
| Vietnam Veterans Memorial | vive | f | :heavy_check_mark: |
| Washita Battlefield National Historic Site | waba | f | :heavy_check_mark: |
| Walnut Canyon National Monument | waca | f | :heavy_check_mark: |
| Waco Mammoth National Monument | waco | f | :heavy_check_mark: |
| Washington Monument | wamo | f | :heavy_check_mark: |
| War In The Pacific National Historical Park | wapa | f | :heavy_check_mark: |
| Weir Farm National Historic Site | wefa | f | :heavy_check_mark: |
| President's Park (White House) | whho | f | :heavy_check_mark: |
| Whiskeytown National Recreation Area | whis | f | :heavy_check_mark: |
| Whitman Mission National Historic Site | whmi | f | :heavy_check_mark: |
| White Sands National Monument | whsa | f | :heavy_check_mark: |
| Wind Cave National Park | wica | f | :heavy_check_mark: |
| President William Jefferson Clinton Birthplace Home | wicl | f | :heavy_check_mark: |
| Wilson's Creek National Battlefield | wicr | f | :heavy_check_mark: |
| William Howard Taft National Historic Site | wiho | f | :heavy_check_mark: |
| Women's Rights National Historical Park | wori | f | :heavy_check_mark: |
| Wolf Trap National Park for the Performing Arts | wotr | f | :heavy_check_mark: |
| Wright Brothers National Memorial | wrbr | f | :heavy_check_mark: |
| Wrangell - St Elias National Park & Preserve | wrst | f | :heavy_check_mark: |
| Wupatki National Monument | wupa | f | :heavy_check_mark: |
| World War II Memorial | wwii | f | :heavy_check_mark: |
| Yellowstone National Park | yell | f | :heavy_check_mark: |
| Yosemite National Park | yose | f | :heavy_check_mark: |
| Yukon - Charley Rivers National Preserve | yuch | f | :heavy_check_mark: |
| Zion National Park | zion | f | :heavy_check_mark: |

**Comment by chadlawlis** [comment]
Query used:

``` sql
SELECT
    parks.unit_id,
    unit_name_long || ' ' || coalesce(unit_desig_full,'') as "name",
    parks.unit_code,
    ldir_enforce
FROM
    parks,
    parks_poly
WHERE
    parks.unit_id = parks_poly.unit_id
    AND
    ldir_enforce = 'f'
    AND
    (geom_poly is not null
    or
    geom_point is not null)
ORDER BY
    parks.unit_code;
```

**Comment by nateirwin** [comment]
Alright, I just checked Washita Battlefield National National Historic Site -> Zion (at the bottom of the table). No duplicate labels so far.

**Comment by chadlawlis** [comment]
We didn't quite finish working through this list, but I think we can close this out. We'll consider it a solid effort to kickstart the PT3 label cleanup.

We're constantly adding and updating unit labels, so this is probably best to handle on a park by park basis as we're browsing around, completing data seeds, developing mobile basemaps, etc.
