### ISSUE TITLE
Update Places Editor Viewer tiles to use new boundaries

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#634]
Now that Park Tiles 2.1 is using our new boundaries data, the last thing to make sure we update are the tiles being used in Places Editor. 

At lower zoom levels, it looks like we're using PT 2.1 Imagery because those tiles seem to have already switched over. Once we get into edit mode, the tiles used there seem to be pulling from the old boundaries still – those are the ones that need updating.

@jimmyrocks: I believe you're using new boundaries to determine unit codes for editing, but feel free to chime in if updating these tiles in Editor will impact your unit code assignments in any way.

cc: @jakecoolidge, @cwlawlis802, @nateirwin.

**Comment by mtaylorlong** [comment]
All these sources are stored in this directory:
https://github.com/nationalparkservice/mapbox-studio-projects/tree/master/places_editor_viewer

I'm not 100% sure what's actually being used here. I think @jakecoolidge understands it better than I do.

**Comment by jakecoolidge** [comment]
I have the view-only map pulling from nps.nps-places-reference, but I may need to update the labeling rules based on recent changes. The imagery visible in edit mode has traditionally been managed by @jimmyrocks --he may need to take a look at where he's pulling that from.
