### ISSUE TITLE
Align THRB building and boundary

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#638]
The boundary and building should align: http://insidemaps.nps.gov/park-tiles-3/#19/40.73859/-73.98901

<img width="485" alt="thrb_boundary_alignment" src="https://cloud.githubusercontent.com/assets/1238636/13887647/8afea16c-ed02-11e5-89e0-f3a9dfef89f3.png">

**Comment by jakecoolidge** [comment]
I encountered this preparing the NPNH basemap. The building is in the right spot, while the boundary is shifted to the southeast. Here's how it appears after I corrected it. @cwlawlis802, the data can be found [here,](https://github.com/nationalparkservice/mapbox-studio-projects/tree/master/places_mobile/NPNH/data/masi_parks) in a shapefile called masi_parks_2, if you'd like to make use of it.

<img width="261" alt="screen shot 2016-03-18 at 12 44 35 pm" src="https://cloud.githubusercontent.com/assets/11392872/13888466/38ca56ac-ed07-11e5-9588-573f0da74226.png">

**Comment by chadlawlis** [comment]
Awesome, thanks @jakecoolidge. I'll update it accordingly.

**Comment by chadlawlis** [comment]
Done via:

``` sql
BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM thrb),
    data_source = 'npnh'
WHERE
    unit_id = 378;
UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 378)
WHERE
    unit_id = 378;
UPDATE 
    parks_point
SET
    geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_id = 378)
WHERE
    unit_id = 378;
UPDATE
    parks_label
SET
    geom_label = (SELECT geom_point FROM parks_point WHERE unit_id = 378)
WHERE
    label_id = 102;
COMMIT;
```

Both the area boundary and label point were updated. Will confirm once boundaries are regenerated.

**Comment by chadlawlis** [comment]
This is now live.
