### ISSUE TITLE
AGFO labeling twice

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#639]
Note: this is a weird one. The extra label appears to be coming in from OSM, and is visible at z17 only. It doesn't appear to be an `ldir_enforce` issue.

**Comment by chadlawlis** [comment]
This is actually a Places issue - there is a Locale POI there, creating that additional label http://insidemaps.nps.gov/places/editor/#background=mapbox-satellite&id=n4767716&map=17.00/-103.75372/42.42235.

I am removing the Locale, which will resolve this.
