### ISSUE TITLE
VIIS label being knocked out by OSM

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#643]
VIIS is set to label at Z7, but is being knocked out by these rather large OSM place labels: http://insidemaps.nps.gov/park-tiles-3/#7/18.480/-65.978

![viis_z7](https://cloud.githubusercontent.com/assets/1238636/13889029/0ae6279a-ed0a-11e5-9480-38ffdba1752d.png)

There are other units on these islands as well, set to appear later, which should probably take priority over these OSM labels.

**Comment by mtaylorlong** [comment]
Took care of this. Park labels now take priority over country labels.
