### ISSUE TITLE
Add POI type: Food Box

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#65]
Parks like SEKI have first-come, first-serve boxes that can be shared by multiple camping groups to keep food away from bears:
http://www.nps.gov/seki/planyourvisit/bear_bc.htm
http://www.nps.gov/seki/planyourvisit/upload/FoodStorageBoxes_PageSize_v2.pdf

**Comment by chadlawlis** [comment]
Land Recreation > Food > "Food Box / Food Cache"
