### ISSUE TITLE
BICY and EVER should have same min_zoom_tint_band

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#655]
Mismatch occurs at zoom <=10

<img width="409" alt="screen shot 2016-03-18 at 2 58 17 pm" src="https://cloud.githubusercontent.com/assets/11392872/13891946/e0f04898-ed19-11e5-994f-9e8b9ca7bf11.png">

**Comment by chadlawlis** [comment]
Set min_zoom_tint_band = 10 and min_zoom_border = 9 for BICY to match up with EVER.

This will update once the tiles are regenerated.

**Comment by chadlawlis** [comment]
This is now live.

Related: https://github.com/nationalparkservice/places-data/issues/671
