### ISSUE TITLE
Assign route tags to bus stops / shuttle stops

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#66]
Information on the OSM wiki is a bit vague. In SEKI we have multiple shuttle routes, and some bus stops are served by multiple routes. Supporting this information in Places will help with routing applications.

**Comment by jimmyrocks** [comment]
Bus Route information in OSM is stored in a relation, this is complex and I don't expect Places users to understand it or keep it updated. We are instead planning on using bus route data from the parks in the GTFS format.  So I don't think we should keep track of this in places.

**Comment by jakecoolidge** [comment]
Sounds good.
