### ISSUE TITLE
BOAF could label one zoom sooner

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#660]
Currently displays at z13; looks like it could fit at z12.

<img width="600" alt="screen shot 2016-03-18 at 3 24 09 pm" src="https://cloud.githubusercontent.com/assets/11392872/13892566/c84b38e4-ed1d-11e5-965f-c3de3d0737bf.png">

**Comment by chadlawlis** [comment]
min_zoom_label has been set to 12. This will update once the tiles are regenerated.

**Comment by chadlawlis** [comment]
Label renders at Z12 now, but it is labeling twice at Z12.

Set `ldir_enforce = 't'`. Should fix once boundaries are regenerated.

**Comment by chadlawlis** [comment]
Fixed.
