### ISSUE TITLE
OBRI labeled only as "Obed WSR" in PT3 at all scales

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#68]
Obed is labeled: "Obed Wild and Scenic River Wild & Scenic River".

http://www.nps.gov/npmap/tools/park-tiles/#13/36.1116/-84.7651

**Comment by jimmyrocks** [comment]
Looks like a concatenation issue. You can make this change in CartoDB,
although we still don't have a standard workflow for getting this back into
Park Tiles.

**Comment by nateirwin** [comment]
Well, there are two records in CartoDB for `obed`. One with a `poly_source=Land Resources Division` and the other with a `poly_source=WSD_Parks`. It looks like the one from WSD_Parks has the issue with the name. I went ahead and fixed it, but I can't explain why there would be two records for a park.

**Comment by jimmyrocks** [comment]
That is strange, and is a different issue. Can we repurpose this issue to
address both issues?

**Comment by nateirwin** [comment]
Sure. I'll update the title.

**Comment by jimmyrocks** [comment]
great!

**Comment by makella** [comment]
This is fixed in CartoDB, we will make sure the label is correct after the tiles are re-run.

**Comment by chadlawlis** [comment]
Well, this is "fixed" in CartoDB - there is only one record "Obed Wild & Scenic River" - and it is maintained correctly in the new PostGIS parks table with `unit_name_long = Obed` and `unit_desig_full = Wild & Scenic River`. However, the label in PT3 is only showing up as `Obed WSR`.

Re-purposing this issue, and copying @mtaylorlong.

**Comment by mtaylorlong** [comment]
@cwlawlis802: All this sounds good to me. Isn't `Obed WSR` exactly how we want it to label in PT3?

**Comment by chadlawlis** [comment]
Ah, if that's the case then we're all set here. I imagined we might want the full designation spelled out at higher zoom levels, given the availability of space for the label. If not that's good to know - I've noticed this for other units, so being an intentional design decision would explain it.

**Comment by mtaylorlong** [comment]
Well, it should got to the full label eventually. If it never does, then I should look at the min_zoom settings in Parks postgis. I need to look anyway to see why the polygon isn't rendering.

**Comment by chadlawlis** [comment]
Ya, it never does.

**Comment by chadlawlis** [comment]
Well, this could be why...

![query - places_boundaries on postgres localhost 15432 2015-12-10 10-10-28](https://cloud.githubusercontent.com/assets/1238636/11722512/4af7eada-9f26-11e5-909d-c306881ebf6f.jpg)

**Comment by mtaylorlong** [comment]
This OBED issue is still there. I just need to go into the parks table and fix its min_zoom settings. I'll try to take care of this soon.

**Comment by chadlawlis** [comment]
:+1: 

Thanks, @mtaylorlong.

**Comment by mtaylorlong** [comment]
I'm closing this issue since it's also handled in #321.
