### ISSUE TITLE
Campground roads missing in Mather Campground at GRCA

### ISSUE THREAD

**Issue by ryanjhodge** [nationalparkservice/places-data#69]
The loop roads where the actual campsites are located are not showing up on Park Tiles.  They do show up on on OSM.

![parktiles](https://cloud.githubusercontent.com/assets/4172213/8394651/1320a0f8-1cf8-11e5-9c04-8654fb4983b7.PNG)

![osm3](https://cloud.githubusercontent.com/assets/4172213/8394652/177c9c9c-1cf8-11e5-9503-a3da1986f657.PNG)

**Comment by ryanjhodge** [comment]
I'm thinking this is happening because these roads are tagged with `service=driveway` which does not seem appropriate for this situation according to [driveway OSM wiki](http://wiki.openstreetmap.org/wiki/Tag:service%3Ddriveway)

I'll edit them on OSM and see if it takes care of it.

**Comment by ryanjhodge** [comment]
Looks like that did it.  This brings to light an overlying issue, that roads with `service=driveway` tag are not getting rendered.  That might warrant it's own issue, but I'll leave that up to you guys.

![capture](https://cloud.githubusercontent.com/assets/4172213/8398405/eac8fbbe-1da1-11e5-8a7c-26e16b2f7438.PNG)

**Comment by jimmyrocks** [comment]
We are hoping to use road data from Places in Park Tiles in the near future.
We are already using a version of it of it for the Places Editor
http://insidemaps.nps.gov/places/view/#16/36.050/-112.120

This version is designed to help the person editing identify feature to edit, so the cartography is designed to be more contrasting than Park Tiles.

**Comment by nateirwin** [comment]
Closing for now, as given the current paradigm, we don't have granular control over which data is brought in and available for Park Tiles. As @jimmyrocks mentioned: This should resolve itself shortly when we switch over to NPS data.

**Comment by makella** [comment]
I've had this on my list of enhancements to Park Tiles: https://github.com/nationalparkservice/park-tiles/issues/134

If we'd like to add this class, we can do it until we fully switch over.  I also agree that roads like these are not necessarily driveways.

**Comment by ryanjhodge** [comment]
Thanks for the responses, I forgot to mention that campsites are explicitly stated in the `highway=service road` [tag definition](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice), which is why I felt confident about updating these features on OSM.

> Generally for access to a building, motorway service station, beach, campsite, industrial estate, business park, etc. This is also commonly used for access to parking, driveways, and alleys.

**Comment by jimmyrocks** [comment]
Ryan,

This was definitely an error in OpenStreetMap, thanks for fixing it!

This is one reason why we would like to use our own data within the parks,
so we can control how it displays on our maps and only people validated by
the NPS can make changes.

## 

Jim
