### ISSUE TITLE
Move CAHA label point

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#690]
Cape Hatteras NS is a very odd-shaped polygon, so its centroid falls in Pamlico Sound. The label point could be moved to the park's "heart", near Hatteras Light.

<img width="152" alt="screen shot 2016-03-25 at 3 56 48 pm" src="https://cloud.githubusercontent.com/assets/11392872/14054902/bee91cd2-f2a2-11e5-9ff7-a8ded847bcaa.png">

<img width="426" alt="screen shot 2016-03-25 at 4 01 25 pm" src="https://cloud.githubusercontent.com/assets/11392872/14054931/0f8890b4-f2a3-11e5-9ee7-275ef2c96168.png">

Of course, ideally it might follow the arc of the Outer Banks...

<img width="435" alt="screen shot 2016-03-25 at 4 06 59 pm" src="https://cloud.githubusercontent.com/assets/11392872/14055001/b28879c8-f2a3-11e5-8ea5-bae2a5a52421.png">

**Comment by chadlawlis** [comment]
Done via:

``` sql
BEGIN;
UPDATE parks_label
SET geom_label = (SELECT ST_GeomFromText('POINT(-75.52963256835938 35.21855725628777)', 4326))
WHERE label_id = 346;

UPDATE parks_label
SET geom_label = ST_Transform(ST_SetSRID(geom_label, 4326), 3857)
WHERE label_id = 346;
COMMIT;
```

Will confirm once tiles have been regenerated.

**Comment by chadlawlis** [comment]
This is now live.
