### ISSUE TITLE
Fix GRSA boundary

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#693]
In transitioning IMR from WSD_Parks to Lands via #692, GRSA was generated using a ST_Union() of the two areas Lands has on file - for the Preserve and the Park. These two areas do not align seamlessly, outputting a boundary that needs fixing:

![grsa](https://cloud.githubusercontent.com/assets/1238636/14092704/13b5a2b6-f506-11e5-9f24-8c250f3bbc98.png)

This will have to be resolved manually in QGIS and reloaded.

**Comment by mtaylorlong** [comment]
Here's a cleaned up boundary shapefile. Note, I did not delete any outer vertices, just the inner ones causing these sliver gaps:

[grsa_merged.zip](https://github.com/nationalparkservice/places-data/files/221398/grsa_merged.zip)

**Comment by chadlawlis** [comment]
Done via:

``` sql
BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM grsa_merged)
WHERE
    unit_id = 177;
UPDATE
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 177)
WHERE
    unit_id = 177;
COMMIT;
```

This will go live once tiles are regenerated.

**Comment by chadlawlis** [comment]
This is now live.
