### ISSUE TITLE
FORA Boundary

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#699]
This is the current boundary:

![screen shot 2016-04-06 at 10 44 58 am](https://cloud.githubusercontent.com/assets/11392872/14325044/aea3359c-fbe4-11e5-9aaa-45ec786256bd.png)

Several parcels appear to be missing. Here's the official depictions of the boundary hosted by Lands:

This is an older, perhaps more solidified interpretation:
http://landsnet.nps.gov/tractsnet/documents/FORA/Segment_Maps/forasm01.pdf
![screen shot 2016-04-06 at 10 48 11 am](https://cloud.githubusercontent.com/assets/11392872/14325149/2fbd35f6-fbe5-11e5-9246-b2f5cd81fe81.png)

And this is a younger "draft" version:
http://landsnet.nps.gov/tractsnet/documents/FORA/Segment_Maps/forasm01_draft.pdf
![screen shot 2016-04-06 at 10 49 55 am](https://cloud.githubusercontent.com/assets/11392872/14325185/5eababf4-fbe5-11e5-81db-e5ef092efad7.png)

The younger draft version doesn't contradict the older version--both assign several properties to the park that are not included in the current boundary we're accessing. Seems like Lands would want to correct this if notified.

**Comment by chadlawlis** [comment]
@jakecoolidge is this "younger draft version" available to us? Or are we looking to stick with Lands here and nudge them to make the fix?

**Comment by jakecoolidge** [comment]
All I have are these images--I don't have geospatial data. Dave K. is checking with his management analyst to get the Outer Banks group's take on the proper depiction. Based on the above, I would think Lands has the correct boundary already, though I don't know what their process would be for correcting it. Mark suggested I contact the chief cartographer for SER, but I don't want to take that step unless it's necessary.

**Comment by nateirwin** [comment]
If we do need to take this to the SER cartographer, that request should come from the park.

**Comment by chadlawlis** [comment]
Sounds good. Holler at me if/when we have a boundary update in the queue here.

**Comment by jakecoolidge** [comment]
SER GIS coordinator Chris Barrow confirmed that LRD's segment maps are more accurate than the geometry in the latest release. I also digitized the boundary shown in the segment map and shared this data with Chris. The image below compares the geometry in LRD's dataset (in red) with data digitized based on LRD's segment maps (in purple):

![fora_boundary_comparison](https://cloud.githubusercontent.com/assets/11392872/16622042/dafd8bb6-4355-11e6-91c1-4c413c395880.png)

Chris will notify LRD to revise FORA's boundary on behalf of the Outer Banks group. In the meantime, I've placed my data [here](https://drive.google.com/open?id=0B8kRL6psDWmZTFZ4azZUdDdnaHM) should we decide to update our boundaries data with the revised geometry.

@cwlawlis802 I'll let you make the call for closing this issue.

**Comment by chadlawlis** [comment]
Sounds like approval to me. I'll get this updated here soon. Thanks @jakecoolidge!

**Comment by chadlawlis** [comment]
Done via:

``` sql
BEGIN;
UPDATE
    parks_poly
SET
    geom_poly = (SELECT wkb_geometry FROM fora),
    data_source = 'fora'
WHERE
    unit_id = 139;
UPDATE 
    parks
SET
    unit_area = (SELECT ST_Area(geom_poly) FROM parks_poly WHERE unit_id = 139)
WHERE
    unit_id = 139;
UPDATE 
    parks_point
SET
    geom_point = (SELECT ST_Centroid(geom_poly) FROM parks_poly WHERE unit_id = 139)
WHERE
    unit_id = 139;
COMMIT;
```

Will go live once boundaries are regenerated.

**Comment by jakecoolidge** [comment]
👍 thanks @cwlawlis802!

**Comment by chadlawlis** [comment]
This is now live.
