### ISSUE TITLE
Add record for MASI

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#701]
Somehow I got MASI - Manhattan Sites - confused with MAPR - Manhattan Project National Historical Park. I am moving comments originally listed in #179 over here, to address appropriately as MASI.

We need to add a record for MASI, set all appropriate subunits to `subunit_of = 'masi'`, and move the custom aggregate boundary over from MAPR to MASI before updating MAPR from the Lands release.

**Comment by chadlawlis** [comment]
Moving over from #179:

From Daniel, webmaster @ MASI, 2/11/16:

> I am the webmaster for all seven websites for the Manhattan Sites Unit.
> You have consent to use the Park Tile 3 map for the following sites:
> CACL
> FEHA
> AFBG
> THRB
> GEGR
> HAGR
> SAPA

So, I will combine these units to create a master boundary for MASI.

**Comment by chadlawlis** [comment]
Moving over from #179:

_Note_: 5 of the 7 units that were merged to create this boundary pull from Lands (CACL, FEHA, THRB, HAGR, SAPA) while AFBG and GEGR  pull from a custom `npnh` source. I am setting the source for the standalone MASI unit to `npmap` in `parks`.

@jakecoolidge the source for AFBG appears to align better with imagery:
![afbg](https://cloud.githubusercontent.com/assets/1238636/12990534/20c72eaa-d0c8-11e5-849f-ead1fe924c4c.jpg)
while the GEGR source appears to be expanded a little bit beyond what Lands provides:
![gegr](https://cloud.githubusercontent.com/assets/1238636/12990570/50e229d2-d0c8-11e5-884b-8b8b221cba4e.jpg)

Do these look right for these units? Closing, but chime in if you can confirm that these are good or require a transition to Lands.

**Comment by chadlawlis** [comment]
Okay, MASI has been added using the mistaken MAPR aggregate boundary from before. Done via:

``` sql
BEGIN;
-- add to parks table
INSERT INTO parks (
    unit_id,
    unit_name_short,
    unit_name_long,
    unit_code,
    simp_type,
    data_source,
    unit_region,
    unit_state,
    unit_url)
values (
    (select max(unit_id) + 1 from parks),
    'Manhattan Sites',
    'Manhattan Sites',
    'masi',
    'point',
    'masi',
    'ner',
    'ny',
    'https://www.nps.gov/npnh/index.htm');

-- add to parks_poly table
INSERT INTO parks_poly (
    unit_id,
    unit_code,
    geom_poly
    )
VALUES (
    (SELECT unit_id FROM parks WHERE unit_code = 'masi'),
    'masi',
    (SELECT geom_poly FROM parks_poly WHERE unit_code = 'mapr')
    );

-- add to parks_line table
INSERT INTO parks_line (
    unit_id,
    unit_code
    )
VALUES (
    (SELECT unit_id FROM parks WHERE unit_code = 'masi'),
    'masi'
    );

-- update parks with geometry calculations from parks_poly
UPDATE
    parks
SET
    unit_area = (select ST_Area(geom_poly) from parks_poly where unit_code = 'masi'),
    geom_point = (select ST_Centroid(geom_poly) from parks_poly where unit_code = 'masi')
WHERE
    unit_code = 'masi';
COMMIT;
```

We'll still want to double check the boundaries for AFBG #704 and GEGR #703 against Lands.

**Comment by cwlawlis802** [comment]
See #702 for `subunit_of`.
