### ISSUE TITLE
Compare GEGR boundary to Lands

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#703]
GEGR was updated in Lands in the 20150422 release (see #538), though it is currently pulling from a custom `npnh` source. The GEGR source appears to be expanded a little bit beyond what Lands provides:

![gegr](https://cloud.githubusercontent.com/assets/1238636/12990570/50e229d2-d0c8-11e5-884b-8b8b221cba4e.jpg)

@jakecoolidge are you familiar with this unit? It is unclear from HFC's map https://www.nps.gov/hfc/carto/PDF/GEGRmap1.pdf which is more accurate. If we aren't sure either way we should probably ping Mark.

**Comment by chadlawlis** [comment]
If we update this boundary we'll need to update the aggregate MASI boundary as well (see #701).

**Comment by jakecoolidge** [comment]
Just pinged Mark; we'll see what he says. The extra blue parcels in your screenshot, @cwlawlis802, belong to the City of New York Parks Dept., according to Lands' official tract map. I was surprised by that finding.

**Comment by chadlawlis** [comment]
Lands tract map available here: http://landsnet.nps.gov/tractsnet/documents/GEGR/Segment_Maps/gegrsm01.pdf.

Thanks for looking into this and pinging Mark, @jakecoolidge :+1:

**Comment by chadlawlis** [comment]
From Mark, 4/11:

> Yea, this is where reality and the lands office split when you are doing urban mapping.
> 
> So in the case of Grants Tomb, the map is showing what we want the public to see.  While not legally correct, its the area we want them to go to and think of as Grant's Tomb.  This happens a lot on Harper's Ferry Maps.  And often is representative of deals made between different agencies.   The Visitor center is sitting inside City land, but the visitor does not care or does not need to know that.  So the map just show it as part of the park.

So, we will stick with the current boundary from `npnh`.
