### ISSUE TITLE
Compare AFBG boundary to Lands

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#704]
AFBG is currently pulling from a custom `npnh` source. This appears to align better with imagery than the Lands boundary:

![afbg](https://cloud.githubusercontent.com/assets/1238636/12990534/20c72eaa-d0c8-11e5-849f-ead1fe924c4c.jpg)

I'm assuming we should stick with the NPNH source here, but might be worth pinging Mark about. cc @jakecoolidge

**Comment by chadlawlis** [comment]
If we update this boundary we'll need to update the aggregate MASI boundary as well (see #701).

**Comment by jakecoolidge** [comment]
I think he'll want to go with the custom boundary, but I pinged Mark for confirmation.

**Comment by chadlawlis** [comment]
Agreed, thanks for pinging him for confirmation though :+1:

**Comment by chadlawlis** [comment]
From Mark @ NPNH, 4/11:

> Yea, this is where reality and the lands office split when you are doing urban mapping.
> 
> As for African Burial Ground, this is more an issue of imagery.  Imagery can be distorted based on a number of factors, and this issues are more apparent as the imagery improves.  Once you get to 6" pixel resolution imagery, the lining up of imagery becomes very hard.  A good example of this is that I mapped the buildings of Gateway in 2010 using 2010 imagery, each year when imagery comes out the building move a few feet.  I long ago stopped trying to move the building to match the imagery.  That's what's happening here.  The basemap displays what we want to show.

Jake sent Mark a screenshot of Park Tiles 3, which is what Mark is referring to by "basemap" here. So, we will stick with the current boundary from `npnh`.
