### ISSUE TITLE
Hello, highway labels!

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#709]
I was just looking at Park Tiles 3 and noticed that a bunch of highway labels are showing up at fairly small zoom levels. Did something change recently with this?

<img width="1440" alt="fullscreen_4_12_16__7_37_pm" src="https://cloud.githubusercontent.com/assets/10443/14480438/47d0dd2c-00e6-11e6-8ec2-f07bbf79a318.png">

Cc/ @mtaylorlong

**Comment by mtaylorlong** [comment]
@nateirwin: I think you're right that it's a little much. I did simplify the highway labeling rules, and I probably need a bit more control over phasing in major highways before county road numbers. I'll take a look today and fold this update into the others for our new data source.

**Comment by mtaylorlong** [comment]
I looked into this. The difference between PT2.1 and PT3 highway shields was that in PT3, I included shields for secondary and tertiary roads. I agree that the shields are overwhelming, so I'm going to remove secondary and tertiary shields to return to the PT2.1 ways. I just uploaded the change to mapbox.
