### ISSUE TITLE
Revisit Class and Superclass designations for various structures

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#717]
While adding support to PT3 for fortifications and boat docks, I identified an opportunity to streamline my cartocss with some adjustments to the class and superclass for these features.

This is the current setup:  

| superclass | class | type |
| --- | --- | --- |
| miscellaneous | structure | fortification |
| structure | recreation | boat dock |

I'd love to get these two features with one selection by aligning their `superclass` or `class`. Boat dock seems to be the only area with a `superclass` of `structure`. Fortification is in good company, with a handfull of other features with a `class` of `structure`. So, the easiest thing, would be to change Boat Dock, but I actually think it makes more sense to revisit how were categorizing fortification as it's other similar features.

What if we made fortification a `superclass` of `structure` and a new class of, say, `military` or something like that? This, of course, would lead to looking at other features with a `superclass` of `miscellaneous` and potentially updating them as well.

@cwlawlis802: How could we go about approving these changes and implementing them?

**Comment by chadlawlis** [comment]
Type "Fortification" (point and area) now under Superclass "Structure", Class "Fortification".
