### ISSUE TITLE
Boat docks rendering on top of trails / pedestrian paths

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#719]
Example here: http://insidemaps.nps.gov/park-tiles-3/#19/37.80892/-122.46995.

The structure rendered here is a Boat Dock, under which is a Pedestrian Path (superclass Trail, class Non-Motorized). This path should render on top of the dock, though rendering building footprints and fortifications on top of trails/roads still makes sense.

**Comment by mtaylorlong** [comment]
Good catch! I fixed this and updated PT3 standard. I've made another instance of the places polygon layer called `nps_places_polygons.surface` which is positioned under roads and trails in the .yml stack. `nps_places_polygons.building` is still positioned on top of roads and trails, and includes both buildings and fortifications.
