### ISSUE TITLE
AMME labeling twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#723]
Z11 only.

**Comment by chadlawlis** [comment]
Set `ldir_enforce = 't'`.

This should fix once boundaries are regenerated.

**Comment by chadlawlis** [comment]
The double label at z11 is fixed, but the label is now being cut off at z6 and z16.

Set `ldir = 'W'` (previously `'E'`), will confirm if fixed once live.

**Comment by chadlawlis** [comment]
And the label is now cutting off at z15 and slightly at z9.

@mtaylorlong do you have a way of testing the label directionality locally before we update this in the database?

**Comment by chadlawlis** [comment]
Trying `ldir = 'S'` ...

**Comment by chadlawlis** [comment]
This now cuts off at z5. Trying `ldir = 'N'` ...

**Comment by mtaylorlong** [comment]
@cwlawlis802: I do have a way of testing before we commit to a value in the db. (sorry for the delayed response). After testing, I think `ldir='NW'` is best. I've also updated `min_zoom_label_center` to 14. Should be all set after the next render of boundary tiles.

**Comment by chadlawlis** [comment]
Hm, label is now cutting off partially at z6 and doubling at z12.

`ldir_enforce` already set to `'t'` so we'll have to find another workaround here.

**Comment by chadlawlis** [comment]
The map on insidemaps has now updated and the label is not doubling, so that's all set.

It is still cutting off partially at z9.

**Comment by chadlawlis** [comment]
We've exhausted our options here, so a partial label cutoff at z9 is something we'll have to live with. Closing.
