### ISSUE TITLE
INUP labeling twice

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#727]
z13-18.

Setting `ldir_enforce = 't'`.

**Comment by chadlawlis** [comment]
This did not fix the double label given `ldir` was NULL. I've set `ldir = 'NE'` and will confirm once live.

**Comment by mtaylorlong** [comment]
I just tested `ldir='NE'` and it's not going to work – the label gets chopped off badly in a few intermediate zoom levels. The best option seems to be `ldir='SE'`. I've made the change in the db. Just waiting on the next run of boundary tiles now.

**Comment by chadlawlis** [comment]
Hm, label is still duplicating at z14-15 despite `ldir_enforce = 't'`.

What else can we do here to prevent this @mtaylorlong?

**Comment by mtaylorlong** [comment]
@cwlawlis802: I don't see this duplication. It looks correct to me in pt3: https://www.nps.gov/npmap/tools/park-tiles/#14/71.2971/-156.7503

**Comment by chadlawlis** [comment]
Weird, another case of the change showing up through the public link but initially not through insidemaps.  It's fixed on insidemaps now, so we're all set.
