### ISSUE TITLE
Support "Cliff" preset as as line

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#730]
After some discussion, we've decided it makes sense to support "Cliff" as a Places preset for a line. This way, we can show the rim of the Grand Canyon and any other deadly fall hazards very explicitly on the map. This helps work around the issue of hillshades becoming unusable around z18.

@cwlawlis802, @jimmyrocks: I'll let y'all figure out how the underlying tags should work.

Let us know when it's ready and we'll find some cliffs to add!

**Comment by chadlawlis** [comment]
👍 

`{"natural":"cliff"}`

**Comment by chadlawlis** [comment]
This has been added to the spreadsheet, will go live once presets are regenerated.

**Comment by chadlawlis** [comment]
This is now live.
