### ISSUE TITLE
Add `nps_official` field to `parks` table

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#731]
I'm proposing we add a new field to the `parks` table in the places boundaries database: `nps_official`

This would be a boolean field to indicate whether the record is one of the 411 official park units. This way, it would be easy to query for a list of the official units and also easy to show which "unofficial" units we support (and why it's super helpful).

@jimmyrocks says that if we add the field in the database, we'll need to also add a field in cartodb so they two can properly sync. 

I thought @cwlawlis802 could add the fields. I'd be happy to work through the list and populate the data.

**Comment by chadlawlis** [comment]
Adding @jimmyrocks as the assignee here.

This will need to be added to the `parks` table in the boundaries database and the `parks_v2` table out in CartoDB. Thanks @jimmyrocks!

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-data/commit/96d3348e994295d20bb90fc95e8899a427e2eb4e
