### ISSUE TITLE
Add "garden" area preset

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#737]
"leisure":"garden"; see https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgarden

Gateway NRA has several of these; might be worth capturing?

**Comment by chadlawlis** [comment]
I'm assuming we would want this as both a point and area, @jakecoolidge?

**Comment by jakecoolidge** [comment]
That's correct--that's how I envisioned it.

**Comment by chadlawlis** [comment]
Garden is already available as a point, added to spreadsheet as area. Will go live once presets are regenerated.

**Comment by chadlawlis** [comment]
This is now live.
