### ISSUE TITLE
SAAN trails and points of interest

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#74]

**Comment by jakecoolidge** [comment]
done.

**Comment by nateirwin** [comment]
Great, Jake! Did you by chance follow up with the park to let them know? Just wondering because I talked to them on the phone yesterday, and they were curious what the status was.

**Comment by jakecoolidge** [comment]
Hey @nateirwin: I have a draft ready to go, but I made a note to follow up with you. I wasn't sure if _____ can access Places--will he be able to go into Places and review the inputs?

**Comment by nateirwin** [comment]
He probably won't be able to, but the park contact will be able to. So that should suffice. I'd just include both of them in the email so they know that the data has been seeded.
