### ISSUE TITLE
Compare STLI with latest Lands release 20160630

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#748]
From https://github.com/nationalparkservice/places-data/issues/746.

![stli](https://cloud.githubusercontent.com/assets/1238636/16505743/adef821a-3edb-11e6-8f5c-f9364dec7127.png)

Any thoughts on this @jakecoolidge?

**Comment by jakecoolidge** [comment]
The new Lands release improves the geometry around the dock structures on Liberty Island, but the added territory in the adjacent water areas is disorienting at first glance. In our recent experience with the mobile app, NPNH staff focused on two geometries: a park unit border that coincides with the shoreline of each island, and a buffer area that excludes non-authorized watercraft for security purposes. I'll ask Gateway NRA cartographer Natalya A. if she has any insight on the matter.

**Comment by jakecoolidge** [comment]
Natalya and staff at STLI/ELIS are unfamiliar with this version of the boundary. Correspondence from 7/1/2016:

> The app users wouldn't care about this, so let's let it stand. But this is very different from our prior understanding of the park boundaries. All, FYI. US Park Police, does this have any implications for the security boundary?

&mdash;Deputy Superintendent John Hnedak (where "this" is the official boundary in question, and "it" is the current depiction in the mobile app)

Lt. Tony Lordo Jr., USPP at STLI replied: 

> As indicated, the Liberty Island docks are included within the park boundaries (Federal Land). I see no implications to our security boundary.  The maritime security zone is noted on the attachment for reference and should not be affected by the boundaries referred to by Natalya.

So, not a resounding consensus. The current boundary depiction, though not perfect, is consistent with how the islands have typically been mapped, particularly on maps made for the public. However the new boundary depiction won't raise issues for law enforcement, at least.

**Comment by chadlawlis** [comment]
Interesting, thanks for the follow up @jakecoolidge. Sounds like there is no real desire from the park to transition to the Lands boundary. I'm going to close this for now, to re-open if the park explicitly asks for an update.
