### ISSUE TITLE
Fort Raleigh labeled twice at large scales

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#757]

**Comment by chadlawlis** [comment]
Hm, I'm not seeing this @nateirwin - what zoom levels are you seeing this at?

**Comment by nateirwin** [comment]
Looks like zoom levels 18 and 19:

<img width="740" alt="park_tiles___npmap" src="https://cloud.githubusercontent.com/assets/10443/16598736/8a22ba48-42bc-11e6-819f-7b53d78bb960.png">

It's happening on both retina and non-retina.

**Comment by chadlawlis** [comment]
Ah, there it is - I misunderstood "large scales".

`ldir_enforce` set to `'true'`.

**Comment by chadlawlis** [comment]
This has been resolved.
