### ISSUE TITLE
New preset type: Crater Rim (line)

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#768]
I'm proposing a new preset – Crater Rim – as a line feature. Following the [OSM standard](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dvolcano#Crater_rim) we can tag this with a combination of `natural=cliff AND geological=volcanic_caldera_rim`. 

I'd suggest we categorize like this:  

| Superclass | Class | Type |
| --- | --- | --- |
| Natural Feature | Cliff | Crater Rim |

@jimmyrocks @cwlawlis802: Let me know if there are any other details to work out. I'd love to get this running soon so I can swap out the custom YELL caldera rim with real Places data.

**Comment by chadlawlis** [comment]
This has been added to the spreadsheet as a line only and will go live once presets are regenerated.

**Comment by chadlawlis** [comment]
This is now live.
