### ISSUE TITLE
"permission denied for relation parks"

### ISSUE THREAD

**Issue by kentr** [nationalparkservice/places-data#779]
Apologies if this is the wrong repo.  It was the best-looking place to file this issue...
### Problem

When accessing the [park tiles demo map](https://www.nps.gov/maps/tools/park-tiles/#9/37.8380/-119.5505), the points of interest don't load.

In the web inspector, I see a `"permission denied for relation parks"` result for the [`points_of_interest` cartodb URL](https://nps.cartodb.com/api/v2/sql?cb=1471998142725&q=SELECT+a.minzoompoly+AS+m%2Cb.name+AS+n%2Cb.type+AS+t%2Cb.unit_code+AS+u%2CST_X%28b.the_geom%29+AS+x%2CST_Y%28b.the_geom%29+AS+y+FROM+parks+AS+a%2Cpoints_of_interest+AS+b+WHERE+a.unit_code%3Db.unit_code).

Maybe the CartoDB tables aren't "public" anymore?

**Comment by chadlawlis** [comment]
Hi @kentr - sorry about that, the table permissions were changed temporarily which caused some downtime. This has been resolved, and the POIs appear to be back on the map. Thank you for flagging!
