### ISSUE TITLE
Filter `pt_render = false` label points out of vector tile source

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#782]
Layer: `nps_places_boundaries_point`.

SQL here: https://github.com/nationalparkservice/places-data/blob/gh-pages/boundaries/database/nps-places-boundaries-v2.tm2source/data.yml#L27-L54.

`pt_render` must be added into SELECT clause and `WHERE pt_render = false` into the WHERE clause. This must be done in Mapbox on the server and updated in the code on github, per above.

**Comment by chadlawlis** [comment]
All set - thanks @jimmyrocks!

https://github.com/nationalparkservice/places-data/commit/f9408907989ceef8e1c1021c72aaf650b19d6d1b

**Comment by jimmyrocks** [comment]
Lines fixed with commit: https://github.com/nationalparkservice/places-data/commit/8f26e7e289de367a96cfe2ec240e7bf2b771f472
Points fixed with commit: https://github.com/nationalparkservice/places-data/commit/f9408907989ceef8e1c1021c72aaf650b19d6d1b
