### ISSUE TITLE
Add name_abbr field to nps_park_labels_15

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#79]
When rendered at full name, Homestead should read Homestead National Monument not just Homestead.

http://www.nps.gov/maps/embed.html?mapId=5bb01010-51aa-4065-b877-0babdf7c91d4

**Comment by makella** [comment]
Fort Larned National Historic Site needs full designation in full name
http://www.nps.gov/maps/embed.html?mapId=5bb01010-51aa-4065-b877-0babdf7c91d4

**Comment by makella** [comment]
@makella needs to look into this on the cartography side.  CartoDB is good with the naming.

**Comment by makella** [comment]
We are adding the abbreviated name in nps_park_labels_15 which will keep the abbreviated name until the park is ready for full label.

Refer to: https://github.com/nationalparkservice/mapbox-studio-projects/commit/43256cae223aa285ec74446192aade33c26fbbc3

**Comment by jimmyrocks** [comment]
Field added
