### ISSUE TITLE
Some road labels are uppercase some are lower case, some are mixed case

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#80]
In our rendering data source, road labels are a mix between all upper, all lower, mixed, etc. There are a variety of variations in the `name` field

**Comment by jimmyrocks** [comment]
This is a problem with the data coming into places.
What is the best method to fix this problem for rendering?

Should we normalize text before importing?
Should we run a script on places to update all names to be normalized?

**Comment by nateirwin** [comment]
Automated cleanup of names is going to be really difficult. I think we may just have to deal with the bad labels for now and manually clean them up over time.

This could also be a microtask. We could develop a little tool that displays names that we think need to be cleaned up (all uppercase, all lowercase, etc.) and let a user mark the names as valid or submit a cleaned up name.

**Comment by makella** [comment]
I was thinking that a script could be run where everything was automatically changed to mixed case.  Like after a space the first letter would be capitalized and then lower case after that until the next space.

**Comment by nateirwin** [comment]
We could try something like that, but there are a bunch of edge cases that will be difficult to handle.

For example: `McCain Street` would turn into `Mccain Street`.

Maybe this is something we're ok with? There is certainly going to be less cleanup if we run the script and then go in and try to manually clean up edge cases like `McCain`.

**Comment by makella** [comment]
Always gonna be edge cases! There are a ton of random labels in here.  Anyway, I'm fine with whatever you guys think is best for now.

**Comment by makella** [comment]
I'm not sure if these will be helpful, but here are a set of scripts my old boss Charlie Frye from Esri wrote to handle common labeling challenges.  find and replace, transform to proper case, and extract hwy shield numbers.  They are all super useful and ones that I used a lot to clean up data back then.

**Comment by makella** [comment]
oops link:
http://arcscripts.esri.com/details.asp?dbid=15800

**Comment by jimmyrocks** [comment]
Thanks @makella, I was going to say that we're not the first group to have this problem, so I'm sure someone has already put the work in and open sourced the solution.

**Comment by makella** [comment]
definitely we are not! :)

**Comment by makella** [comment]
With Charlie's tool, a first step is to first make everything all upper or all lower and then run -- that's what it assumes.  And writing to a new labeling field (instead of changing original field) is probably a good idea.

**Comment by chadlawlis** [comment]
Is this something we're still interested in pursuing, @nateirwin and @jimmyrocks?

When seeding data or cleaning up Places data for a mobile app basemap I make a point to clean up the text casing for all features. This is relatively easy in Postgres and/or JOSM, though on a park by park basis. I'm assuming this may be our best (and most realistic) way forward?

**Comment by nateirwin** [comment]
Yeah, I don't think this needs to be automated at this point. A lot has changed since this ticket was first opened. I'm going to go ahead and close this.
