### ISSUE TITLE
Capturing BLRI road segment info

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#81]
BLRI breaks the Parkway into segments, which allows them to map seasonal openings/closures along the Parkway. Nate and I discussed segmenting the Parkway geometry in Places in accordance with BLRI's segmentation. BLRI has provided us with their Parkway geometries. The data also includes three attributes: 
- the segment's name/description ("423.2 to 443.7 Parkway")
- Control (two values, "Open or Closed" or "Ungated")
- and Table Order(1, 2, 3...). 

I'm thinking about how we capture some, if not all of this info in Places. 
- The name/description could be captured with `alt_name`. 
- **Control** seems approximate to `access`. "Open or Closed" could be mapped to an access tag with conditional restriction&mdash;but I'm interested in what you guys think of this.
- Table order probably should not be maintained in Places.

**Comment by nateirwin** [comment]
@jakecoolidge: I probably wasn't clear yesterday, but I actually think we should merge the geometries together for BLRI's roads. We can maintain the segments themselves in the Places system.

**Comment by chadlawlis** [comment]
Sounds like name/description could work as `alt_name`. At first glance control doesn't map well to `access`, given "Open or Closed" doesn't really provide any further information here. "Open" and "Closed" aren't two separate values, correct? Table order sounds discardable.

**Comment by jakecoolidge** [comment]
I think in this case, "Open or Closed" just means it's a section that is periodically closed, but it doesn't indicate when (depends on seasonal weather conditions, I imagine). "Ungated" indicates the road is open year-round without restriction. In Yellowstone, entire roads will be closed for the winter, while BLRI will close more localized sections...so maybe that's my more general question--is this something we want to capture in Places, and if so, which OSM tag might we use?

**Comment by chadlawlis** [comment]
In this case, given how generic these values are (we don't know the conditions under which these segments are open vs. closed), this might be difficult to capture in Places. I don't see any `access` tags that would be of use here http://wiki.openstreetmap.org/wiki/Key:access.

@nateirwin will structured data address any road access conditions?

**Comment by nateirwin** [comment]
We are storing real-time road status information outside of Places, in Live.

That said, there may be a use for capturing general seasonal closures, gate information, etc. within Places itself. I would say the defining line between Places and Live is "how often does the information change?" Gate locations don't change often, nor do general rules about season closure (e.g. Elk Fork Road is closed December 1st - April 15th every year).

Attributes, however, that reflect current status should be maintained in Live.

I think we will end up expanding Places in the future to support this temporal data, but for now this is the distinction.

Clear as mud?

**Comment by jakecoolidge** [comment]
That makes sense to me--if a cyclical road closure is nearly as established as the geometry of the road itself, it seems like we could capture this in Places, and leave more rapidly changing conditions to Live. Maybe like Chad experienced, I couldn't immediately see a way to support cyclical road closures (like the Elk Fork Road example) with OSM tags, but I figured that was more due to my lack of familiarity with some of these special use-case tags. OSM seems to lack a coherent/consistent way of capturing this. ?

**Comment by chadlawlis** [comment]
Thanks @nateirwin, this makes sense to me.

@jakecoolidge, if the data included a time or date range during which the road segment is open or closed we could use the conditional key, e.g. `access:conditional=no @ (Jan-Mar)` (see http://wiki.openstreetmap.org/wiki/Conditional_restrictions#Value).

In this case it sounds like the BLRI data doesn't have specific conditions under which a road segment is open or closed, which is why it doesn't seem fit for inclusion in Places. The other control value is "Ungated" - if it was "Gated" we could add that using `barrier=gate` http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dgate.

**Comment by nateirwin** [comment]
So `barrier=gate` is another tough one. I feel like we should capture gates as points, even though in some research I did on this topic it seems that it is appropriate to tag lines as `barrier=gate`, as well.

**Comment by chadlawlis** [comment]
Agreed to gates as points. In this case the only data we have for BLRI is that a road segment is "Ungated" though, right @jakecoolidge? In which case I don't think this warrants or aligns with a tag (one would assume all roads are ungated).

**Comment by jakecoolidge** [comment]
Sounds like you can't say "this road is subject to occasional closures" if you don't know when it closes? In that case, I think I'll close this BLRI-related issue for now. The conditional key mentioned above could be useful in parks like Yellowstone, though.
