### ISSUE TITLE
White House label in nps-places-boundaries

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#83]
for `zoom<=14` in `nps_park_labels` the White House labels Lafayette Square and then `zoom>=15` in `nps_park_labels_15` the name changes to White House.

Are there two places here that need to be labeled?

**Comment by jimmyrocks** [comment]
We moved the White House point and changed it's label at one point when we were building Park Tiles.
https://github.com/nationalparkservice/mapbox-studio-projects/blob/1b38b6b8eff82f8a21fd3f7d8dc94a0931f8c2f7/park_tiles/park_tiles_data_process/nps_data_compilation/scripts/cleanup/label_points_tasks.sql#L51-58
https://github.com/nationalparkservice/mapbox-studio-projects/blob/1b38b6b8eff82f8a21fd3f7d8dc94a0931f8c2f7/park_tiles/park_tiles_data_process/nps_data_compilation/scripts/cleanup/label_points_tasks.sql#L135-136

Lafayette Square is a separate park located directly north of the White House, so the two labels shouldn't conflict as long as we are setting their labels to display at the right time

**Comment by mtaylorlong** [comment]
This issue seems to have resolved itself in the new parks table.
