### ISSUE TITLE
Remove orphan nodes from GOGA

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#86]
There are a lot of orphan nodes showing up in GOGA, possibly from a failed upload. Many of them look like intended building vertices, some others are standalone. Fortunately the ones intended as building vertices have the appropriate building footprint underneath, so there is no need to retry any import. All nodes are tagged only as `nps:unit_code=goga`.

@jimmyrocks can you remove these directly from the database? I've been removing a number of them manually, but there appear to be quite a few.

**Comment by jakecoolidge** [comment]
I think I can do this using JOSM--I'll look into it and report back here.

**Comment by jakecoolidge** [comment]
I just removed 638 nodes that fit the criteria. If you encounter any others, let me know. Something for a future conversation--how these nodes get created in the first place...
