### ISSUE TITLE
DC park boundary updates

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#87]
From @johnpauls

1) This is from the Suitland Parkway which heads east out of Washington DC.
![image](https://cloud.githubusercontent.com/assets/5996979/8982912/a9a0f5a0-3693-11e5-8468-c92c87b772c1.png)

There is a label there "National Capital Parks" which should either be Suitland Parkway or National Capital Parks East. I don't think there is anything that is called National Capital Parks.

2) There are many overlapping boundaries at this unit, such as 

![image](https://cloud.githubusercontent.com/assets/5996979/8983021/8d43551e-3694-11e5-8103-8e32014e4afd.png)

and

![image](https://cloud.githubusercontent.com/assets/5996979/8983035/a05f4054-3694-11e5-8b4f-17353750ebe1.png)

3) The boundary seems shifted for Jones Point Park, part of George Washington Memmorial Parkway in VA, across the river from Oxon Cove Park in MD. It looks like the lighthouse in not in the park. 

![image](https://cloud.githubusercontent.com/assets/5996979/8983111/6c4d1af6-3695-11e5-942d-86076deeed29.png)

4) Label for Lincoln Memorial is far from the building 
![image](https://cloud.githubusercontent.com/assets/5996979/8983225/80380796-3696-11e5-8795-5f636fce84cb.png)

At zoom level 14, the Korean War Veterans Memorial label is right on the Lincoln Memorial. 

That is what I have for now, but I am not sure that everything that should be labeled in DC is, as there are lots of small sites, some of which are "official" parks, and some are not, and I have to check to see which are which.

**Comment by johnpauls** [comment]
An update - the place marked as "National Capital Parks' should be Suitland Parkway.

**Comment by makella** [comment]
more on boundaries from @johnpauls:

@nateirwin   Here are a couple of examples.  

Here is Piscataway Park in Maryland from our GIS (may not be the most current data):

![image](https://cloud.githubusercontent.com/assets/5996979/9038071/6cdec2e4-39bf-11e5-91e9-7fb2a5b62d84.png)

Green is NPS owned, the areas in yellow are mostly private homes with a scenic easement and a few farms.  Large parts of the are consists of private homes on wooded lots.
Here it is from Parktiles 3 link above:

![image](https://cloud.githubusercontent.com/assets/5996979/9038692/4e79862c-39c4-11e5-90f3-916f90e59b46.png)

Currently, the park appears to be one large natural area, are all the local roads and private homes are hidden. Also,there are road segments that go nowhere as only the parts on NPS owned land are displayed. Note also River Road on the far west side. If you zoom in you see:
![image](https://cloud.githubusercontent.com/assets/5996979/9038186/7342c8fa-39c0-11e5-84ac-ef46e95e5a0b.png)

There is a double polygon, but also the road does not match up inside vs. outside the park.

Here in Antietam, also in Maryland on our GIS:
![image](https://cloud.githubusercontent.com/assets/5996979/9038268/12242914-39c1-11e5-993c-a31c98b64ed1.png)

Again green is NPS, yellow is easement, white w/red outline is private with no easement.

Here is the same view from ParkTiles
![image](https://cloud.githubusercontent.com/assets/5996979/9038294/49827e56-39c1-11e5-8e2a-6e32d4840a11.png)

In this case, as much of the NPS owned part of the battlefield is in agriculture (crops, soybeans) with historic farm houses on the land. The private land is also agriculture and older homes, so it can be hard to tell where NPS boundaries are when you are there.

**Comment by mtaylorlong** [comment]
@cwlawlis802: This one relates so closely to all the boundary work you're doing in NACA that I'm going to wait and got through these when we've gotten all that sorted out. I'm guessing your work may resolve some of these issues.

**Comment by chadlawlis** [comment]
All of these issues should be resolved with our NCR update #347. Closing.
