### ISSUE TITLE
Projection issue: HALE and AMME

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#90]
From @ryanjhodge

Possible projection issue in the Pacific Islands Region.  See screenshots of HALE and AMME below.  It looks like those boundaries should be lining up with the coast.

HALE
![capture](https://cloud.githubusercontent.com/assets/4172213/8973164/9f48833e-3616-11e5-9123-3efd860aefd1.PNG)

AMME
![capture2](https://cloud.githubusercontent.com/assets/4172213/8973173/b255a8ee-3616-11e5-8e6a-c2271fab64b0.PNG)

**Comment by jimmyrocks** [comment]
HALE
![image](https://cloud.githubusercontent.com/assets/98192/9481936/14527712-4b4c-11e5-9f9b-d514bc1c902e.png)
Our current boundary is in Light Blue
The Boundary from the (Lands Dataset / IRMA / Roger) is in Red
Where they both overlap is a purple color

The Lands Dataset is far better, but there is a big chunk that is not included in Lands.
Do we have a better dataset that we can use?

The AMME boundary is much better in Lands, so we are going to use it for our next release.

@ryanjhodge?

**Comment by jakecoolidge** [comment]
AMME looks good, not sure about HALE. I'm going to close this issue and open a separate one solely for HALE.
