### ISSUE TITLE
KLGO- Seattle Unit Label and point are off

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#91]
From @ryanjhodge

Klondike goldrush Seattle Unit - The Visitor Center is on 2nd Ave and Jackson.  There's a brown building outline of it on the map already (from Places?). But the VC icon is currently showing up Northwest of there at Marion St and Western Ave.  I've visited this unit before and I'm pretty sure the whole unit is comprised of just one building (the VC on 2nd Ave).  The label is also "off".

**Comment by jimmyrocks** [comment]
Move this to 47.59937N, 122.33195W

**Comment by nateirwin** [comment]
Fixed the Visitor Center and headquarters points. We still need to fix the label though.

**Comment by jimmyrocks** [comment]
The label should be moved in the next release

**Comment by chadlawlis** [comment]
Looks like everything is all set here: http://insidemaps.nps.gov/park-tiles-3/#19/47.59932/-122.33207

![park tiles 3 insidemaps 2016-02-02 13-17-25](https://cloud.githubusercontent.com/assets/1238636/12763007/591217d6-c9af-11e5-8bb6-0969b833925f.jpg)
