### ISSUE TITLE
Add highway=steps

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-data#92]
http://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps

There are a lot of staircases in parks, and this would be useful to have in our map

**Comment by jakecoolidge** [comment]
I agree. I imported ways to GOGA with this tag as a demonstration. If I hadn't used the tag, information about GOGA's staircases would have been lost. Several beaches and hillsides are accessed via stairs in this park.

**Comment by jimmyrocks** [comment]
Thanks for preserving that information at least! I was looking at some GATE
beach access areas, and realized that it's very useful to know where stairs
are.

**Comment by chadlawlis** [comment]
Land Recreation > Trail > "Steps"
