### ISSUE TITLE
John F Kennedy Center for the Performing Arts (DC) is not a NPS unit

### ISSUE THREAD

**Issue by johnpauls** [nationalparkservice/places-data#94]
Currently the Kennedy Center in DC is marked as an NPS unit. It used to be one, but it was spun off in 1994.

**Comment by chadlawlis** [comment]
Done and done. Removed from CartoDB parks along with places_boundaries parks, parks_poly, and parks_line:

``` sql
DELETE FROM parks WHERE unit_code = 'jofk';
DELETE FROM parks_poly WHERE unit_code = 'jofk';
DELETE FROM parks_line WHERE unit_code = 'jofk';
```
