### ISSUE TITLE
Populate parks table carto fields for KEAQ

### ISSUE THREAD

**Issue by johnpauls** [nationalparkservice/places-data#95]
Currently it appears at level 15 - could it appear at level 12 or 13 instead?

**Comment by mtaylorlong** [comment]
I've looked into this for the latest PT3 update, and we seem to be missing our record of this park in our `parks` table. Looking at our geocoder it seems we might still have the polygon. 

@cwlawlis802: Will you restore this record in the main `parks` table and assign a point with the centroid? Let me know here when it's done and I'll set the min_zoom settings.

**Comment by chadlawlis** [comment]
Yup, this somehow disappeared from the parks table on the server but remained in the CartoDB parks table. So, I exported the geometry and re-inserted the record with geometry back into the parks table on the server, along with parks_poly and parks_line.

I set the min_zoom_poly = 17, as it was in CartoDB. Feel free to tweak @mtaylorlong. All other carto fields need to be populated as well.

**Comment by mtaylorlong** [comment]
Done! Kenilworth will be labeled at zoom 12. Also set min_zoom_poly to 14 so the boundary shows up in pt3.
