### ISSUE TITLE
unit code uppercase and lowercase in nps.nps-places-data

### ISSUE THREAD

**Issue by makella** [nationalparkservice/places-data#96]
In the `nps.nps-places-data` MB Studio source, I've noticed that in the `nps_places_roads_and_trails` layer that the 'unit_code' for BLRI (area I'm working on) is `blri` for some roads and `BLRI` for others.

**Comment by nateirwin** [comment]
I noticed this too. We should definitely convert everything to lower-case before pushing it out to CartoDB and Mapbox.

**Comment by jimmyrocks** [comment]
I've noticed a few things that I'd like to change about the unit_code in
places.
Right now if you enter a unit_code in iD, it'll take whatever you put in,
even if the capitalization is wrong
Another issue if you combine two objects with different unit_codes, iD will
concatenate the unit_codes into something like "gate;stli"

Would it be acceptable to everyone if i replaced all unit_codes with just
the first 4 letters and made them lower case?

**Comment by jakecoolidge** [comment]
yes, totally.

**Comment by nateirwin** [comment]
Works for me.

**Comment by jimmyrocks** [comment]
If everyone's ok with it, I'll can either put that process into iD or lock
it on the database side.
I'm leaning toward doing it in iD just because there may be some edge cases
where we don't want to database to be manipulating our tags.
Plus I could see that workflow being a little harder to document.

**Comment by nateirwin** [comment]
My vote is iD

**Comment by jimmyrocks** [comment]
https://github.com/nationalparkservice/places-editor/commit/2c8c8085968f80a2bfa2c1988132ba9d8560b2cd
