### ISSUE TITLE
SER trails

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#99]
Chris: "I have attached trails data for parks that (are missing from Places).  
(ABLI, ANDE, BISC, CANA, CARL, COWP, DESO, FOCA, FODO, GUCO, GUIS, HOBE, JELA, MOCR, NATR, OCMU, OVVI, RUCA, SAJU, SEMO, STRI, TIMU, VIIS)"

**Comment by jakecoolidge** [comment]
completed

**Comment by nateirwin** [comment]
Go, @jakecoolidge!
